antlr4-maven-plugin/pom.xml
bild.py
pom.xml

This basically sets the version number to 4.5-SNAPSHOT for pushing to maven central snapshots area: `https://oss.sonatype.org/content/repositories/snapshots`.  to be safe I changed the version within all of the pom.xml files as well as bild.py but we are building things with bild.py only.   We use maven only to do the install/deploy once we have the jars we want. We do this with some [magical commandline stuff](https://github.com/antlr/antlr4/wiki/Deploying-ANTLR-mvn-artifacts). Once we have finalized things than I can change the version to 4.5, create the new jars, and push the release.

Freshen maven 2

---

runtime/Java/src/org/antlr/v4/runtime/ANTLRErrorStrategy.java
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/test/org/antlr/v4/test/rt/gen/Generator.java
tool/test/org/antlr/v4/test/rt/gen/grammars/ParserErrors/SingleSetInsertionConsumption.st
tool/test/org/antlr/v4/test/rt/gen/grammars/ParserErrors/SingleTokenDeletionConsumption.st
tool/test/org/antlr/v4/test/rt/java/TestParserErrors.java

Fixes: https://github.com/antlr/antlr4/issues/795
As discussed, this changes the code generation for `Parser`s so that they only `consume` when they do *not* need to `recoverInline`. I've added tests which fail before the change (in both cases, the `set` rule's final consumed token was `d`), and updated the documentation to warn that `recoverInline` will handle it's own token consumption.
(As a side note, I see that the build and test infrastructure has changed - it would be nice if there was a little bit of documentation about that. It took me a while to figure out the test generator, and I could never get `bild.py` to do what I wanted.) [Edit: parrt adding link to [building ANTLR itself](https://github.com/antlr/antlr4/wiki/How-to-build-ANTLR-itself)]

Fix excess token consumption after `recoverInline`

---

contributors.txt
runtime/Java/src/org/antlr/v4/runtime/tree/gui/TreeViewer.java

It changes the TestRig's JDialog to remember its state between launches. When it gets shutdown, it stores the following information using [standard Java Preferences API] (http://docs.oracle.com/javase/8/docs/technotes/guides/preferences/overview.html) and restores them during consequent launch:
* Dialog's width and height
* Dialog's position on screen
* The TreeView component's scale factor
* The placement of the splitpane divider

Makes TestRig's dialog to save and restore its state

---

contributors.txt
tool/src/org/antlr/v4/codegen/JavaTarget.java

Goto isn't in the reserved words, so it doesn't get caught when compiling a grammar that uses it as a rule name.

Add goto to reserved words for java.

---

tool/src/org/antlr/v4/analysis/LeftRecursiveRuleTransformer.java
tool/src/org/antlr/v4/parse/GrammarTreeVisitor.g
tool/src/org/antlr/v4/semantics/SemanticPipeline.java
tool/src/org/antlr/v4/tool/ErrorType.java
tool/test/org/antlr/v4/test/tool/TestLeftRecursionToolIssues.java

We didn't check for left-recursive rules that didn't follow pattern that would lead to error. added unit tests. Passes all tests. Fixes #822, Fixes #855.

Check for nonconforming left-recursive rules.

---

tool/src/org/antlr/v4/Tool.java
tool/test/org/antlr/v4/test/tool/TestCompositeGrammars.java

Fixes #823. For the record, there are lots of errors that ask for g.fileName and not `tokenOfErrorLocation.getInputStream().getSourceName()`.

Report unknown rule error in proper file.

---

contributors.txt

I want to contribute to the antlr/antlr4-python3 project.
Signed-off-by: jcbrinfo <jcbrinfo@users.noreply.github.com>

Add @jcbrinfo as a contributor

---

runtime/Java/src/org/antlr/v4/runtime/Parser.java
runtime/Java/src/org/antlr/v4/runtime/ParserRuleContext.java
runtime/Java/src/org/antlr/v4/runtime/tree/SyntaxTree.java
tool/test/org/antlr/v4/test/tool/TestParserInterpreter.java

Check eof in tree

---

runtime/Java/src/org/antlr/v4/runtime/atn/AmbiguityInfo.java
runtime/Java/src/org/antlr/v4/runtime/atn/LookaheadEventInfo.java
runtime/Java/src/org/antlr/v4/runtime/atn/ProfilingATNSimulator.java

This is internal to profiling ATN simulator so hopefully won't mess up binary compatibility with 4.5.

LookaheadEventInfo now tracks alt taken by decision.

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Index.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Performance/ExpressionGrammar.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Performance/ExpressionGrammar_1.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Performance/ExpressionGrammar_2.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Performance/Index.stg
tool/test/org/antlr/v4/test/runtime/java/Java.test.stg
tool/test/org/antlr/v4/test/tool/TestPerformance.java

Move TestPerformance.testExpressionGrammar to the runtime test suite

---

runtime/Java/pom.xml
runtime/Java/src/org/antlr/v4/runtime/RuleContext.java
runtime/Java/src/org/antlr/v4/runtime/misc/TestRig.java
runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java
tool-testsuite/test/org/antlr/v4/test/tool/InterpreterTreeTextProvider.java
tool-testsuite/test/org/antlr/v4/test/tool/TestAmbigParseTrees.java
tool-testsuite/test/org/antlr/v4/test/tool/TestGrammarParserInterpreter.java
tool-testsuite/test/org/antlr/v4/test/tool/TestLookaheadTrees.java
tool/pom.xml
tool/src/org/antlr/v4/gui/BasicFontMetrics.java
tool/src/org/antlr/v4/gui/GraphicsSupport.java
tool/src/org/antlr/v4/gui/JFileChooserConfirmOverwrite.java
tool/src/org/antlr/v4/gui/PostScriptDocument.java
tool/src/org/antlr/v4/gui/SystemFontMetrics.java
tool/src/org/antlr/v4/gui/TestRig.java
tool/src/org/antlr/v4/gui/TreeLayoutAdaptor.java
tool/src/org/antlr/v4/gui/TreePostScriptGenerator.java
tool/src/org/antlr/v4/gui/TreeTextProvider.java
tool/src/org/antlr/v4/gui/TreeViewer.java
tool/src/org/antlr/v4/gui/Trees.java

move swing related stuff out of runtime package into org.antlr.v4.gui

---

.travis.yml
runtime-testsuite/pom.xml
runtime-testsuite/src/org/antlr/v4/testgen/TestGenerator.java
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java
runtime/JavaScript/src/antlr4/FileStream.js
tool-testsuite/pom.xml
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

It was recently noticed that travis-ci only tests the java runtime. This somewhat breaks the purpose of the ci. This PR clarifies test generation paths and enables testing of all targets except browsers

Fix maven test scope

---

contributors.txt
runtime/JavaScript/src/antlr4/FileStream.js
runtime/JavaScript/src/antlr4/Utils.js
runtime/JavaScript/src/antlr4/tree/Tree.js

It provides proper implementation for visit function which is essential for visitors. It fires appropriate visit function in visitors. It behaves in the same way as java implementation.
I have also fixed bug that prevented running runtime on nodejs. There is no importScripts symbol in scope so JS throws exception - we need to use typeof operator to avoid it.

Added proper visit function in ParseTreeVisitor

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

When using labeled rules, the doc comments in the emitted C# base listener and visitor classes contain a reference that does not exist. This produces a compiler warning. However, the corresponding interfaces are correct. It seems appropriate to use those comments for the base classes.

Update doc comment in C# base listener and visitor classes

---

tool/src/org/antlr/v4/gui/TreeViewer.java

The `selectedTree.getSelectionPath()` return null if nothing is selected.
Added check to avoid NPE:
```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.antlr.v4.gui.TreeViewer$4.valueChanged(TreeViewer.java:376)
at javax.swing.JTree.fireValueChanged(JTree.java:2921)
at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3382)
at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
at javax.swing.tree.DefaultTreeSelectionModel.removeSelectionPaths(DefaultTreeSelectionModel.java:502)
at javax.swing.JTree.removeDescendantSelectedPaths(JTree.java:3714)
at javax.swing.JTree.setExpandedState(JTree.java:3597) …
```

TreeViewer: Fix NPE

---

tool/src/org/antlr/v4/gui/TestRig.java

The help and error message from the TestRig program refers to the old `runtime.misc` instead of the new `gui` package:
```
java org.antlr.v4.runtime.misc.TestRig GrammarName startRuleName
[-tokens] [-tree] [-gui] [-ps file.ps] [-encoding encodingname]
[-trace] [-diagnostics] [-SLL]
[input-filename(s)]
Use startRuleName='tokens' if GrammarName is a lexer grammar.
Omitting input-filename makes rig read from stdin.
```

Update TestRig.java help text with correct package name

---

doc/creating-a-language-target.md

In the “Getting started” chapter of “Creating an ANTLR Language Target” the “upstream” remote is mentioned. The documentation now explains that this remote must be created manually.

Doc: more details on remotes `origin` and `upstream` in local Git repo

---

tool/src/org/antlr/v4/gui/TestRig.java

After loading and casting the parserClass in TestRig#process using `cl.loadClass(parserName).asSubclass(Parser.class)` there is a check if the class returned by `#asSubclass` is not null:
```
parserClass = cl.loadClass(parserName).asSubclass(Parser.class);
if ( parserClass==null ) {
System.err.println("Can't load "+parserName);
}
```
The method `#asSubclass` will never return `null`, but throw an `ClassCastException` when the cast is not valid, therefore the check can be removed.
See also: [TestRig#process Documentation](http://docs.oracle.com/javase/6/docs/api/java/lang/Class.html#asSubclass(java.lang.Class))

Extra 'null' check in TestRig#process

---

tool/src/org/antlr/v4/codegen/ActionTranslator.java

The parameter `RuleFunction rf` in `ActionTranslater#translateActionChunk` may be `null`.
The method's implementation takes care of this by checking `rf` before making its `ruleCtx` the translator's nodeContext:
```
if ( rf!=null ) translator.nodeContext = rf.ruleCtx;
```
However in the statement following this code the check for `rf!=null` is missing. This will lead to a `NullPointerException` when  `altLabel` is defined and `rf` is `null`:
```
if ( altLabel!=null ) translator.nodeContext = rf.altLabelCtxs.get(altLabel);
```
To avoid the problem only access `rf.altLabelCtxs` when `rf` is not null:
```
if ( rf!=null ) {
translator.nodeContext = rf.ruleCtx;
if ( altLabel!=null ) translator.nodeContext = rf.altLabelCtxs.get(altLabel);
}
```

Possible NullPointerException in ActionTranslater#translateActionChunk

---

contributors.txt
doc/listeners.md

- ParserRuleContext does not have type parameters
- Confusing sentence cleaned up a little

Fixing typos in listeners.md

---

runtime/Java/src/org/antlr/v4/runtime/misc/Utils.java

It is used nowhere but imports `java.awt.*`.
Android runtime has no `java.awt.*` classes so Android SDK build tools say "it includes
invalid packages". It's better if antlr4-runtime has no dependency on `java.awt.*`.
Thanks.

Remove unused Utils#waitForClose() in antlr4-runtime

---

contributors.txt
runtime/JavaScript/src/antlr4/BufferedTokenStream.js

I noticed a minor mistake in the JavaScript runtime. From what I can tell the `tokenIndex` property is never assigned and thus is `undefined`
Note that in JavaScript,
```js
undefined < anyInteger
```
returns `false`

Fix mistake in tokenIndex bounds check

---

runtime/JavaScript/src/antlr4/LL1Analyzer.js

The PredictionContext should be passed to the ATNConfig constructor in the first argument, the `params` object. Instead, it is being passed as the second argument which is intended to be the config.

JS: LL1Analyzer passing PredictionContext incorrectly to ATNConfig ctor

---

runtime/JavaScript/src/antlr4/atn/LexerActionExecutor.js

LexerActionExecutor caches its hash string in a member called
'hashString'. However, the class also has a method with the
same name which leads to unexpected results.
The member has been renamed to '_hashString' to avoid the name
clash.

JS: LexerActionExecutor cached hash string name clashes with function

---

antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java

For grammar-heavy projects, running the generator every time results in a lot of extra compilation that slows down builds. 
This makes it so that the antlr tool is only run when the tokens file either doesn't exist, or is older than the last modification to its grammar.

Only run the maven plugin when needed.

---

contributors.txt
tool/src/org/antlr/v4/analysis/AnalysisPipeline.java
tool/src/org/antlr/v4/analysis/LeftRecursiveRuleAnalyzer.java
tool/src/org/antlr/v4/analysis/LeftRecursiveRuleTransformer.java
tool/src/org/antlr/v4/automata/ATNFactory.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java
tool/src/org/antlr/v4/automata/ParserATNFactory.java
tool/src/org/antlr/v4/codegen/OutputModelWalker.java
tool/src/org/antlr/v4/codegen/Target.java
tool/src/org/antlr/v4/codegen/model/decl/AltLabelStructDecl.java
tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java
tool/src/org/antlr/v4/misc/Graph.java
tool/src/org/antlr/v4/misc/Utils.java
tool/src/org/antlr/v4/parse/GrammarToken.java
tool/src/org/antlr/v4/parse/ScopeParser.java
tool/src/org/antlr/v4/tool/AttributeDict.java
tool/src/org/antlr/v4/tool/ErrorType.java
tool/src/org/antlr/v4/tool/Grammar.java
tool/src/org/antlr/v4/tool/GrammarParserInterpreter.java
tool/src/org/antlr/v4/tool/GrammarTransformPipeline.java
tool/src/org/antlr/v4/tool/LeftRecursiveRule.java

This fixes all errors (but not the numerous warnings) reported by Oracle JDK 1.8.0_72 in a simple run of `mvn javadoc:javadoc`. Mostly unescaped `>`, `<`, `&`, but also self-closed `<p/>` and similar. Plus I deleted two commented-out functions, since the function body got included in the doc comment, and since git will be able to recover them so removing them completely helps keep the sources cleaner.

Fix Javadoc errors

---

runtime/JavaScript/src/antlr4/atn/ATNConfig.js

When an ATNConfig instance is created with an alt of 0, it is possible for it to be incorrectly changed to null due to its "falsey" nature.

JS: ATNConfig can incorrectly change "alt" of 0 to null

---

tool/src/org/antlr/v4/codegen/target/Python2Target.java

Just added return to the list of python2 keywords. It appears to be missing in the Python3 Target as well.

Fixing Issue #1148

---

doc/targets.md

Currently that table doesn't render as a table on GitHub.

Format feature parity table as markdown table

---

contributors.txt
runtime/Java/src/org/antlr/v4/runtime/Vocabulary.java
runtime/Java/src/org/antlr/v4/runtime/VocabularyImpl.java

Add Vocabulary.getMaxTokenType()

---

runtime/JavaScript/src/antlr4/atn/LexerActionExecutor.js

According to the corresponding Java implementation, the equals() method for LexerActionExecutor should be doing an equals() test on each of the actions rather than testing the Array reference is equal.

JS: Do deep Actions array comparison in LexerActionExecutor equals()

---

runtime/JavaScript/src/antlr4/atn/SemanticContext.js

The OR toString() method was incorrectly added to the AND prototype

JS: Fix copy-and-paste error in OR SemanticContext toString() method

---

runtime/JavaScript/src/antlr4/atn/SemanticContext.js

AND.evalPrecedence() method is attempting to invoke a method on a non-existent class "SemanticPredicate". It should be using "SemanticContext" instead.

JS: SemanticPredicate should be SemanticContext

---

tool/src/org/antlr/v4/codegen/DefaultOutputModelFactory.java

This ensures that the stop token has been set before the `@after` action gets executed.
This is one way to fix #1129. Another would be adding the corresponding line directly to the method template. But the postamble-based approach should be more flexible in the long run.

Set stop token in postamble

---

contributors.txt
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/node/BaseTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java

the old paths contained a / at the beginning of the path e.g. "/C:/" but the expected path is "C:/" and due to this all test for the targets javascript, python and c# failed on windows.

update the runtime paths to work in windows

---

runtime/Python2/src/antlr4/IntervalSet.py
runtime/Python2/src/antlr4/ListTokenSource.py
runtime/Python2/src/antlr4/PredictionContext.py
runtime/Python2/src/antlr4/atn/ATNConfigSet.py
runtime/Python2/src/antlr4/atn/ATNState.py
runtime/Python2/src/antlr4/atn/LexerATNSimulator.py
runtime/Python2/src/antlr4/atn/PredictionMode.py
runtime/Python2/src/antlr4/atn/SemanticContext.py
runtime/Python2/src/antlr4/dfa/DFAState.py
runtime/Python2/src/antlr4/tree/Trees.py
runtime/Python2/src/antlr4/xpath/XPath.py
runtime/Python3/src/antlr4/IntervalSet.py
runtime/Python3/src/antlr4/ListTokenSource.py
runtime/Python3/src/antlr4/PredictionContext.py
runtime/Python3/src/antlr4/atn/ATNConfigSet.py
runtime/Python3/src/antlr4/atn/ATNState.py
runtime/Python3/src/antlr4/atn/LexerATNSimulator.py
runtime/Python3/src/antlr4/atn/PredictionMode.py
runtime/Python3/src/antlr4/atn/SemanticContext.py
runtime/Python3/src/antlr4/dfa/DFAState.py
runtime/Python3/src/antlr4/tree/Trees.py
runtime/Python3/src/antlr4/xpath/XPath.py

The Python implementations are completely synchronous
with the Java version even if some of the constructs
can be expressed with simpler Python solutions. These are
typically the all, any, count, next builtins or the list
comprehensions, etc. Beside using them makes the code
clearer, they are also prefered by the standard and can
result in performance speedup. The patch contains such
equivalent transformations in the Python targets.

Make Python targets more pythonic.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

The default pass statements were missing from the LL1AltBlock's
template in case of Python targets, which generated conditional statements
without body in some cases and ended in syntax error. The patch fixes this.

Add missing default pass statements to Python targets.

---

.gitattributes

During review of #1304, I noticed that the repository did not include a **.gitattributes** file to ensure EOL characters are handled consistently across developers who may vary.
📝 All files already in the repository are already handled consistently. This file ensures new developers and/or developers working on new machines continue to do the same things we've always been doing.

Add default .gitattributes

---

.editorconfig
contributors.txt

An EditorConfig file allows easy config of the IDE editor when loading a new project (like Antlr4).
See http://editorconfig.org/ for more info.

Add .editorconfig

---

pom.xml
runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTestAssert.java
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java

optionally delegate assertEquals to RuntimeTestSupport delegate, to enable target specific assertXxx behaviour (work around the different algo in C#)
also fixed an issue where mono was not found on MacOSX

enable target specific assertXxx behaviour

---

doc/parser-rules.md
tool-testsuite/test/org/antlr/v4/test/tool/TestScopeParsing.java
tool/src/org/antlr/v4/parse/ScopeParser.java
tool/src/org/antlr/v4/tool/Attribute.java
tool/src/org/antlr/v4/tool/AttributeDict.java

Support `x:T` argument/local notation in `[...]` blocks. Updated scope testing. Updated doc.  Any target can use `x:T` or `T x` notation as we parse into generic `Attribute` object and code generators do the right thing.

Add postfix types in args like x:T for Swift target

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

[@pboyer](https://github.com/pboyer), [@millergarym](https://github.com/millergarym)
Creating Temp Var _x looks to me error prone.
Following java.stg seems to me more robust.
In this way Var re declaration issue does not arise.
For [_x redeclared in this block](https://github.com/pboyer/antlr4/issues/88) this seems to be a safer solution than the PR [Fix for redeclared error is generated Go code](https://github.com/pboyer/antlr4/pull/89)
Congratulations to Antlr team and specially to Go contributors

Stgwotempvar

---

contributors.txt
runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
tool-testsuite/test/org/antlr/v4/test/tool/TestActionTranslation.java
tool/src/org/antlr/v4/codegen/ActionTranslator.java

ActionTranslator.java - the fix
TestActionTranslation.java - regression test
BaseTest.java - allow left-recursive rule in test

Fixing issue #1295 - $e.v yields incorrect value for recursive rule

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

The Python templates contained superfluous semicolons after
the sync call of errHandler. This patch removes them.

Remove unnecessary semicolons from Python targets.

---

runtime/Python3/src/antlr4/Parser.py

The last parameter name of Parser::enterRule in the Python3 runtime
was mistakenly combined with its type. The patch fixes this.

Fix typo in the parser of the Python3 runtime.

---

runtime/Python2/src/antlr4/atn/PredictionMode.py
runtime/Python3/src/antlr4/atn/PredictionMode.py

The PredictionMode::hasSLLConflictTerminatingPrediction method aims to
create ATNConfig objects from another ATNConfig and SemanticContext
objects. In case of the Python targets, the initialization
happened without keyword arguments. Since the called **init**
method had default values set for all the parameters, the parameter
substitution worked by indices. As a consequence, the first ATNConfig
parameter was wrongly interpreted as an ATNState and the SemanticContext as
an alternative. The patch fixes this by adding the missing keywords.

Fix initialization of ATNConfig when computing SLL prediction termination condition.

---

runtime/Cpp/runtime/src/support/Any.h

* There was an inconvenience that an Any created with a nullptr returned false for isNull(), resolved by adding the ctor
* removed warning [forcing value to bool 'true' or 'false'] when calling is<>

CPP runtime :  Added a specialized ctor for Any for nullptr.

---

runtime/Python2/src/antlr4/ListTokenSource.py
runtime/Python3/src/antlr4/ListTokenSource.py

At the end of the nextToken() function, setting the eofToken field was
attempted without the 'self' keyword, resulting in accessing
and setting a new local and unused variable. The patch supplements
the missing 'self' keywords for both targets.

Fix eofToken access in ListTokenSource.nextToken() by Python targets.

---

runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
runtime/Python3/src/antlr4/atn/ParserATNSimulator.py

The Java target initializes the conflictingAlt local variable
based on the conflictingAlts property of the target state.
However, the Python targets reset it to None. The patch makes the
initializations consistent.

Fix the initialization of conflictingAlts in execATN in Python targets.

---

tool/src/org/antlr/v4/Tool.java

As reported on the mailing list in 2007 and also in the Gradle forums in the last years, it is currently impossible to define two different grammars in different packages using separate lexer and parser files and import the lexer files using `tokenVocab`.
Ultimately the problem is that the referenced `tokenVocab` cannot be resolved when processing a grammar that does not reside in the default package. Using the `-lib` makes it possible to work around this problem for a single package, but this fails to work for multiple grammars in different packages because `-lib` can only be specified once.
This patch allows the `tokenVocab` to specify paths instead of only file names, i.e. it is then possible to write `tokenVocab='com/test/html/HTMLLexer';`
The ANTLR parser allows quoted strings for …

Allow paths as tokenVocab option

---

runtime/Python2/src/antlr4/atn/ATNConfigSet.py
runtime/Python3/src/antlr4/atn/ATNConfigSet.py

The **contains** method of ATNConfigSet used different hashing
function (hash) for indexing the config dictionary than the
getOrAdd method (hashCodeForConfigSet) which filled it.
Furthermore, they also used different methods for comparing
ATNConfig objects. The patch makes them consistent.

Fix comparisons in ATNConfigSet.__contains__ of Python targets.

---

appveyor.yml

This adds a simple configuration file to the root directory which enables use of appveyor.com for Windows-based integration testing.   See a sample build from my fork at    https://ci.appveyor.com/project/BurtHarris/antlr4

Add AppVeyor.yml for Windows contious integration

---

contributors.txt
runtime/Python2/src/antlr4/TokenStreamRewriter.py

Hello, i've added the TokenStreamRewriter to Python2 runtime.
If all goes well i hope to expand on this contribution.
Please advise about how to integrate into the auto-generated test suit if this is necessary.
P.S: Closes ISSUE #1115

add TokenStreamRewriter to Python2 runtime

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

Following code was generated by the cpp backend for the demo project:
```cpp
antlrcpp::Any TParser::StatContext::accept(tree::ParseTreeVisitor *visitor) {
if (dynamic_cast<TParserVisitor*>(visitor) != nullptr)
return ((TParserVisitor *)visitor)->visitStat(this);
//           ~~~~~~~~~~~~~~~~
else
return visitor->visitChildren(this);
}
```
There is a C-Cast used after the class was checked through a dynamic cast.
This could lead to undefined behaviour when casting classes with virtual bases.
This PR changes the cpp template in order to cache the result returned by the dynamic cast to remove the c-cast.

Fix a dangerous c-cast in the cpp codegen

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

The issue here was that I used a := short variable declaration in the template, when there could be multiple assignments of this variable. Hence, duplicate assignment compiler errors were encountered. 
Here, I follow the model set by `Java.stg` and use a single variable declaration. I observed no regressions in the test suite and @ereyes01 was kind enough to test it out on the `Java.g4` grammar. 
I need a verification that the `currentRule.hasLookaheadBlock` field will not provide "false positives". Specifically, we need to be sure that `_alt` is not declared and not used. Go will emit a compile error if a variable is declared and not used. If this is not guaranteed I can provide a simple "proxy" usage to silence the error.
PTAL @parrt.
This is a fix for #1397.

Fix for #1397

---

runtime/Go/antlr/lexer.go
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

@parrt @pboyer 
Clean pull request for redeclared var error.
Create block so _x and _m var are created in a local scope.

Fix for redeclared error is generated Go code. 

---

contributors.txt
runtime/Cpp/runtime/src/RuleContext.cpp

**Problem**
In C++ target, `getText()` returns a string in which the tokens are separated by a comma and a space. On the other hand, Java target returns a string which results from direct appending of the tokens.
**Solution**
Removed comma and space appended to the stringstream in C++ `getText()` for consistency with Java target.
Fix to Issue #1434

Fix to Issue #1434

---

contributors.txt
runtime/Cpp/runtime/antlr4cpp-vs2015.vcxproj
runtime/Cpp/runtime/antlr4cpp-vs2015.vcxproj.filters
runtime/Cpp/runtime/src/tree/pattern/ParseTreePattern.cpp

The VS2015 project for the cpp runtime references a nonexistant file (Tree.cpp) and doesn't reference a file required for compilation and linking (ParseTree.cpp). Additionally, an include directive doesn't compile as ParseTree.cpp is in a subfolder. This should fix the above issues with VS2015.

Update VS2015 cpp runtime project

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

#1459 shows that `la_` may end up being redeclared in generated code.
This variable doesn't need to be declared at all. We can just use inline it.
All tests continue to pass. I used @syn-ful's example code to confirm this now compiles and from basic experimentation, it seems to work as expected.
PTAL @parrt CC @syn-ful

Fix for #1459

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/TestTokenStreamRewriter.java

@antlr/antlr-targets you are free to make runtime lib api tests in your runtime subdirectory. E.g., https://github.com/antlr/antlr4/blob/master/runtime/Python2/tests/TestTokenStreamRewriter.py is the analog of this Java code I'm moving. In my case, it makes most sense to put the test in the runtime-testsuite group not under runtime/java.

move api lib test to runtime tests

---

runtime/Python2/src/antlr4/Parser.py
runtime/Python3/src/antlr4/Parser.py

The consume method of the Parser class calls visitTerminal on both
TerminalNodes and ErrorNodes even if the comment above states that
ErrorNodes should be visited by visitErrorNodes. This behaviour
is also inconsitent with the Java target. The patch fixes this in
both Python targets.

Call visitErrorNodes properly in Python targets.

---

contributors.txt
runtime/Cpp/demo/TLexer.g4

Since Tool generates errors if token have several identical commands, the demo grammar in CppTarget throw an error at compile time.
This Pull Request fix this, by creating a new token.

Fix conflict lexer command in CppTarget demo

---

contributors.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Cpp.test.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Files.stg

This Pull Request fix #1457 
- Ensured that there is no "using namespace" in the generated header files
- Ensured that there is any "using namespace" in runtime/src headers included by antlr-runtime.h:
``$]find runtime/Cpp/runtime/src/ -type f -name *.h -print | xargs grep "namespace" | grep using``

Issue 1457

---

contributors.txt
runtime/Cpp/runtime/src/BufferedTokenStream.h
runtime/Java/src/org/antlr/v4/runtime/BufferedTokenStream.java
runtime/Swift/Antlr4/org/antlr/v4/runtime/BufferedTokenStream.swift

I've found the documentation somewhat confusing at first sight, so thought it would be worth getting it right, even if the fix is quite trivial.
(The patch touches all runtimes where the wording was incorrect.)

Fix documentation of getHiddenTokensToRight in BufferedTokenStream

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt
runtime/Cpp/runtime/src/ANTLRFileStream.cpp
runtime/Cpp/runtime/src/antlr4-common.h
runtime/Cpp/runtime/src/support/Any.h

- add required extra flags to the C++ compiler in CMakeLists.txt
- guard some code with _MSC_VER instead of WIN32
[cut]
Thank you for proposing a contribution to the ANTLR project. In order to accept changes from the outside world, all contributors must "sign" the  [contributors.txt](https://github.com/antlr/antlr4/blob/master/contributors.txt) contributors certificate of origin. It's an unfortunate reality of today's fuzzy and bizarre world of open-source ownership.
Make sure you are already in the contributors.txt file or add a commit to this pull request with the appropriate change. Thanks!
[/cut]

adapt code to compile with msys2 mingw compiler

---

runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java
runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserExecDescriptors.java
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/DefaultErrorStrategy.cs
runtime/Cpp/runtime/src/DefaultErrorStrategy.cpp
runtime/Go/antlr/error_strategy.go
runtime/Java/src/org/antlr/v4/runtime/DefaultErrorStrategy.java
runtime/JavaScript/src/antlr4/error/ErrorStrategy.js
runtime/Python2/src/antlr4/error/ErrorStrategy.py
runtime/Python3/src/antlr4/error/ErrorStrategy.py
runtime/Swift/Antlr4/org/antlr/v4/runtime/DefaultErrorStrategy.swift
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

* Add tests for scenarios presented in the original bug
* Fix `DefaultErrorStrategy.sync` not handling falling off decision rule the same way as `adaptivePredict`
* Fix code generation for `LL1OptionalBlock`
Fixes #1545

Fix multiple problems with optional block bypass at end of rule

---

tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
tool/src/org/antlr/v4/automata/ParserATNFactory.java
tool/src/org/antlr/v4/parse/GrammarTreeVisitor.g
tool/src/org/antlr/v4/tool/ErrorType.java

```
beast:/tmp $ a4.6 T.g4
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
context [/report INTERNAL_ERROR] 1:17 attribute arg isn't defined
error(20):  internal error:
beast:/tmp $ a4.6.1 T.g4
error(181): T.g4:2:4: token ranges not allowed in parser: 'A'..'Z'
```

Fixes #1556.

---

tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
tool/src/org/antlr/v4/semantics/SymbolChecks.java

This fixes the critical regression described in #1543.
A disabled test is also included showing the desired final behavior for error 75.

Disable label checks for left recursive rules

---

tool/src/org/antlr/v4/codegen/model/ElementFrequenciesVisitor.java
tool/src/org/antlr/v4/codegen/model/RuleFunction.java
tool/src/org/antlr/v4/codegen/model/decl/ContextRuleGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextTokenGetterDecl.java

This analysis is required for proper code generation in the TypeScript target when strict null checks are enabled. It also applies to targets intending to differentiate optional values from required values.

Implement support for optional getters

---

runtime-testsuite/pom.xml
runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/TestVisitors.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/VisitorBasic.g4
runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/VisitorCalc.g4

This is a re-implementation of #1566 targeting the Java runtime API specifically. Other targets may follow with their own equivalent implementations.

Add visitor tests for Java runtime API

---

tool/src/org/antlr/v4/codegen/model/ElementFrequenciesVisitor.java
tool/src/org/antlr/v4/codegen/model/RuleFunction.java

These issues were found when I was implementing the new optional element tests for TypeScript.
* Properly handle elements that are optional in some alts but not others
* Properly handle block sets (a group of terminals producing a SetTransition)
* Properly handle OPTIONAL subrule
* Don't use list labels for elements that appear twice in a block set

Fix multiple bugs with the new optional element analysis

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/TestTokenStream.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/VisitorBasic.g4
runtime/Java/src/org/antlr/v4/runtime/BufferedTokenStream.java
tool-testsuite/test/org/antlr/v4/test/tool/TestPerformance.java

Fixes #1584
@antlr/antlr-targets This bug may affect other targets.

Reset BufferedTokenStream.fetchedEOF when calling setTokenSource

---

contributors.txt
runtime/Cpp/runtime/src/tree/ParseTreeProperty.h

- The std::map doesn't have get, put and remove methods. 
- Removed empty InitializeInstanceFields method.

Fix parse tree property

---

contributors.txt
runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake

The include path variable exported by `cmake/ExternalAntlr4Cpp.cmake` doesn't follow up the latest update of the include folder hierarchy. Which may raise compile error on generated cpp/header files since they try to `#include "antlr4-runtime.h"` but the correct path is `#include "antlr4-runtime/antlr4-runtime.h"`.
I modify `ExternalAntlr4Cpp.cmake` so that we don't need to touch the generation of grammar cpp/header files.

Fix wrong include path of antlr4cpp runtime in cmake/ExternalAntlr4Cpp.cmake

---

runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java

I wanted to run the C# tests on a CentOS 7 machine, which doesn't have a new enough `mono` package available to run the tests (we need 4.6).
I built from source, which installs in `/usr/local/bin` by default, but the tests still failed. This PR fixes the issue by looking in `/usr/local/bin` before `/usr/bin` (which is fairly standard for `$PATH` searching).

Look in /usr/local/bin before /usr/bin for mono

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

Since case formatting in Go denotes private verses public the format={lower} is getting in the way.
Currently the only workaround to place the generated code in the same package as the types being used, and these types can't be exported. This is inconvenient and unnecessary. I see know downside to leave the case on the type as set in the grammar.
The `import "./<superClass>"` also get in the way. I tried using superClass to add fields to a parser. This works nicely, but the import needed to be removed by hand. Relative imports are of very limited use in Go. Also in the grammar developer needs an import for the superClass it is trivial to place the import statement in the `@members` block.

Remove lower case formatting on Go types & super import

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestIntegerList.java
runtime/Java/src/org/antlr/v4/runtime/misc/IntegerList.java
runtime/Java/src/org/antlr/v4/runtime/misc/Utils.java

While working on #276 , I found that `Utils.toCharArray(IntegerList)` was silently corrupting `IntegerList`s containing values larger than `0xFFFF`.
The root cause was a cast from `int` to `char`, which silently truncates the (possibly 32-bit input) to 16 bits.
Currently, this doesn't cause issues, because there is no way to add an integer larger than 0xFFFF to an `IntegerList`, but fixing #276 will do this for the first time (serializing a grammar with Unicode literals > `0xFFFF` to an ATN needs to encode `IntegerList`s with values > `0xFFFF`).
In this diff, I fix the issue by:
1. Adding a new method `IntegerList.toCharArray()` and making `Utils.toCharArray(IntegerList)` call that
2. Treating the contents of the `IntegerList` as a series of Unicode code points when serializing to a …

New method IntegerList.toCharArray()

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCodePointCharStream.java
runtime/Java/src/org/antlr/v4/runtime/CodePointCharStream.java

As part of #276 , the Java runtime needs a way to parse an input as a stream of Unicode code points.
Currently, `ANTLRInputStream` treats input as a stream of UTF-16 code units, so even if we add support for Unicode literals > `U+FFFF`, the Java runtime cannot parse such files.
This PR adds a new class `CodePointCharStream` as an alternative to `ANTLRInputStream`, which can be used to parse input files not as UTF-16 code units, but as Unicode code points (stored in an `IntBuffer`).
I included unit tests for all the public methods, as well as a convenience method to create a `CodePointCharStream` from a Java `String`.
Because storing input both as a `String` (in UTF-16) as well as a series of Unicode code points (an array of 32-bit `int`s in an `IntBuffer`) is pretty inefficient, I'll …

New class CodePointCharStream (alternative to ANTLRInputStream)

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestUTF8CodePointDecoder.java
runtime/Java/src/org/antlr/v4/runtime/UTF8CodePointDecoder.java

In order to use the new `CodePointCharStream` from #1626 without causing perf regressions, we need a way to efficiently convert UTF-8 input data (from disk or from network) to Unicode code points.
Java's built-in functionality to do this requires an intermediate conversion to UTF-16, which will be a lot of overhead (both memory and CPU).
This PR introduces a new class `UTF8CodePointDecoder`, modeled on Java's [CharsetDecoder](https://docs.oracle.com/javase/7/docs/api/java/nio/charset/CharsetDecoder.html), which decodes UTF-8 data in a `ByteBuffer` to Unicode code points stored in an `IntBuffer`.
To avoid lots of comparisons in a hot codepath, I used a lookup table to map the UTF-8 leading byte to the number of needed trail bytes.
(We could use the same lookup table for trailing bytes, but …

New class UTF8CodePointDecoder

---

runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/browser/BaseBrowserTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/node/BaseNodeTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python2/BasePython2Test.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java
runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
tool-testsuite/test/org/antlr/v4/test/tool/TestCompositeGrammars.java
tool-testsuite/test/org/antlr/v4/test/tool/TestPerformance.java

When writing tests for #276, I ran into an issue where Unicode values passed via `TestDescriptor`s randomly failed for some languages' runtimes, not not others.
When I investigated, I found many copy-pasted versions of the "write a Java `String` to disk" routine. Some of these explicitly converted to the String UTF-8, but many did not, which meant they didn't work if the system property `file.encoding` wasn't set to `utf-8` (and, let's be honest, nobody really sets this).
This PR addresses the issue by consolidating all runtime tests to use `BaseRuntimeTest.writeFile()`.

Fix writing Unicode values in runtime tests

---

runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Misc/Utils.cs

When adding Unicode support to the C# runtime as part of #276, I found the C# runtime method `Utils.ToCharArray()` was unused.
Rather than add support for Unicode, this PR simply deletes the unused method.

Remove unused C# runtime method Utils.ToCharArray

---

runtime/CSharp/runtime/CSharp/Antlr4.Runtime/AntlrInputStream.cs

As part of #276, the C# runtime needs to be able to treat input files as a series of Unicode code points.
Similar to #1626, this PR adds a new class `CodePointCharStream` to the C# runtime to allow parsing input as a series of Unicode code points.
I'm not a C# expert, so for now, this class only supports construction from a C# `string`. To optimize this, we'll probably want a way to deserialize UTF-8 bytes directly to a `CodePointCharStream`, but I'll leave that for another PR.

New C# runtime class CodePointCharStream

---

runtime/JavaScript/src/antlr4/error/Errors.js

missing js export

---

runtime-testsuite/test/org/antlr/v4/test/runtime/StreamVacuum.java
runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/browser/BaseBrowserTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/node/BaseNodeTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java

This is part of the work for https://github.com/antlr/antlr4/issues/276 .
When adding Unicode tests to the parameterized `TestDescriptors`, I found that a number of the runtimes failed to decode Unicode values passed over stdout.
The root cause was that `StreamVacuum` was not specifying UTF-8 when decoding output to Unicode—that meant it was using the default Java encoding, which can change from host to host, and is almost certainly not UTF-8.
That meant any tests which tried to read UTF-8 output from the runtime process would decode it using the wrong encoding, and the tests would fail.
I found many copies of `StreamVacuum` which all had the same issue, so this PR:
1. Consolidates all the copies `StreamVacuum` into one
2. Makes that copy specify UTF-8
3. Ensures Python and Java external …

Consolidate multiple copies of StreamVacuum, make use UTF-8

---

LICENSE.txt
runtime/JavaScript/src/antlr4/FileStream.js
runtime/JavaScript/src/antlr4/InputStream.js
runtime/JavaScript/src/antlr4/index.js
runtime/JavaScript/src/antlr4/polyfills/codepointat.js

As part of #276, we need JavaScript support for Unicode code points.
JavaScript exposes this via the ECMAScript 6 method [`String.codePointAt()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt), but it appears ANTLR 4 is intended to support ECMAScript 5.1 browsers:
https://github.com/antlr/antlr4/blob/fed8c97bda1a80ce62828c25083a45e8070d7108/doc/javascript-target.md#L5
So, this PR adds an MIT-licensed polyfill for `String.codePointAt()` from https://github.com/mathiasbynens/String.prototype.codePointAt which I will use in a subsequent PR to implement Unicode code point support in the JavaScript runtime.
I updated `FileStream` and `InputStream` to optionally support decoding UTF-16 code unit sequences to Unicode code points. The API …

JavaScript runtime: Optionally support decoding UTF-16 sequences to Unicode code points

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCharStreams.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCodePointCharStream.java
runtime/Java/src/org/antlr/v4/runtime/CharStreams.java
runtime/Java/src/org/antlr/v4/runtime/CodePointCharStream.java
tool/src/org/antlr/v4/gui/TestRig.java

As part of #276 , we need to make `BaseJavaTest` and the command-line `TestRig` work with Unicode values > U+FFFF.
To do this, I refactored the logic for creating `CodePointCharStreams` from Unicode data into a runtime utility class `CharStreams`. This class is a collection of static methods to connect `CodePointCharStream` with `UTF8CodePointDecoder`. It knows how to create `CodePointCharStreams` from:
1. `String`
2. `InputStream`
3. `ReadableByteChannel`
I updated `BaseJavaTest` and `TestRig` to use the new logic (the latter only when `-encoding UTF-8` is specified on the command line — we'll probably want to make this the default at some point).

Make BaseJavaTest and TestRig work with Unicode values > U+FFFF

---

runtime-testsuite/pom.xml
tool-testsuite/pom.xml

Previously, ANTLR's unit tests were run with the default encoding of the calling environment (which may or may not be UTF-8).
That affected all sorts of APIs, like `new String(byte[])`, making them behave unexpectedly if the encoding wasn't set to UTF-8 (e.g. on Windows).
This ensures we always run tests with `file.encoding` set to `UTF-8`.

Ensure unit tests are run with file.encoding=UTF-8

---

runtime-testsuite/test/org/antlr/v4/test/runtime/StreamVacuum.java
runtime-testsuite/test/org/antlr/v4/test/runtime/TestOutputReading.java

`StreamVacuum` has some particularly odd behavior. In particular, it always appends `\n` to the output of the test if the output was non-empty.
Many tests depend on this behavior, so this refactors the logic out into a helper class `TestOutputReading` so we can re-use it from tests which want to write output to a file instead of to `stdout`.

New class TestOutputReading to mimic StreamVacuum for tests which write to a file

---

LICENSE.txt
runtime/JavaScript/src/antlr4/InputStream.js
runtime/JavaScript/src/antlr4/index.js
runtime/JavaScript/src/antlr4/polyfills/fromcodepoint.js

This is a follow-up to https://github.com/antlr/antlr4/pull/1628 . 
When I added optional support to read in code points > U+FFFF to `InputStream`, I forgot to update `InputStream.getText()` to handle converting those code points back to UTF-16 for the Javascript `String`.
That meant the code which enabled the optional `decodeToUnicodeCodePoints` feature and then invoked `InputStream.getText()` would fail.
The root cause was that `this.strdata.slice(start, stop + 1)` was using the wrong units for the index; `this.strdata` uses UTF-16 for its indexes, but `start` and `stop` would be in Unicode code points.
This updates `InputStream.getText()` to work correctly if the `decodeToUnicodeCodePoints` flag is truthy. I imported the `String.fromCodePoint()` polyfill for backwards compatibility to …

Fix JavaScript InputStream.getText() when input contains Unicode values > U+FFFF

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python2.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
runtime/Python2/src/antlr4/Lexer.py
runtime/Python2/src/antlr4/Parser.py
runtime/Python3/src/antlr4/Lexer.py
runtime/Python3/src/antlr4/Parser.py
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Until Python 3.6 (https://www.python.org/dev/peps/pep-0528/), writing Unicode to `sys.stdout` on Windows just doesn't work correctly.
To work around this, this PR adds optional support to `Lexer` and `Parser` in the Python 2 and Python 3 runtimes to write output to a specified `file`-like object, instead of hard-coding `sys.stdout`.
We will still default to `sys.stdout` if nothing is specified.
I'll send a subsequent diff after this lands to use this in the Python2/3 runtime tests.

Python 2 and Python 3 support for lexer and parser output to a file

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/CSharp.test.stg
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Lexer.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Parser.cs
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

This is the same as https://github.com/antlr/antlr4/pull/1651 , but for C#.
It turns out C# on Windows writing to `Console.Out` has just as many problems with Unicode as Python < 3.6 does.
So, to work around these issues, this diff adds optional support to the C# `Lexer` and `Parser` for writing output to a file instead of hard-coding `Console.Out`.
A subsequent diff will use this work from the C# runtime tests.

C# support for lexer and parser output to a file

---

runtime/CSharp/runtime/CSharp/Antlr4.Runtime/AntlrInputStream.cs

When I got the tests running for C#, I found that my new class `CodePointCharStream` had a bug preventing it from working correctly with Unicode code points > U+FFFF:
```
TestSets>BaseRuntimeTest.testOne:119->BaseRuntimeTest.testParser:170 expected:<null> but was:<
Unhandled Exception:
System.ArgumentException: Found a low surrogate char without a preceding high surrogate at index: 2. The input may not be in this e
ncoding, or may not contain valid Unicode (UTF-16) characters.
Parameter name: s   
at System.Char.ConvertToUtf32 (System.String s, System.Int32 index) [0x00105] in <a8460a77e67a430a8486a9751162e5f4>:0
at Antlr4.Runtime.CodePointCharStream..ctor (System.String input) [0x00020] in <e8faca77c4004290bfda247d286930a6>:0
at Test.Main (System.String[] args) [0x0000e] in …
```

Easy: Fix C# CodePointCharStream to actually work with code points > U+FFFF

---

runtime/Java/src/org/antlr/v4/runtime/CharStreams.java

We have a few tests which create a `CodePointCharStream` from a string and expect to set the source name. This updates the `CharStreams` API to make this possible.

Easy: Allow setting source name when creating CodePointCharStream from string

---

tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeEscapes.java
tool/src/org/antlr/v4/codegen/Target.java
tool/src/org/antlr/v4/codegen/UnicodeEscapes.java
tool/src/org/antlr/v4/codegen/target/CSharpTarget.java
tool/src/org/antlr/v4/codegen/target/CppTarget.java
tool/src/org/antlr/v4/codegen/target/GoTarget.java
tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java
tool/src/org/antlr/v4/codegen/target/JavaTarget.java
tool/src/org/antlr/v4/codegen/target/Python2Target.java
tool/src/org/antlr/v4/codegen/target/Python3Target.java
tool/src/org/antlr/v4/codegen/target/SwiftTarget.java

This is part of the fix for #276.
Previously, if an input grammar definition included non-ASCII text or escaped Unicode literals, we would write out non-ASCII source files which then needed to be compiled.
While it's possible to configure many compilers to support UTF-8 source files, it's pretty challenging to do so across the board.
So, instead, this PR ensures all source which is code-generated by ANTLR4 to be 7-bit US-ASCII.
We do this by emitting language-specific Unicode literal escapes (`\uABCD` for Java and Javascript, `\uABCD` or `\U0001ABCD` for Python, and `\u{ABCD}` for Swift).
Note that this diff includes support for parsing the new extended `\u{ABCD}` ANTLR grammar escapes I plan to add to ANTLR in a subsequent diff. If you'd like, I can split that out and send it in …

Emit language-specific Unicode escapes in codegen

---

runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python2/BasePython2Test.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java

This builds on #1651 to write Python test output to a file instead of `sys.stdout`.
This works around bugs with Python < 3.6 when writing Unicode to `sys.stdout` on Windows.

Python 2/3 tests: Write test output to a file

---

runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/BaseErrorListener.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/ConsoleErrorListener.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/IAntlrErrorListener.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/IAntlrErrorStrategy.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Lexer.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Parser.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/ProxyErrorListener.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Tree/Xpath/XPathLexerErrorListener.cs
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

This builds on #1652 to write C# test output and test error output to files instead of `Console.Out` and `Console.Error`.
This works around bugs with C# on Windows failing to write Unicode to `Console.Out` and `Console.Error`.
I also updated the C# tests to use the new `CodePointCharStream` to support Unicode code points > `U+FFFF`.

C#: Write test output to a file

---

runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/LexerATNSimulator.cs
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Lexer.cs
runtime/Cpp/runtime/src/ParserInterpreter.cpp
runtime/Go/antlr/lexer.go
runtime/Go/antlr/lexer_atn_simulator.go
runtime/Java/src/org/antlr/v4/runtime/Lexer.java
runtime/Java/src/org/antlr/v4/runtime/atn/LexerATNSimulator.java
runtime/JavaScript/src/antlr4/Lexer.js
runtime/JavaScript/src/antlr4/atn/LexerATNSimulator.js
runtime/Python2/src/antlr4/Lexer.py
runtime/Python2/src/antlr4/ParserInterpreter.py
runtime/Python2/src/antlr4/atn/LexerATNSimulator.py
runtime/Python3/src/antlr4/Lexer.py
runtime/Python3/src/antlr4/ParserInterpreter.py
runtime/Python3/src/antlr4/atn/LexerATNSimulator.py
runtime/Swift/Sources/Antlr4/Lexer.swift
runtime/Swift/Sources/Antlr4/misc/extension/CharacterExtension.swift

Previously, `Lexer.MAX_CHAR_VALUE` was set to `0xFFFF` (or sometimes `0xFFFE`).
This meant some lexer transitions (like `NotSet`) would not support Unicode values > `U+FFFF`.
This changes `Lexer.MAX_CHAR_VALUE` to `0x10FFFF` (the largest possible Unicode code point). I replaced all the range-checks which hard-coded `0xFFFF` or `0xFFFE` with this new constant.

Change MAX_CHAR_VALUE to 0x10FFFF

---

runtime/Java/src/org/antlr/v4/runtime/ANTLRErrorStrategy.java
runtime/Java/src/org/antlr/v4/runtime/Parser.java
runtime/Java/src/org/antlr/v4/runtime/ParserInterpreter.java
runtime/Java/src/org/antlr/v4/runtime/ParserRuleContext.java

The new methods act like a built-in factory during parse tree construction. In the end it is a fairly minor change, but since I moved some methods around in Parser, it looks bigger than it is. All I did was to convert `new TerminalNodeImpl` and `new ErrorNodeImpl` code to calls to the factory methods. I also cleaned up ParserRuleContext add child stuff.
@antlr/antlr-targets should consider updating their targets as it adds flexibility that will be handy in a future PR where I support tree construction that contains hidden text before/after nodes.

 factor out the creation of error nodes and terminal nodes in the parser

---

runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Lexer.cs

When I added unit tests to cover error handling for Unicode values > `U+FFFF`, I found the C# runtime assumed that all code-points passed to `Lexer.GetErrorDisplay(int)` could be cast to a 16-bit `char`.
This was corrupting error messages for (valid) Unicode code points > U+FFFF.
To fix this, this PR changes the error message formatting logic to support Unicode code points > `U+FFFF`.

Support Unicode values > U+FFFF in C# runtime error messages

---

runtime/Java/src/org/antlr/v4/runtime/atn/RangeTransition.java
runtime/Java/src/org/antlr/v4/runtime/dfa/LexerDFASerializer.java
runtime/Java/src/org/antlr/v4/runtime/misc/IntervalSet.java
tool/src/org/antlr/v4/automata/ATNOptimizer.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java
tool/src/org/antlr/v4/misc/CharSupport.java
tool/src/org/antlr/v4/tool/DOTGenerator.java

There were a number of spots in the codebase which relied on `int` casts to `char`.
This replaces them with explicitly handling all `int`s as Unicode code points, rather than assuming they can be truncated to a 16-bit unsigned `char`.

Get rid of all (char) casts

---

runtime/Java/src/org/antlr/v4/runtime/Parser.java
runtime/Java/src/org/antlr/v4/runtime/ParserRuleContext.java
runtime/Java/src/org/antlr/v4/runtime/tree/TerminalNode.java
runtime/Java/src/org/antlr/v4/runtime/tree/TerminalNodeImpl.java

An addendum to https://github.com/antlr/antlr4/pull/1665
Technically, this is not backward compatible as it changes the interface but no one was able to create custom TerminalNodes anyway so I'm adding as it improves internal code quality. addChild now sets the parent rather than create. MUCH better.

augment TerminalNode with setParent()

---

runtime/Python2/src/antlr4/CodePoints.py
runtime/Python2/src/antlr4/InputStream.py

Until Python 3.3, Python could be compiled in one of two modes (`sys.maxunicode == 0x10FFFF` or `sys.maxunicode == 0xFFFF`).
In particular, Python 2.7 on macOS and on Windows uses `0xFFFF`, where Python 2.7 on Linux as well as Python >= 3.3 globally use `0x10FFFF`.
The two modes behave VERY differently when looking at Unicode strings with code points > `U+FFFF`.
Python 2.7 on Linux:
```
>>> import sys
>>> hex(sys.maxunicode)
'0x10ffff'
>>> len(u'\U0001F40D')
1
>>> [c for c in u'\U0001F40D']
[u'\U0001f40d']
```
Python 2.7 on Windows:
```
>>> import sys
>>> hex(sys.maxunicode)
'0xffff'
>>> len(u'\U0001F40D')
2
>>> [c for c in u'\U0001F40D']
[u'\ud83d', u'\udc0d']
```
To handle this inconsistency, this PR introduces a new module `antlr4.CodePoints`, which …

Python 2.7 InputStream: Properly support Unicode code points on Windows and macOS

---

runtime/Java/src/org/antlr/v4/runtime/atn/CodePointTransitions.java
tool/src/org/antlr/v4/automata/ATNOptimizer.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java

This is part of the work for #276. (Thanks to @sharwell for suggesting this optimization!)
When adding support for Unicode code points > U+FFFF, we can keep the size of the serialized ATN almost the same if we:
1. Ensure all transitions involving Unicode code points > U+FFFF are represented using `SetTransition` (i.e., not inlined as `AtomTransition` or `RangeTransition`, which only take 16-bit arguments)
2. Serialize the `SetTransition`s with Unicode code points > U+FFFF separately using 32-bit arguments
This PR implements part 1) via a new class `CodePointTransitions`, which handles creating transitions appropriately for Unicode code points both BMP (<= U+FFFF) and SMP (> U+FFFF).

New class CodePointTransitions to create SetTransitions for Unicode code points > U+FFFF

---

tool-testsuite/test/org/antlr/v4/test/tool/TestUnicode.java
tool/pom.xml
tool/src/org/antlr/v4/codegen/Unicode.java

In https://github.com/antlr/antlr4/pull/1633/#issuecomment-280778324 , @mike-lischke suggested adding support for Unicode property escapes like `\p{L}` in ANTLR grammars.
This PR adds a new utility class `Unicode` to the tool which uses the ICU library (which provides all the up-to-date Unicode data we need) to generate various `IntervalSet` maps to trivially provide these property escapes.
We can use these so users can generate Unicode lexer grammars using Unicode escapes to represent sets of code points with general categories, binary properties, and scripts:
```
UPPER_CASE = '\p{Lu}'
LATIN = '\p{Latin}'
CJK = ('\p{Han}' | '\p{Hiragana}' | '\p{Katakana}' | '\p{Hangul}')
EMOJI = '\p{Emoji}'
```

New tool utility class Unicode

---

runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/SetsDescriptors.java
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ATNDeserializer.cs
runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp
runtime/Cpp/runtime/src/atn/ATNDeserializer.h
runtime/Cpp/runtime/src/misc/Interval.cpp
runtime/Cpp/runtime/src/misc/Interval.h
runtime/Cpp/runtime/src/misc/IntervalSet.cpp
runtime/Cpp/runtime/src/misc/IntervalSet.h
runtime/Go/antlr/atn_deserializer.go
runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java
runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java
runtime/JavaScript/src/antlr4/atn/ATNDeserializer.js
runtime/Python2/src/antlr4/Lexer.py
runtime/Python2/src/antlr4/atn/ATNDeserializer.py
runtime/Python3/src/antlr4/atn/ATNDeserializer.py
runtime/Swift/Sources/Antlr4/atn/ATNDeserializer.swift
tool-testsuite/test/org/antlr/v4/test/tool/TestATNLexerInterpreter.java
tool-testsuite/test/org/antlr/v4/test/tool/TestATNSerialization.java
tool-testsuite/test/org/antlr/v4/test/tool/TestTokenTypeAssignment.java
tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeGrammar.java
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/src/org/antlr/v4/codegen/target/CSharpTarget.java
tool/src/org/antlr/v4/misc/CharSupport.java
tool/src/org/antlr/v4/parse/ANTLRLexer.g

Fixes #276 .
This used to be a WIP PR, but it's now ready for review.
This PR introduces a new extended Unicode escape `\u{10ABCD}` in ANTLR4 grammars to support Unicode literal values > `U+FFFF`.
The serialized ATN represents any atom or range with a Unicode value > U+FFFF as a set. Any such set is serialized in the ATN with 32-bit arguments.
I bumped the UUID, since this changes the serialized ATN format.
I included lots of tests and made sure everything is passing on Linux, Mac, and Windows.

New extended Unicode escape \u{10ABCD} to support Unicode literals > U+FFFF

---

runtime/Cpp/runtime/src/TokenStreamRewriter.cpp

Fix for https://github.com/antlr/antlr4/issues/1698
TokenStreamRewrite::replace expect a valid reference on std::string object. Not a null pointer.

Fix for #1698

---

tool-codegen/src/main/string-template/unicodedata.st
tool-codegen/src/org/antlr/v4/unicode/UnicodeDataTemplateController.java
tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeData.java

This is split off from the WIP PR #1688.
This extends the `UnicodeData` code-generated class to support Unicode blocks in addition to general categories, scripts, binary properties.
I added tests to cover the new functionality.
Since Unicode block names overlap with script names, I prefix the block name with `In`: `\p{InBlockName}`.
I also made it so `-` and `_` are treated the same.

UnicodeData: Also support Unicode blocks

---

tool-testsuite/test/org/antlr/v4/test/tool/TestEscapeSequenceParsing.java
tool/src/org/antlr/v4/misc/CharSupport.java
tool/src/org/antlr/v4/misc/EscapeSequenceParsing.java

This is split off from the WIP PR #1688.
The current logic to parse lexer charset escapes is a bit iffy. This introduces a new class `EscapeSequenceParsing` which we can use to add `\p{UnicodeProperty}` escape sequences, along with tests.

New class EscapeSequenceParsing with \p{UnicodeProperty} support

---

tool-testsuite/test/org/antlr/v4/test/tool/TestATNConstruction.java
tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java
tool/src/org/antlr/v4/tool/ErrorType.java

@mike-lischke asked for this in his review of https://github.com/antlr/antlr4/pull/1633 . I think it's a great way to show the power of the new full Unicode functionality in ANTLR4.
This PR adds two new lexer escapes suitable for use in a charset, so:
`[a-z]`
could become:
`[\p{Ll}]`
or, equivalently:
`[\p{Lowercase_Letter}]`
to match both a-z as well as exciting Unicode code points like 𝐚 (`U+1D41A`) through 𝐳 (`U+1D433`).
I included both matching and non-matching variants:
1. `\p{Letter}`: Include all Unicode code points with the general category "Letter"
2. `\P{Letter}`: Include all Unicode code points which do not have the general category "Letter"
This also works for:
1. Scripts (`\p{Latin}`, `\p{Hiragana}`, `\p{Cyrillic}`)
2. Binary properties (`\p{Emoji}`, …

New \p{Letter} Unicode property escape

---

doc/cpp-target.md
doc/lexer-rules.md
doc/lexicon.md

This updates the lexer, lexicon, and C++ documentation so 4.7 users know all about the new `\u{XXXXXX}` and `\p{Letter}` Unicode literal and property escapes.

Update docs for new Unicode literal and property escapes

---

doc/lexer-rules.md
tool-codegen/src/main/string-template/unicodedata.st
tool-codegen/src/org/antlr/v4/unicode/UnicodeDataTemplateController.java
tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeData.java
tool/src/org/antlr/v4/misc/EscapeSequenceParsing.java

When I went to implement [Unicode TR29 grapheme cluster parsing](http://www.unicode.org/reports/tr29/), I found I forgot to include enumerated Unicode properties in the code-generated `UnicodeData.java`.
Since enumerated properties have multiple values (as opposed to the binary properties we supported previously), I used the semi-standard syntax:
`\p{PropertyName=PropertyValue}`
All the existing tests pass and I added a few more for the new syntax.

Also support Unicode enumerated properties via \p{Foo=Bar} syntax

---

contributors.txt
runtime/JavaScript/src/antlr4/ParserRuleContext.js

For JavaScript target, `getToken` and `getChild` methods in `ParserRuleContext.js` did not check if `this.children` is `null` as code for Java target did. I added the two if statements Java implementation has in these methods.
For an example of where the problem arises, consider the rule
```
program : /* nothing */ | statements ;
```
If the input is empty (i.e. `statements` is not matched), the visitor's method
```
ProgramBaseVisitor.prototype.visitProgram = function(ctx) {
return { statements: ctx.statements() ? this.visit(ctx.statements()) : [] }
}
```
fails on the `ctx.statements()` call, because of an attempt to access `this.children.length` in `ParserRuleContext.js`'s `getChild` method.
Meanwhile, the Java implementation of the same thing has no problem calling `ctx.statements()`.

Fixed null pointer exception for JS target

---

doc/lexer-rules.md
tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeData.java
tool/src/org/antlr/v4/unicode/UnicodeDataTemplateController.java

To finish the Unicode grapheme cluster parser, we need a few more `\p` properties:
`\p{EmojiPresentation=EmojiDefault}`
`\p{EmojiPresentation=TextDefault}`
`\p{EmojiPresentation=Text}`
This data comes from ICU, but it uses an extended set syntax which ANTLR's `\p` escape doesn't currently support, so I'm including it as a specific escape.
I updated the docs and tests.

A few last escapes: \p{EmojiPresentation=EmojiDefault} and \p{EmojiPresentation=TextDefault}

---

doc/faq/general.md
doc/interpreters.md
doc/unicode.md
runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCharStreams.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCodePointCharStream.java
runtime/Java/src/org/antlr/v4/runtime/CharStreams.java
tool-testsuite/test/org/antlr/v4/test/tool/TestATNLexerInterpreter.java
tool-testsuite/test/org/antlr/v4/test/tool/TestUnicodeGrammar.java
tool/src/org/antlr/v4/gui/TestRig.java

This adds a centralized factory method `CharStreams.create()`, uses it in `TestRig`, and adds a new `doc/unicode.md` to explain all things Unicode.

Tidy up CharStreams and add new doc/unicode.md

---

doc/unicode.md

It should be made clear that the recommended use of CharStreams.fromPath() is a Java-only solution. The other targets just have their ANTLRInputStream class extended to support full Unicode.

A few updates to the Unicode documentation.

---

runtime/Java/src/org/antlr/v4/runtime/misc/IntervalSet.java

Using YourKit, I found the perf bottleneck in both `lex_legacy_grapheme_utf8` and `lex_new_grapheme_utf8` is the invocation of `IntervalSet.contains()` by `SetTransition`. (The new Unicode property sets `\p{Foo}` are quite large and contains lots of `Interval`s).
I can speed up the runtime of the grapheme lexer by almost 2x by using binary search instead of a linear scan in `IntervalSet.contains()` (this is trivial, since the set of intervals to search is already sorted and disjoint).
I'm not quite sure why this was a win for most things but negative for `udhr_hin.txt`. Still, a big enough win overall that it should be well worth it.
Before:
```
lex_legacy_java_utf8 average time  1044us over 2000 runs of 29038 symbols
lex_legacy_java_utf8 average time  1928us over 2000 runs of 29038 …
```

IntervalSet perf: Use binary search for IntervalSet.contains(el)

---

runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestCharStreams.java
runtime/Java/src/org/antlr/v4/runtime/CharStreams.java

Following up to https://github.com/antlr/antlr4/pull/1781#issuecomment-290154707 , this removes the outdated comments that suggest UTF-8 is necessary to support code points > `U+FFFF`, and adds tests to confirm `CharStreams` supports those code points with UTF-16 and UTF-32.

Tidy comments and add tests to ensure UTF-16 and UTF-32 support Unicode code points > U+FFFF

---

runtime/Java/src/org/antlr/v4/runtime/UnbufferedCharStream.java
tool-testsuite/test/org/antlr/v4/test/tool/TestUnbufferedCharStream.java

Fixes #1795 .
This changes the Java implementation of `UnbufferedCharStream` to use code points, not UTF-16 code units, following the changes to `CharStreams`.
For now, I didn't bother putting this in the `CharStreams` interface, but if we end up changing that to use a `Builder` style, we could make an `unbuffered()` option.
I updated the tests. Note the weirdness around `\uFFFF` — before, we were relying on `(char)IntStream.EOF` converting `-1` to `\uFFFF`, but now we no longer have that, so the test code explicitly appends `\uFFFF`.

Change UnbufferedCharStream to use code points

---

runtime/Java/src/org/antlr/v4/runtime/UnbufferedCharStream.java

Noticed this when I ported #1796 to C# in #1798.

Small tidy-up for Java UnbufferedCharStream

---

runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Antlr4.Runtime.mono.csproj
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Antlr4.Runtime.vs2013.csproj
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/CharStreams.cs

Based on the discussion at https://github.com/antlr/antlr4/pull/1771#issuecomment-287627618 , this brings the Java runtime's `CharStreams` factory API to C#.
I updated `BaseCSharpTest` to make use of the new API to illustrate how it works.

New C# CharStreams static factory class

---

runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/browser/BaseBrowserTest.java
runtime/JavaScript/src/antlr4/CharStreams.js
runtime/JavaScript/src/antlr4/index.js

Based on the discussion at https://github.com/antlr/antlr4/pull/1771#issuecomment-287627618 ,  this brings the Java runtime's `CharStreams` factory API to JavaScript.
I updated `BaseBrowserTest` to illustrate usage of the new API.

New JavaScript CharStreams functions

---

runtime/Java/src/org/antlr/v4/runtime/UnbufferedCharStream.java

As requested here: https://github.com/antlr/antlr4/pull/1796#discussion_r108793476

Use UTF-8 by default in UnbufferedCharStream and allow specifying charset

---

tool/src/org/antlr/v4/codegen/target/Python3Target.java

Noticed this poking around in the Python 3 codegen. `2 ^ 31` is not 2<sup>31</sup>, it's 2 XOR 31, which is 29..

Python 3 codegen probably didn't mean to limit ATN segment size to 2 XOR 31

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Swift.test.stg
runtime/Swift/Sources/Antlr4/CommonToken.swift
runtime/Swift/Sources/Antlr4/Lexer.swift
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/ParserRuleContext.swift
runtime/Swift/Sources/Antlr4/atn/ArrayPredictionContext.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift
runtime/Swift/Sources/Antlr4/misc/BitSet.swift
runtime/Swift/Sources/Antlr4/misc/utils/CommonUtil.swift
runtime/Swift/Tests/Antlr4Tests/VisitorTests.swift

Swift 3.1 was [released](https://swift.org/blog/swift-3-1-released) on Mar. 27th.
The language change should be source compatible, but our implementation is using some language feature that's not guaranteed by the public API thus breaking the ANTLR4 Swift runtime build. This PR will fix those issues along with several warnings because of the language release.
The PR  #1793 removing StringExtension public modifier is breaking one unit test that uses the "length" method in the old string extension. The second commit will fix this issue by unwrapping the "length" method in the SwiftTest.stg file. We don't want to expose (those pretty generic) extensions inside Swift runtime but need to make sure our generated parsers (in a different module) still works.

Fixing Problems after Swift3.1 Release

---

contributors.txt
doc/lexicon.md

’\’' should be ’\’
Signed-off-by: Yishuang Lu <luystu@gmail.com>

Correct typo in lexicon.md

---

runtime/Go/antlr/file_stream.go

The previous implementation was swallowing any errors so it could be confusing.  For instance a missing file is treated as an empty string which successfully parses (when one would expect an error).
This will be an incompatible change and is probably best lumped in with the other incompatible changes coming up.

Add proper error handling semantics to FileStream.

---

contributors.txt
runtime/JavaScript/src/antlr4/CharStreams.js

Currently the JS runtime `CharStreams.fromString` sometimes returns (and mangles) the global `window` object instead of returning a proper InputStream. This is prevented by using the `new` keyword in this and similar helper methods.
@bhamiltoncx, please take a look. Perhaps I'm doing something wrong... if so, I'm happy to be mistaken!

Add `new` keyword to return proper InputStreams

---

.travis/before-install-linux-dotnet.sh
.travis/before-install-osx-dotnet.sh
.travis/run-tests-dotnet.sh
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Antlr4.Runtime.dotnet.csproj

@parrt @ericvergnaud https://travis-ci.org/xied75/antlr4/builds/226855441
Renamed dll to Antlr4.Runtime.Core as Eric suggested.
dotnet test on Mac now able to finish successfully.
dotnet test on Linux runs faster.
The cmd to pack nuget package is ```dotnet pack Antlr4.Runtime.dotnet.csproj``` then we'll get a nupkg inside bin/
In fact we can push the nupkg automatically (nightly build would be great) if we want. Let me know.

[dotnet] speed up tests; rename runtime dll ready for nuget

---

contributors.txt
doc/releasing-antlr.md
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Antlr4.Runtime.dotnet.csproj
runtime/CSharp/runtime/CSharp/Package.nuspec
runtime/CSharp/runtime/CSharp/build-nuget-package.sh

This PR updates the nuspec file so the NuGet package includes the .NET Core DLL. The NuGet package has the following structure to support both .NET 3.5 and up, as well as .NET Core:
```
lib
├── net35
│   └── Antlr4.Runtime.Standard.dll
└── netstandard
└── Antlr4.Runtime.Core.dll
```
I've verified that when the NuGet package is installed in .NET Framework projects ("normal" .NET), it references Antlr4.Runtime.Standard.dll, and in .NET Core projects it references Antlr4.Runtime.Core.dll.
For the build process, ideally to do a cross-platform build we could use a multi-targeting build with `dotnet`, the new command-line tool from Microsoft. However, due to https://github.com/Microsoft/msbuild/issues/1333 (a bug with msbuild core) we need to continue using mono to build .NET3.5, and `dotnet` …

[dotnet] NuGet packaging for .NET Core

---

runtime/Cpp/runtime/src/CommonTokenStream.cpp
runtime/Cpp/runtime/src/CommonTokenStream.h

Channel parameter in c-tor is now a size_t - fixes #1827.

---

contributors.txt
runtime/Cpp/runtime/src/tree/ParseTreeWalker.cpp
runtime/Cpp/runtime/src/tree/ParseTreeWalker.h

as intended.
The existing code intended for ParseTreeWalker::DEFAULT to provide a
IterativeParseTreeWalker. However, the implementation initialized
ParseTreeWalker::DEFAULT by doing a (value) copy of an
IterativeParseTreeWalker, which sliced the object and therefore,
unfortunately, transformed it back into a regular ParseTreeWalker.
This change implements the desired behavior. Furthermore by making DEFAULT
a reference, we are able to preserve the interface to existing code.

Make ParseTreeWalker::DEFAULT provide an IterativeParseTreeWalker

---

doc/cpp-target.md

The listener example still refers to ```Ref<>``` and shared pointers, but in
reality the generated method does not pass a shared pointer. The actual
signature looks more like this:
```
virtual void enterKey(ParserRuleContext * /*ctx*/) override { }
```
This change updates the example to match that signature, and removes a line
discussing ```Ref<>```. It also adds the ```override``` keyword in order to make the
user's code a little more robust against typos/changes in the grammar.

Fix listener example in C++ documentation.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

That removal breaks the tests, so the namespace is obviously needed there (although I don't see any bad effect on my own code which uses this part).

Reverted removal of namespace.

---

contributors.txt
runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java
runtime/Python2/src/antlr4/IntervalSet.py
runtime/Python3/src/antlr4/IntervalSet.py

I'm getting different error messages from Java and Python runtimes for the same grammar. Figured out a check from the Java version was missing in the Python one so here's it

Fix input mismatch errors not reported the same way as Java in Python

---

contributors.txt
doc/csharp-target.md

The file endings for `MyGrammarBaseListener`, `MyGrammarVisitor` and `MyGrammarBaseVisitor` was `.js`. Changed to `.cs`

Corrected `.js` file endings to `.cs` in doc/chsharp-target.md

---

contributors.txt
runtime/Go/antlr/common_token_stream.go
runtime/Go/antlr/input_stream.go
runtime/Go/antlr/interval_set.go

When I am creating custom `TokenStream`, `GetTextFromInterval` method needs start and stop of `Interval`. However, `Interval` does not export these values.
This PR addes getter and `Contains`  to `Interval` in order to implement custom TokenStream.

[Go] Add getter method to Interval.

---

runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java
runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/SemPredEvalParserDescriptors.java
runtime/Java/src/org/antlr/v4/runtime/DefaultErrorStrategy.java
runtime/Java/src/org/antlr/v4/runtime/InputMismatchException.java

Fixes #1922 
:memo: This needs more test cases, particularly for LL(k) failures where k>1. However, my current understanding is these cases have been impacted by this bug for much longer (since 4.2.2) than the issue being addressed for the k=1 case.

Report InputMismatchException with original context information

---

contributors.txt
runtime/Go/antlr/tokenstream_rewriter.go
runtime/Go/antlr/tokenstream_rewriter_test.go

TokenStreamRewriter implementation was missing
Ported code from Java version; however, there are couple of deviations due to difference between composition (Go) and inheritance (Java) concepts
Ported tests from Swift for LexerA

[Go] Implemented TokenStreamRewriter

---

runtime/Python2/src/antlr4/Parser.py
runtime/Python3/src/antlr4/Parser.py

ANTLR parsers in Java are allowed to access the number of encountered
syntax errors via the getNumberOfSyntaxErrors method. However, the
Python variants must use the protected _syntaxErrors member to get this
value. The patch defines the same getter for Python targets too.

Python: add public getter to parsers to access syntax error count.

---

doc/getting-started.md

version of the antlr jar package is different from other place of this doc，and it make mistake.

correct the version of the antlr jar package

---

.editorconfig

As an example, compare [before](https://github.com/antlr/antlr4/blob/1203794259adf03e140dfd4698de8e9e91f5c985/runtime/Java/src/org/antlr/v4/runtime/ANTLRFileStream.java) and [after](https://github.com/sharwell/antlr4/blob/set-tab-width/runtime/Java/src/org/antlr/v4/runtime/ANTLRFileStream.java).

Set the tab width in .editorconfig so GitHub shows source properly

---

runtime/Cpp/runtime/src/atn/PredictionMode.h

When compiling under gcc, ANTLR4CPP_PUBLIC macro expands to the following gcc visibility attribute:
```
__attribute__((visibility ("default")))
```
(when compiling under Windows it expands to the corresponding ```__declspec``` attribute)
This change was introduced in commit 8ff852640a7ec62d46330f71e274c591ada1fc70
Although the attribute makes perfect sense when applied to a ```class``` declaration, it makes no sense (has no effect) when applied to an ```enum class``` declaration. I assume that doing so was unintentional; that when the change was introduced it was it was added mechanically to all ```class XXX``` instances in the source code, a process which accidentally picked up one ```enum class XXX``` instance.
Although it has no effect on the object code, it leads to the following …

Remove the useless visibility attribute from this "enum class" declaration

---

.travis.yml

Oracle JDK 7 support has been withdrawn.
https://github.com/travis-ci/travis-ci/issues/7964
http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

Replace oraclejdk7 with openjdk7 in .travis.yml.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

This is to avoid two _lt variables in the same scope. This happens with the [mysql grammar](https://github.com/antlr/grammars-v4/tree/master/mysql): `build: previous declaration at mysql/mysql_parser.go:12215:6`

[Go] Placed the CommonSetStuff code inside a scope

---

runtime/Swift/Sources/Antlr4/CharStream.swift
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/Recognizer.swift
runtime/Swift/Sources/Antlr4/TokenStream.swift
runtime/Swift/Sources/Antlr4/misc/BitSet.swift
runtime/Swift/Sources/Antlr4/misc/exception/ANTLRError.swift

This was copied from the API of the equivalent code in Java when
the runtime was ported to Swift.  It is meaningless in Swift, and
was unused.

Remove ANTLRError.nullPointer from the Swift runtime.

---

.travis.yml

Split Travis tests into three phases.  This gives a "smoke-test" phase which just runs the Java tests, to get a quick check that compilation is working.  It is followed by the "main-test" phase that tests each target on their preferred platform (e.g. Swift on macOS, Python on Linux) followed by "test-extended" which runs all the remaining tests (all the other Java variants, and any other platforms supported by each target).
This means that those tests in the later phases won't run unless the earlier phases have passed.  This should vastly improve our Travis turnaround.
This PR also changes the matrix so that we get some coverage across all of openjdk7,8 and oraclejdk7,8 and moves the Go and Javascript tests to Trusty just so that they are more up-to-date.  This adds one additional Java …

Split Travis tests into three phases, and add caching and timeout management

---

runtime/Go/antlr/common_token_stream_test.go
runtime/Go/antlr/testing_assert_test.go
runtime/Go/antlr/testing_lexer_b_test.go
runtime/Go/antlr/testing_util_test.go

This PR add tests for `CommonTokenStream`. These tests is ported from [Java test](https://github.com/antlr/antlr4/blob/master/tool-testsuite/test/org/antlr/v4/test/tool/TestCommonTokenStream.java).
To testing purpose, these two files are also added. I think these files can be used for future tests.
- testing_lexer_b_test.go
- testing_util_test.go
- testing_assert_test.go  <-- assert library which is almost same as Java assertions.
(updated: as thankful comment, I removed dependency to assert library)

[Go] Add CommonTokenStream test.

---

runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java

Setting `ATNConfig` properties can change the hash code of the instance, leading to cases where the `closureBusy` set places objects in the wrong buckets. While this has not led to known cases of stack overflow, it has led to cases where one or more buckets contains a large number of duplicate objects, and the set's add operation goes from O(1) to O(n).
:link: This bug was found during investigation of a report by @gkudva in https://github.com/antlr/antlr4/issues/42#issuecomment-312299708.

Avoid adding to closureBusy before all ATNConfig properties are set

---

contributors.txt
tool/src/org/antlr/v4/gui/TreeViewer.java

Main driver for exporting to SVG was the ability to search in big parse trees. I wont add new dependencies to the pom.xml, but if its ok, I'll prepare the next commit for the SVG view, too.

added SVG export of parse tree

---

runtime/Swift/Sources/Antlr4/atn/ATNConfig.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfigSet.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNConfig.swift
runtime/Swift/Sources/Antlr4/atn/LexerActionExecutor.swift
runtime/Swift/Sources/Antlr4/atn/LexerChannelAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerCustomAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerIndexedCustomAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerModeAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerMoreAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerPopModeAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerPushModeAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerSkipAction.swift
runtime/Swift/Sources/Antlr4/atn/LexerTypeAction.swift
runtime/Swift/Sources/Antlr4/atn/PredictionContext.swift
runtime/Swift/Sources/Antlr4/atn/SemanticContext.swift
runtime/Swift/Sources/Antlr4/dfa/DFAState.swift
runtime/Swift/Sources/Antlr4/misc/IntervalSet.swift
runtime/Swift/Sources/Antlr4/misc/MurmurHash.swift
runtime/Swift/Sources/Antlr4/misc/Triple.swift
runtime/Swift/Tests/Antlr4Tests/MurmurHashTests.swift

Improve MurmurHash in a number of ways:
Use Swift's overflowing operators rather than multipliedReportingOverflow etc.
Use UInt32 for the hash values.  This matches how MurmurHash3 is generally defined (e.g. on Wikipedia).
Add support for decoding Strings (UTF-8, then little-endian) and hashing the resultant UInt32 values.
Add a test set, using test patterns from Ian Boyd (public domain).
This is dependent on PR #2032 (I found these problems when working on the Swift 4 migration).

Improve MurmurHash

---

appveyor.yml

For some reason, possibly the new images that AppVeyor rolled out on Oct 22,
our AppVeyor tests now fail immediately, with msbuild complaining that there
are multiple solutions in the repository.
Address this by not using the default AppVeyor build section, but calling
msbuild ourselves explicitly in the build_script section.  This way, we can
specify which .slns we want to build.  I have specified the runtime and
runtime-testsuite Antlr4.vs2013.slns; the other ones didn't work for me in
this configuration.
Also, these builds were previously running with low / zero logging.  As
far as I can tell, this gave AppVeyor no way to know whether the build has
succeeded or not.  It certainly gives no way to diagnose any failures that do
occur.  I have dialed the logging up on everything.
Also, …

Fix the AppVeyor tests.

---

.travis.yml

Caching ~/.m2 is useful; caching org/antlr inside there is not.  It causes
unnecessary re-submission of the cache every build.

Remove ~/.m2/repository/org/antlr from the Travis cache.

---

tool/src/org/antlr/v4/Tool.java

If the specified output path was a file and not a directory, the error
handling intended to invalidate outputDirectory, but due to an apparent
copy-paste error, it invalidated libDirectory instead.

Very minor fix in error handling path for the -o command line option.

---

tool/src/org/antlr/v4/Tool.java

ErrorManager.setFormat was being called before the command line options
were parsed in handleArgs.  This meant that setFormat was always called
with the default, and so the command line option never took effect.
This option apparently only worked for 2.5 hours on Sep 6 2012 ;-)
Closes #992.

Fix the -message-format command line option.

---

.travis.yml
.travis/before-install-osx-dotnet.sh

This avoids hitting the Microsoft server every time.  The download isn't
super-reliable, so this should help with build reliability.
This extends the cache timeout, because the package is large and the
upload was timing out.

Add Travis-side caching of the dotnet package that we download from Microsoft

---

runtime/Swift/Sources/Antlr4/UnbufferedCharStream.swift

The call to stream.read needs to use buffer.count, not buffer.capacity,
as the maxLength.  Otherwise, some bytes get dropped on the floor and the
stream is corrupted.
Remove the code to pad self.data back to up to its previous capacity when
copying data at the end of release.  This came over from the Java port, but
I don't think it makes sense in Swift, given the copy-on-write Array
value semantics.  Instead, just copy the tail of the buffer if there is
anything left to read (i.e. self.data gets smaller) and when there is nothing
in the buffer to read, reset to the specified bufferSize (i.e. self.data
goes back to the specified self.bufferSize.
Remove debug print statement that was accidentally left in.

Fix UnbufferedCharStream in the Swift runtime.

---

runtime/Swift/Sources/Antlr4/Lexer.swift
runtime/Swift/Sources/Antlr4/LexerInterpreter.swift
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

This makes it possible for client code to use CharStream as a generic type
constraint and construct Lexer subclasses generically.

Make CharStream.init(CharStream) required (in the Swift runtime).

---

pom.xml

Add an entry to pom.xml so that the runtime/Swift subdirectories that contain
build output are removed when "mvn clean" is used.

Include the Swift runtime in "mvn clean".

---

contributors.txt
tool/src/org/antlr/v4/codegen/target/GoTarget.java

This fixes https://github.com/antlr/antlr4/issues/2080 by adding all method names from the `RuleContext` interface definition to the reserved words list.  Arguably this is a quick fix and not a full solution, but should help avoid some headaches in the mean time.
```go
type Tree interface {
GetParent() Tree
SetParent(Tree)
GetPayload() interface{}
GetChild(i int) Tree
GetChildCount() int
GetChildren() []Tree
}
type SyntaxTree interface {
Tree
GetSourceInterval() *Interval
}
type ParseTree interface {
SyntaxTree
Accept(Visitor ParseTreeVisitor) interface{}
GetText() string
ToStringTree([]string, Recognizer) string
}
type RuleNode interface {
ParseTree
GetRuleContext() RuleContext
GetBaseRuleContext() *BaseRuleContext
}
type RuleContext interface {
RuleNode
GetInvokingState() int …
```

Add RuleContext interface methods to reserved words

---

.travis/run-tests-swift.sh

These are the unit tests that are written in Swift, not the more
in-depth runtime-testsuite tests (we were always running those).
I don't know why JAVA_HOME isn't set during run-tests-swift.sh, but it
isn't.  Set it, since runtime/Swift/boot.py expects it as part of the
parser generation.

Run the Swift runtime unit tests during the Travis run.

---

contributors.txt
runtime/JavaScript/src/antlr4/error/ErrorStrategy.js

I was using the Antlr4 JavaScript version in my project, but get an error related to ErrorStrategy.js.
ErrorStrategy::reportNoViableAlternative method try to new a Interval object, but pass two Token as constructor argument, but Interval class assume the arguments to be numbers. So I fixed by this PR.

[JavaScript] Fix Interval usage in ErrorStrategy.js

---

.travis/before-install-osx-dotnet.sh
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java

Issue #2078 is a crash (SIGILL) inside the .NET runtime when running on macOS on Travis.  This is intermittent, so a retry may help.  Retry this specific exit status inside runProcess.
Log the command / stdout / stderr / exit status at three places during the C# runtime tests.  At these places we are executing subprocesses, but if those fail we weren't logging the info that we needed to diagnose the problem.
Print the stack trace if compilation fails.
Assert that test compilation succeeded.
Switch to .NET Core SDK 1.1.4 for the Travis macOS tests.  This is the LTS release at the moment.  This didn't fix #2078, sadly.  I've already seen one SIGILL on 1.1.4.  We should upgrade anyway.

[CSharp] Add extra diagnostics and a retry to the C# runtime tests and upgrade the macOS runtime

---

runtime/Swift/Sources/Antlr4/tree/pattern/Chunk.swift
runtime/Swift/Sources/Antlr4/tree/pattern/ParseTreePatternMatcher.swift
runtime/Swift/Sources/Antlr4/tree/pattern/TagChunk.swift
runtime/Swift/Sources/Antlr4/tree/pattern/TextChunk.swift
runtime/Swift/Tests/Antlr4Tests/ParseTreePatternMatcherTests.swift

Fix the parsing inside ParseTreePatternMatcher.split.  It was trivially
broken in a number of ways, with bugs that aren't in the Java version
that it was ported from, so it's obviously never been run before.
This adds unit tests for ParseTreePatternMatcher.split, and makes Chunk
implement Equatable, so that it we can compare Chunk instances in the
tests.
Tidy up the description implementations at the same time.

Fix ParseTreePatternMatcher.split in the Swift runtime.

---

runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
runtime/Swift/Sources/Antlr4/ANTLRFileStream.swift
runtime/Swift/Sources/Antlr4/misc/Utils.swift

Change the initializer to ANTLRFileStream so that it throws any errors that
occur while reading the file.  Previously, it was just dropping any errors on
the floor (inside Utils.readFile).
Remove Utils.readFile, it's not used anywhere else.

Report errors in ANTLRFileStream.

---

runtime/Swift/Sources/Antlr4/BailErrorStrategy.swift
runtime/Swift/Sources/Antlr4/DefaultErrorStrategy.swift

Mark every method in BailErrorStrategy and DefaultErrorStrategy as "open",
so that they can be extended by subclasses in user code.

Open the error strategies to subclasses.

---

runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/dfa/DFA.swift

Make all the mutexes in the Swift runtime use "let" rather than "var".
They are never changed, and they wouldn't make good mutexes if they were.

[Swift] Make all the mutexes "let" rather than "var".

---

runtime/Swift/Sources/Antlr4/atn/ATN.swift
runtime/Swift/Sources/Antlr4/misc/IntervalSet.swift

Replace IntervalSet.setReadonly(Bool) with makeReadonly().  This
operation only ever works in one direction, and would throw an exception
if a caller attempted to make a read-only IntervalSet read-write again.
By changing the interface we remove the need to check this, and so we
don't need to declare the exception.  Unlike in the Java runtime, we
need to declare the possibility of the exception at the callsite, so this
was pointlessly cluttering.

[Swift] Replace IntervalSet.setReadonly with makeReadonly.

---

runtime/Swift/Sources/Antlr4/dfa/DFA.swift

Make DFA.precedenceDfa be a "let" rather than a "var", and remove
setPrecedenceDfa.  This field never varies after construction.  The
code in setPrecedenceDfa was carried over from the Java runtime, but
it only threw an exception, and was deprecated.  There's no need for
that in the Swift runtime.

[Swift] Make DFA.precedenceDfa be a "let" rather than a "var".

---

runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
runtime/Swift/Sources/Antlr4/ANTLRFileStream.swift
runtime/Swift/Sources/Antlr4/atn/ATN.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfigSet.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/dfa/DFA.swift
runtime/Swift/Sources/Antlr4/misc/Utils.swift

Minor tidyups in the Swift runtime.  No semantic change.
Depends on PR #2102 due to merge conflicts.

[Swift] Some minor tidyups.

---

runtime/Swift/Sources/Antlr4/atn/ATN.swift

Remove unused ATN.modeNameToStartState.  In the Java runtime this is
only used by LexerATNFactory (i.e. during lexer generation) and we don't
have the equivalent in the Swift runtime at all.

[Swift] Remove unused ATN.modeNameToStartState.

---

runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/atn/ATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift

Make ATNSimulator.sharedContextCache declared as non-optional.  It
was used this way anyway, so it was just being pointlessly forced
at the use-sites.

[Swift] Make ATNSimulator.sharedContextCache non-optional.

---

runtime/Swift/Sources/Antlr4/LexerInterpreter.swift
runtime/Swift/Sources/Antlr4/ParserInterpreter.swift

Fix initialization of {Lexer,Parser}Interpreter.decisionToDFA.  These
were always being created as empty arrays, which would never work.
I don't know if anyone's using this code; presumably not.

[Swift] Fix initialization of {Lexer,Parser}Interpreter.decisionToDFA.

---

runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
runtime/Swift/Sources/Antlr4/BailErrorStrategy.swift
runtime/Swift/Sources/Antlr4/misc/exception/ANTLRError.swift
runtime/Swift/Sources/Antlr4/misc/exception/ANTLRException.swift

BailErrorStrategy is supposed to throw an error that's different from
the ordinary recognition error, specifically so that it can be handled
differently by client code.  This was not ported over from Java correctly.
Fix this by moving parseCancellation from ANTLRError to ANTLRException,
adding its RecognitionException argument, and throwing it from the
two handlers in BailErrorStrategy.
Also remove ANTLRException.cannotInvokeStartRule, which is unused.
(The Java runtime uses it when ParseTreePatternMatcher throws a generic
exception, but we don't have that.)

[Swift] Fix parse-cancellation in BailErrorStrategy.

---

doc/swift-target.md
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
tool/src/org/antlr/v4/codegen/model/ListenerFile.java
tool/src/org/antlr/v4/codegen/model/Recognizer.java
tool/src/org/antlr/v4/codegen/model/VisitorFile.java
tool/src/org/antlr/v4/tool/Grammar.java

Add an accessLevel parser option.  Use this to specify the access level
(public, etc) used on the classes and protocols in the generated
parser / lexer / listeners.  This required adding the option to
tool.Grammar.parserOptions so that it was known as a valid option, and
to codegen.model.{Recognizer,ListenerFile,VisitorFile} so that it was
available to the template in all the necessary contexts.
The Swift template has been extended to recognize this option, and generate
classes and members using "open", "public" or "internal" as appropriate.
This is only fully implemented for Swift.  The option is generic, but
the language-specific templates will need to be updated for any language
that would like similar support.
Closes #1597.

Add an accessLevel parser option.

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg

In order to allow JavaScript clients to auto-suggest completions, they need access to the lexer's ATN, not just the parser's.
See usage in:
https://github.com/oranoran/antlr4-autosuggest-js

[JavaScript] enable auto-suggest engines by exposing the lexer ATN as a property, similar to the parser ATN

---

runtime/Go/antlr/trees.go

Hides a function that is essentially internal and is unused outside of this module.

Fix issue with tree finding when the underlying slice needs to be resized.

---

contributors.txt
runtime/Python2/src/antlr4/tree/Tree.py
runtime/Python3/src/antlr4/tree/Tree.py

Previously ParseTreeVisitor in the visitChildren method returned None when it shouldn't visit the next child, so if you overrode the shouldVisitNextChild you would also have to override the visitChildren method only to change that return statement.

[Python3] return result instead of None in visitor

---

contributors.txt
runtime/JavaScript/src/antlr4/InputStream.js

Remove unused  `_loadString` parameter

---

contributors.txt
runtime/Java/pom.xml

This adds an Automatic-Module-Name entry to the runtime jar in order to
provide a stable name upon which other modules can depend. The module
name chosen was "org.antlr.antlr4.runtime". This closely matches the
Maven artifact name with the obvious change that the module name
doesn't contain a hyphen (hyphens can't be used in module names at
the language level in Java).
I have signed the contributor agreement in a separate commit below.
Fix #2163

Add an Automatic-Module-Name

---

tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

We hit a Java limit on the amount of code that's allowed to execute in the static initializer for a class.
```
[ERROR] /home/travis/build/batfish/batfish/projects/batfish/target/generated-sources/antlr4/org/batfish/grammar/cisco/CiscoLexer.java:[14,1] error: code too large
[INFO] 1 error
```
See [this PR](https://github.com/batfish/batfish/pull/1533) for more information.
A really simple fix is in the attached template: instead of defining the large public `String[]` constants directly, move them into `private static` factory functions.

Java.stg: use static functions instead of inline arrays

---

contributors.txt
tool/pom.xml

There are 4 CVEs against the current version of icu4j used by ANTLR. This PR updates to the latest version, which resolves all of the CVEs.
These were identified with the [OWASP Dependency Check](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html).
To the extent my environment is configured, all tests pass. For configurations I don't have (e.g., Python 3.5), the tests fail identically between versions.
Details:
=====
Published Vulnerabilities
CVE-2017-14952  suppress
Severity:High
CVSS Score: 7.5 (AV:N/AC:L/Au:N/C:P/I:P/A:P)
CWE: CWE-415 Double Free
Double free in i18n/zonemeta.cpp in International Components for Unicode (ICU) for C/C++ through 59.1 allows remote attackers to execute arbitrary code via a crafted string, aka a "redundant UVector entry …

Update icu4j to resolve CVEs

---

contributors.txt
doc/csharp-target.md

Added a 'using' statement for namespace using Antlr4.Runtime.Tree, so that IParseTree can be found without fully qualified name.
Fixed typo in property Parser.BuildParseTree.

Updated csharp-target doc

---

contributors.txt
runtime/Python3/src/antlr4/atn/ParserATNSimulator.py

Solve issue #2291 
Tested on my sample file and it works as expected
(took the opportunity to sign contributors.txt)

Enable ParserATNSimulator debug mode in Python3 target

---

runtime/JavaScript/src/antlr4/tree/Tree.js

I've been encountering a problem where the default generated visitor in javascript. It will crash because in the `visit` method it tries to call `accept` on null because it has been passed a null object by `visitChildren`.
This seems like a bug to me as the `children` field is expected to sometimes be null as it is initialised to null and only made non-null when a child is added. Other places handle this case explicitly but here it's assumed to be non-null.
Making the change in this PR makes my visitor work correctly. Do you think it is the right change to make, or if not what should I be doing instead?
---
To explain my reasoning on why this change and not any other:
- The check could easily be `ctx.getChildCount() > 0` and behave the same. I went for this as it's shorter and we're …

JavaScript parse tree visitor: check if ctx.children is non-null in visitChildren

---

contributors.txt
runtime/Python3/src/antlr4/StdinStream.py

Add StdninStream for python3 runtime. Closes: #2271

---

tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Until now, the generated Python3 code imported the custom parser
superclasses relatively. However, this only worked in Python3 if
the module was inside a package, since relative imports rely on
__name__ to determine the current module's position in the package
hierarchy. In case of a standalone script, this was always __main__
and hence these relative imports failed.
The patch handles this issue them same way as it is handled by
listener imports.

[Python] Add missing lexer super class imports.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Until now, the generated Python3 code imported the custom parser
superclasses relatively. However, this only worked in Python3 if
the module was inside a package, since relative imports rely on
__name__ to determine the current module's position in the package
hierarchy. In case of a standalone script, this was always __main__
and hence these relative imports failed.
The patch handles this issue them same way as it is handled by
listener imports.

[Python3] Fix the import of parser superclasses.

---

doc/getting-started.md

I think we should make the alias for antlr4 and grun same. The grun alias command right now depend on step 2, but antlr4 didn't.
Sign of contributors is here: #2315

Make grun alias as same as antlr4.

---

runtime/Swift/Sources/Antlr4/ANTLRInputStream.swift
runtime/Swift/Sources/Antlr4/BufferedTokenStream.swift
runtime/Swift/Sources/Antlr4/ListTokenSource.swift
runtime/Swift/Sources/Antlr4/UnbufferedTokenStream.swift

Minor tidyups in the stream code.  No semantic change.

[Swift] Minor tidyups in the stream code.

---

contributors.txt
runtime/Cpp/runtime/src/antlr4-common.h

Reasons for changes are in commit messages.
In general, it fixes:
- In MingGW
```
warning: declaration 'class std::exception' does not declare anything
class ANTLR4CPP_PUBLIC std::exception; // Needed for VS 2015.
```
- In Clang (I tested with clang-tidy on Windows specifically)
```
error: forward declaration of class cannot have a nested name specifier [clang-diagnostic-error]
class ANTLR4CPP_PUBLIC std::exception; // Needed for VS 2015.
```
Side note: This sort of reverts the commit [19f584d](https://github.com/antlr/antlr4/commit/19f584da05bcc277f9804a596765acfc3c8172c5), where the `#ifdef` flag for the forward declaration was removed.
Another note: Seems like there's more than just `std::exception` that requires forward declaration.

 Fixed warning from MingGW and error from Clang Windows

---

contributors.txt
runtime/Cpp/runtime/src/support/Any.h

To make it easier to work with the const antlrcpp::Any arguments to
the AbstractParseTreeVisitor class aggregateResult and
shouldVisitNextChild functions, add a public const overload for the
antlrcpp::Any::as member function to return a const StorageType&, and
add a public const overloaded conversion operator returning a const
instance of the type contained within the Any.
Add the private antlrcpp::Any::getDerived function to avoid
duplicating the dynamic_cast of the internal pointer, and call it from
the overloaded Any::as functions and also the Any::is function.

Add const accessors to antlrcpp::Any C++ class

---

contributors.txt
runtime-testsuite/pom.xml
tool-testsuite/pom.xml

Simple removal of `-SNAPSHOT` from the ST4 dependency as it appears to be forgotten

Fix ST4 Snapshot dependency

---

.travis.yml
.travis/run-tests-swift.sh
doc/swift-target.md
runtime-testsuite/processors/pom.xml
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Swift.test.stg
runtime/Swift/Sources/Antlr4/ParserRuleContext.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfigSet.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/PredictionMode.swift
runtime/Swift/Sources/Antlr4/atn/SemanticContext.swift
runtime/Swift/Sources/Antlr4/misc/MurmurHash.swift
runtime/Swift/Sources/Antlr4/misc/extension/UUIDExtension.swift

Move the Swift runtime to Swift 4.2.  There are a number of deprecations and changed semantics here (behavior of implicitly-unwrapped optionals and Hashable most notably).
This also upgrades all the Travis tests to use Xcode 10.1 (including the C++ and .NET macOS tests).

Move the Swift runtime to Swift 4.2

---

runtime/Cpp/runtime/src/support/Any.h

The antlrcpp::Any::is function should not throw a std::bad_cast
exception if the contained type can't be cast to the requested type,
but should instead just return a boolean result. Add a boolean
parameter to the private getDerived helper function to allow callers
to specify whether or not they want the cast results checked. In the
is() function, pass false for this parameter; in the as() functions,
pass true.

Do not throw std::bad_cast from antlrcpp::Any::is

---

runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift

This was always clearly a possibility, looking at the body of the method.
The newly-enabled performance tests expose this bug (and I don't know how
we've gotten away with it otherwise for so long).
The Java runtime also returns null at this point.
This fixes the test failures currently seen in PR #2405 and #2407.

[Swift] Make ParserATNSimulator.precedenceTransition return a nullable value.

---

runtime/Swift/boot.py

Make boot.py work under both Python 2 and 3.  This fixes #2369.
Add an extra exception handler, for neater error messages.

[Swift] Syntax error in antlr4/runtime/Swift/boot.py

---

contributors.txt
runtime/Python3/setup.py

Use of the "typing" library introduced in Python 3.5 is the only thing preventing the Antlr4 runtime to be used with the older Python 3.4.
Fortunately there is a backport available that resolves this dependency: https://pypi.org/project/typing/
Added a version-specific dependency so that the "typing" backport will get installed automatically when using versions of python older than 3.5

Fix install dependency for 'typing' library in python3.4

---

runtime/Swift/Sources/Antlr4/misc/utils/Mutex.swift

The mutex util used in the swift-runtime is not destroyed when deallocated. The change in this PR attempts to fix that

[Swift-runtime] Make sure mutexes are being freed accordingly

---

tool-testsuite/test/org/antlr/v4/test/tool/TestCodeGeneration.java
tool/src/org/antlr/v4/codegen/model/ElementFrequenciesVisitor.java
tool/src/org/antlr/v4/codegen/model/RuleFunction.java
tool/src/org/antlr/v4/tool/Grammar.java

Assign token names to string literals in parse rule contexts

---

contributors.txt
runtime/Cpp/runtime/src/tree/ParseTreeProperty.h

virtual dtor for ParseTreeProperty

---

runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp
runtime/Cpp/runtime/src/atn/ParserATNSimulator.h

Function should still make the same calculation but without leaking memory in the process.

This resolves the recently opened issue 2175 (a memory leak).

---

contributors.txt
runtime/Cpp/runtime/src/BufferedTokenStream.cpp
runtime/Cpp/runtime/src/atn/PredictionContext.cpp

In the orignal PredictionContext::mergeArrays there was a bug on Line 281 where the logic differs from java: It currently is:
bool both$ = payload == EMPTY_RETURN_STATE && a_parent && b_parent;
and should instead match java as:
bool both$ = payload == EMPTY_RETURN_STATE && !a_parent && !b_parent;

C++: fix bug in PredictionContext::mergeArrays

---

runtime/Cpp/runtime/src/support/CPPUtils.cpp

The recently added clang directive cause a new warning for Visual Studio build. Need to include the new code with a directive checking for visual studio

C++ avoid warning in visual studio build due to clang specific directive

---

contributors.txt
runtime/Python2/src/antlr4/TokenStreamRewriter.py
runtime/Python3/src/antlr4/TokenStreamRewriter.py
runtime/Python3/test/TestTokenStreamRewriter.py
runtime/Python3/test/mocks/TestLexer.py

This is a bug. If I insert something after the last token, that ``insertation`` will be executed twice!
A minimal working example is:
test.g4
```
grammar test;
ruleABC : 'aa' EOF ;
```
test.txt
```
aa
```
test.py
```
import sys
from antlr4 import *
from testLexer import testLexer
from testParser import testParser
from antlr4.TokenStreamRewriter import TokenStreamRewriter
from collections import namedtuple
from testListener import testListener
Interval = namedtuple("Interval", ["start", "stop"])
class MyListener(testListener):
def __init__(self, tokens:BufferedTokenStream) -> None:
super().__init__()
self.writer = TokenStreamRewriter(tokens)
def getText(self):
return self.writer.getText(TokenStreamRewriter.DEFAULT_PROGRAM_NAME, Interval(0, len(self.writer.tokens.tokens)))
def …
```

bugfix for python-runtime/TokenStreamRewriter.getText

---

runtime/Python2/src/antlr4/TokenStreamRewriter.py
runtime/Python3/src/antlr4/TokenStreamRewriter.py

@ericvergnaud  I updated the documentation you mentioned at #2452 .
By the way, the interval used here is closed interval while typical python range uses ``[start, stop)``, which is confusing to newbees. So I add this in documentation and update the code for ``getDefaultText`` (which also corresponds with the java version https://github.com/antlr/antlr4/blob/master/runtime/Java/src/org/antlr/v4/runtime/TokenStreamRewriter.java#L360)

update python runtime doc

---

contributors.txt
doc/python-target.md

do not use `input` as  a variable name since it is a [Python built-in function](https://docs.python.org/3/library/functions.html#input)

DOCS: do not use python built-in as variable name

---

tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg

Contrary to Python3, the lexers and parser generated for Python2 target
support only relative imports which causes a failure in case of
standalone scripts. The patch adapts these imports to work in both
cases.

Fix imports in the Python2 sources.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Added `del <file.parserName>` to the end of the `ListenerFile`
template the same way it is used in `VisitorFile`.

Clean up namespace of generated Python3 listeners

---

contributors.txt
doc/csharp-target.md

I didn't seen an issue for this and I didn't add one because it seemed like such a simple change. I hope that's ok.

syntax highlighting for csharp language target doc

---

contributors.txt
runtime/Cpp/runtime/src/support/StringUtils.h

This is the result of https://github.com/antlr/antlr4/issues/2556

getText performance improvement by making UTF32Converter thread_local instead of local.

---

tool-testsuite/test/org/antlr/v4/test/tool/CharSupportTest.java

I've analysed your codebase and noticed that `org.antlr.v4.misc.CharSupport` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

Add unit tests for org.antlr.v4.misc.CharSupport

---

contributors.txt
runtime/Python3/src/antlr4/xpath/XPath.py
runtime/Python3/test/expr/Expr.g4
runtime/Python3/test/expr/ExprLexer.py
runtime/Python3/test/expr/ExprParser.py
runtime/Python3/test/run.py
runtime/Python3/test/xpathtest.py

This commit:
- Fixes some code that does not reflect the current API
- Fixes wrong XPath library behavior, such as failing to apply the "invert" flag on certain operations
- Does general style touch-ups
Further work is necessary, such as implementing tests for this functionality, so that further changes to the API or Runtime won't break functionality, and maybe separate the interpreter data from the library code. For now, a code review would be stellar.

General XPath fixes for the Python3 runtime

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Fixing this issue: https://github.com/antlr/antlr4/issues/2611 (and probably https://github.com/antlr/antlr4/issues/2193)
TextIO has moved since Python 3.6 so it should be imported considering the change for new versions.
[I have signed contributor's file: https://github.com/antlr/antlr4/pull/2612]

Fixed TextIO compatibility with 3.6+

---

contributors.txt
runtime/JavaScript/src/antlr4/PredictionContext.js
runtime/JavaScript/src/antlr4/Utils.js
runtime/JavaScript/src/antlr4/atn/ATNSimulator.js
runtime/JavaScript/src/antlr4/atn/PredictionMode.js

Javascript parser is leveraging {} to cache the contexts. Each time when calling Get,Set, the key is converted to string first. In some cases (nested functions), the performance is very bad due to this. When it deals with simple string like "abs(abs(abs(abs(abs(abs(abs(abs(abs(1)))))))))", it takes minutes to finish. The time can easily reach to hours, as time complexity looks like to be O(2^N). 
This change is to use Map to store the real object in the key to avoid that. After this change, the time is decreased to less than 1 second to handle that string.
I believe #2468 and #2523 will also be addressed by this PR.
This's a call stack when parsing nested functions. And I saw there were huge minor GCs caused by the toString().

Fix javascript parser cache performance issue

---

contributors.txt
runtime/Cpp/runtime/src/RuleContext.cpp
runtime/Cpp/runtime/src/RuleContext.h
runtime/Cpp/runtime/src/tree/ParseTree.h
runtime/Cpp/runtime/src/tree/TerminalNodeImpl.cpp
runtime/Cpp/runtime/src/tree/TerminalNodeImpl.h
runtime/Cpp/runtime/src/tree/Trees.cpp
runtime/Cpp/runtime/src/tree/Trees.h

Add pretty print option, default is non pretty print, the second argument is pretty print flag.
Ref #2490 
```cpp
tree->toStringTree(&parser, true);
```
Here's the demo output
```
(main 
(stat 
(expr 
(id 🍴)) = 
(expr 
(expr 
(id 🍐)) + 
(expr "😎")) ;) 
(stat 
(expr 
(expr 
(expr ( 
(expr ( 
(expr ( 
(expr 
(expr 
(id x)) * 
(expr 
(id π))) )) )) )) * 
(expr 
(id µ))) + 
(expr 
(id ∰))) ;) 
(stat 
(expr 
(expr 
(id a)) + 
(expr ( 
(expr 
(expr 
(expr 
(id x)) * 
(expr ( 
(expr 
(expr 
(id y)) ? 
(expr 0) : 
(expr 1)) ))) + 
(expr 
(id z))) ))) ;) <EOF>)
```

Feature: Add pretty print AST to CPP runtime

---

.travis/before-install-linux-cpp.sh
.travis/before-install-linux-go.sh
.travis/before-install-linux-java.sh
.travis/before-install-linux-javascript.sh
.travis/before-install-linux-python2.sh
.travis/before-install-linux-python3.sh
.travis/run-tests-python2.sh
.travis/run-tests-python3.sh

Remove .travis/before-install-linux-{cpp,java,python2,python3}.sh, and
remove some lines from before-install-linux-{javascript,go}.sh.
These contained apt commands for configuring the Mono project's GPG key,
which is not used in any of these builds, and pointless apt-get update
calls.

Remove unnecessary Travis files.

---

runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java

Check the exit status of the processes run during the runtime-testsuite
for Swift.  This means that we'll catch low-level issues earlier.
This changeset also changes the exception handling so that exceptions
throw as far up as possible so that we don't proceed with a test when
something has already broken.

[Swift] Check process exit status during tests.

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/CSharp.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Chrome.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Cpp.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Explorer.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Firefox.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Java.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Node.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python2.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Safari.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Swift.test.stg

Remove unused DeclareLocal and PlusMember macros from *.test.stg.
DeclareLocal was last used in 5c5228 (June 2015) and PlusMember was
last used in 7f16fe6 (Nov 2016).

Remove unused macros from test templates.

---

contributors.txt
runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake
runtime/Cpp/cmake/README.md

CMake 3.14 introduced changes to the ExternalProject Module
> The ExternalProject module ExternalProject_Add() command learned to apply SOURCE_SUBDIR when BUILD_IN_SOURCE is also used. The BUILD_COMMAND is run in the given SOURCE_SUBDIR of the SOURCE_DIR.
https://cmake.org/cmake/help/v3.14/release/3.14.html#modules
This PR updates ExternalAntlr4Cpp.cmake to work with CMake 3.14.
Credit goes to https://github.com/empirical-soft/empirical-lang/pull/10

Fix ExternalAntlr4Cpp.cmake to work with CMake 3.14

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg

When @members is used in the lexer grammar, the content gets placed in an arbitrary location that is out of scope of the generated lexer. The template was updated so the content gets placed in the constructor, allowing for the creation of class members. This is consistent with the placement of members for parser grammars in the Javascript target.

Fix placement of @members in Javascript target lexers

---

runtime/JavaScript/src/antlr4/package.json

The main entry point for JavaScript runtime package is not right: after publish to npm, the main field should point to index.js.
[https://unpkg.com/browse/antlr4@4.7.2/](https://unpkg.com/browse/antlr4@4.7.2/)

Fix main entry point for JavaScript runtime npm package

---

appveyor.yml

Install PHP to C:\tools\php.  This fixes the AppVeyor tests, because
they were looking in C:\tools\php73, but the Chocolatey package has
recently moved to 7.4.

[PHP] Fix AppVeyor tests

---

doc/releasing-antlr.md
runtime/Cpp/README.md
runtime/Cpp/deploy-windows.cmd
runtime/Cpp/runtime/antlr4cpp-vs2017.vcxproj
runtime/Cpp/runtime/antlr4cpp-vs2019.vcxproj
runtime/Cpp/runtime/antlr4cpp-vs2019.vcxproj.filters
runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp

This patch contains a few changes to build now VS 2017/19 binaries instead of VS 2013/15 (with the deployment script). Also a warning was fixed (suppressed) and the docs updated wrt. the C++ target.

C++ VS project updates for next ANTLR4 release

---

runtime/Cpp/runtime/src/CommonTokenFactory.cpp
runtime/Cpp/runtime/src/CommonTokenFactory.h
runtime/Cpp/runtime/src/Lexer.cpp
runtime/Cpp/runtime/src/Lexer.h
runtime/Cpp/runtime/src/ListTokenSource.cpp
runtime/Cpp/runtime/src/ListTokenSource.h
runtime/Cpp/runtime/src/Parser.cpp
runtime/Cpp/runtime/src/Parser.h
runtime/Cpp/runtime/src/Recognizer.h
runtime/Cpp/runtime/src/TokenSource.h

Change the setTokenFactory template function in the Lexer, Parser, and
TokenSource classes to be parameterized by Factory type rather than by
token type. Change the setTokenFactory signature to require the
function argument to be a Ref of the Factory template parameter type
so it can be correctly converted and assigned to the token factory
member. The type of that member is Ref<TokenFactory<CommonToken>>,
which implies that the Factory template parameter must be of a type
convertible to TokenFactory<CommonToken>.

Fix #2727: improve setTokenFactory in Cpp target

---

runtime/JavaScript/src/antlr4/dfa/DFA.js
runtime/JavaScript/src/antlr4/dfa/DFASerializer.js
runtime/JavaScript/src/antlr4/dfa/DFAState.js

This PR is a follow up on #2742 to refactor the DFA object declarations to:
- use es6 classes/inheritance instead of direct prototype manipulation. Es6 class declarations are really just syntactic sugar over prototype inheritance so this change should have no effect on the runtime itself.
- use const/let on variable declarations to improve variable scoping
- refactor comments to be JsDoc compatible which most IDEs can leverage to provide better developer feedback

Javascript: migrate prototypical DFA objects to es6 classes

---

contributors.txt
runtime/Cpp/CMakeLists.txt

This pull request fixes #2606. It installs `antrl4-generator` and `antlr4-runtime` in separate files following the CMake's [search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure).

Fix CMake packaging

---

runtime/JavaScript/.babelrc
runtime/JavaScript/package-lock.json
runtime/JavaScript/package.json
runtime/JavaScript/webpack.config.js

This PR is a follow up on:
- https://github.com/antlr/antlr4/pull/2749#issuecomment-589905171
- https://github.com/antlr/antlr4/pull/2755
This PR adds a babel transformation to the webpack configuration of antlr4.js. This "enables transforms for ES2015+" as stated on [babel website](https://babeljs.io/setup#installation).
According to [this website](https://browserl.ist/) this would default to a global coverage of `90.77%`.
For a comparison of the output code you can check [this gist](https://gist.github.com/carocad/2da39f4d918fd25a704b7a3c3da92724)

Javascript: browser support increased with babel transformation

---

contributors.txt
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Tree/ParseTreeWalker.cs
runtime/Cpp/runtime/src/tree/ParseTreeWalker.h
runtime/Go/antlr/tree.go
runtime/Java/src/org/antlr/v4/runtime/tree/ParseTreeWalker.java
runtime/JavaScript/src/antlr4/tree/Tree.js
runtime/Python2/src/antlr4/tree/Tree.py
runtime/Python3/src/antlr4/tree/Tree.py
runtime/Swift/Sources/Antlr4/tree/ParseTreeWalker.swift

My pull request based on the issue #2759 and the answer given by @ericvergnaud . I applied the changes to all target languages. Hopefully, the documentation style conforms to all the target languages and is accepted by each respective compiler.

Clarify and expand documentation for runtime ParseTreeWalker

---

contributors.txt
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/AntlrInputStream.cs

refactored AntlrInputStream.cs by removing a redundand if-statement

---

runtime/JavaScript/src/antlr4/RuleContext.js
runtime/JavaScript/src/antlr4/tree/Tree.js
runtime/JavaScript/src/antlr4/tree/Trees.js

This PR is a follow up on #2749 specifically [this comment](https://github.com/antlr/antlr4/pull/2749#issuecomment-590068416)
This PR removes 2 of the 3 cyclic dependencies from before:
```bash
$ madge --circular src/antlr4/index.js 
Processed 47 files (1.1s) 
✖ Found 3 circular dependencies!
1) LL1Analyzer.js > PredictionContext.js > RuleContext.js > atn/ATN.js
2) RuleContext.js > tree/Trees.js > ParserRuleContext.js
3) RuleContext.js > tree/Trees.js
```
Number 2 and 3 are eliminated.
The solution for this specific case is to check for `RuleNode` interface since both `RuleContext` and `ParserRuleContext` implement it (`RuleNode -> RuleContext -> ParserRuleContext`) and since `RuleContext` is the only implementation of `RuleNode` the checks are equivalent.
NOTE: On Javascript the RuleNode …

Javascript: fix some cyclic dependencies

---

contributors.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime/Go/antlr/lexer.go
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

The ANTLR Go codegen allocates mutable global variables which can result in data races as evidenced in https://github.com/google/cel-go/pull/177 and reported in #2040. As a local workaround, global variables in the generated source were shifted into local variables within the `NewLexer` and `NewParser` functions. 
While the change made the generated code thread-safe, it came at a significant CPU and memory overhead in parse-heavy call paths. However, exporting the `SetInputStream` method on the `lexer.go` makes it possible to use `sync.Pool` objects with the modified codegen artifacts and reduces the parsing overhead to within striking distance of the prior non-thread-safe code.
To take advantage of such thread-safety and object reuse within ANTLR Go applications, developers would need to …

[Go] Thread-safe ANTLR codegen

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg

Avoid stepping through ANTLR generated code when debugging (C#)

---

tool/src/org/antlr/v4/codegen/Target.java
tool/src/org/antlr/v4/codegen/target/CppTarget.java

If grammars contain something like ?? as a lexer rule (e.g. `CONDITION_CONVERSION: '??';`), the generated C++ code will contain something like `"'??'"` in _literalNames. This can cause compiler warnings or even unintended behaviour, because sequences starting with two ? characters are interpreted as trigraphs.
Using an override of shouldUseUnicodeEscapeForCodePointInDoubleQuotedString in CppTarget
shouldUseUnicodeEscapeForCodePointInDoubleQuotedString in Target was changed from private static to protected to allow overriding
(It's possible to avoid this issue by using C++17 (drops support for trigraphs) and `-Wno-trigraphs`, but escaping the ? character is a universal fix).

C++ target: escape ? character to prevent accidental trigraphs

---

contributors.txt
runtime/Cpp/CMakeLists.txt

On linux. Most users haven't installed libc++-dev, but ANTLR is passing
the "--stdlib=libc++" argument. As a result, this won't compile. Users
will see:
```
/tmp/antlr4/runtime/Cpp/runtime/src/antlr4-common.h:8:10: fatal error:
'algorithm' file not found
```
This is caused by the "WITH_LIBCXX" option.
It was introduced by:
https://github.com/antlr/antlr4/commit/d46ef90aa03066300752895d57fc57a1c5aa8ee6
It causes the option "--stdlib=libc++" to be appended by default.
I believe its default value should have been left as "Off".
With "off" by default, clang will use its default C++ library, which is
always available.
The WITH_LIBCXX option is kept, being able to change the C++ library
might be useful?
BUG=https://github.com/antlr/antlr4/issues/2898

Fix clang compile error with --stdlib=libc++

---

contributors.txt
doc/cpp-target.md

tree::ParseTreeWalker::DEFAULT is not a pointer

Fix C++ target README example

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

All other switch statements have a default case (either "break" or "<error>"), but these two are missing.
Does not change functionality, simply fixes a warning - and allows a project to build with -Werror.

[C++ codegen] Add default cases to AltBlock and OptionalBlock

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

Prior to C++20, the type of a "UTF-8 encoded string literal" is `char const *` - i.e. it is exactly the same as a non-prefixed string literal (they are semantically different, but technically the same).
Since C++20, the type of a UTF-8 encoded string literal is changed to `char8_t const *` - which is not convertable to `char const *`.  Even in C++20, there is no actual change to how characters are stored, only the type is changed (they are now semantically different, and supposed to be technically different - but nothing in the language actually uses the semantics).
In short, removing the u8"" prefix has no effect prior to C++20, and simply allows compilation to succeed since C++20.
Fixes #2844

[C++ codegen] Remove use of the u8"" string literal prefix

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

To avoid unexpected implicit conversions and copy-initialization.

[C++ codegen] Add explicit keyword to constructor

---

runtime/Cpp/runtime/antlr4cpp-vs2019.vcxproj
runtime/Cpp/runtime/src/ANTLRInputStream.cpp
runtime/Cpp/runtime/src/ANTLRInputStream.h

Guarded by the `__cplusplus` macro as it is only available in C++17 or newer.
This avoids a copy if the input is actually `char const *` (due to implicit conversion to `std::string` in the pre-C++ 17 version), and performs the same if the input is actually `std::string`.

[C++ runtime] Add AntlrInputStream(std::string_view) constructor

---

runtime/Cpp/runtime/antlr4cpp-vs2019.vcxproj
runtime/Cpp/runtime/src/IntStream.h
runtime/Cpp/runtime/src/Lexer.h
runtime/Cpp/runtime/src/Recognizer.h
runtime/Cpp/runtime/src/Token.h
runtime/Cpp/runtime/src/TokenStreamRewriter.h
runtime/Cpp/runtime/src/atn/ATN.h
runtime/Cpp/runtime/src/atn/ATNConfig.cpp
runtime/Cpp/runtime/src/atn/ATNConfig.h
runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp
runtime/Cpp/runtime/src/atn/ATNDeserializer.h
runtime/Cpp/runtime/src/atn/ATNState.h
runtime/Cpp/runtime/src/atn/LL1Analyzer.h
runtime/Cpp/runtime/src/atn/LexerATNSimulator.h
runtime/Cpp/runtime/src/atn/PredictionContext.h
runtime/Cpp/runtime/src/misc/MurmurHash.h

Defining a static const member in a header breaks ODR, as the object will be defined in every translation unit that includes the header.
Instead, the members should either be declared `inline` (which is implicitly the case for `constexpr` members) or initialized in a cpp. Alternatively, using an anonymous enum allows the definition to remain inside the header meaning that the compiler can still choose to inline values.

[C++ runtime] Fix static const ODR violations

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

The testcase org.antlr.v4.test.runtime.cpp.TestParserExec was failing after #2806 removed duplicate semicolons from the declarations in generated Cpp header files.
The bug was triggered by TestParserExec because it includes a grammar with alternative labels:
```Antlr
grammar T;
start : a* EOF;
a
: label=subrule {std::cout << $label.text << std::endl;} #One
| label='y' {std::cout << $label.text << std::endl;} #Two
;
subrule : 'x';
WS : (' '|'\n') -> skip ;
```
Grammars without alternative labels (most?) were not affected.
The templates for StructDeclHeader and AltLabelStructDeclHeader differed in whether they appended semicolons to attributes:
StructDeclHeader: `<attrs: {a | <a>;}; separator="\n">`
AltLabelStructDeclHeader: git `<attrs: {a | <a>}; separator = "\n">`

Fix regressions in travis Cpp tests

---

contributors.txt
runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Parser.cs

Previously, when using the internal constructor, the trace listener had no text stream and it threw a null pointer exception. I have chosen the default stream to be Console.Out If somebody wants to create an instance of Trace Listener they will have to include a Parser and a Text Writer such that no such errors are thrown.

Made C# Trace Listener usable for most cases

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

Trying to compile ANTLR from a fresh git checkout using cmake and msvc fails with linker errors.
```
3>gtestd.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_checked_api.obj [F:\Development\antlr4\runtime\Cpp\build\runtime\utfcpp-prefix\src\utfcpp-build\tests\apitests.vcxproj]
3>msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: struct _Cvtvec __cdecl std::_Locinfo::_Getcvt(void)const " (?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ) already defined in gtestd.lib(gtest-all.obj) [F:\Development\antlr4\runtime\Cpp\build\runtime\utfcpp-prefix\src\utfcpp-build\tests\apitests.vcxproj]
3>msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: bool __cdecl std::ios_base::good(void)const " …
```

Fix linker issue when compiling Cpp runtime with CMake and MSVC on Windows

---

doc/csharp-target.md

Correct the spelling of 2 members: `Default` and `Walk`

Correct the csharp-target example for invoking a custom listener

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

Update Swift codegen template to resolve warning:
> ~~Variable '_localctx' was never mutated; consider changing to 'let' constant~~
> Variable '_parentState' was never mutated; consider changing to 'let' constant
> Variable '_startState' was never mutated; consider changing to 'let' constant
Since there is no path where they can be changed I would say its best to just generate without the warnings.
Edit: `_localctx` has been reversed because it is needed for a test

[Swift] Update codegen template

---

tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

The ParseTreeProtocol defines enterEventRule and ExitEventRule as throws. The generated Listener and BaseListener are missing the throws clause, making it impossible for a subclass to throw an Error in these methods.

added throws declaration missing from generated swift code

---

contributors.txt
runtime/Swift/Sources/Antlr4/tree/ParseTreeProperty.swift

I have been converting the examples from "The Definitive ANTLR4 Reference" to Swift. One example in chapter 7 called listeners/TestEvaluatorWithProps.java references a class called  ParseTreeProperty. This class is currently missing from the Swift version of ANTLR4 and is the reason for - and content of - this pull request.

Added missing swift version of class ParseTreeProperty

---

contributors.txt
runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/LexerExecDescriptors.java
tool/src/org/antlr/v4/codegen/target/PHPTarget.java

Fixed https://github.com/antlr/antlr4/issues/2709.

[PHP] Escape dollar sign in target string literal  

---

contributors.txt
runtime/Python3/src/antlr4/Lexer.py
runtime/Python3/src/antlr4/Parser.py

Changed Python runtime Lexer.py, Parser.py to support version >= 3.5

---

contributors.txt
doc/javascript-target.md

When using the JavaScript code generated by antlr4 in a web browser environment, we have to make exceptions for certain node.js based global modules. The configuration provided in documentation is incorrect and no longer works on new versions of Webpack. This PR attempts to correct the documentation with new configuration that works. Thanks to the Webpack team for pointing out the correct approach.
My understanding is that even after switching to ES6, we will still need this configuration.

Corrected Webpack configuration in JavaScript documentation

---

doc/lexer-rules.md

fixing a typo, was role instead of rule

fixing a typo, was role instead of rule

---

contributors.txt
doc/lexicon.md

Documentation: Added Missing lexer/parermodifier clarification in example

---

runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python2/BasePython2Test.java
runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java

Hi @ericvergnaud I updated to allow 3.8 in addition. required interface change to python test routines. hope this is ok.
```java
protected List<String> getPythonExecutables() {
return Arrays.asList("python3.7", "python3.8");
} // force 3.7 or 3.8
```

allow multiple versions when locating python tool

---

.travis.yml
runtime/Cpp/runtime/src/Vocabulary.h

Alternative PR to #2908, upgrading only the c++ build
The first build shows that openjdk8 is not available with Ubuntu focal:
https://travis-ci.org/github/antlr/antlr4/builds/746825671
```
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "GPL" --cacerts" failed and exited with 3 during .
```
The second build shows the issues in the C++ runtime:
https://travis-ci.org/github/antlr/antlr4/builds/746909160
```
In file included from /tmp/BaseCppTest-main-1606808268300/TLexer.cpp:5:
In file included from /tmp/BaseCppTest-main-1606808268300/TLexer.h:7:
In file included from /home/travis/build/antlr/antlr4/runtime-testsuite/target/classes/Cpp/runtime/src/antlr4-runtime.h:126: …
```

travis: upgrade c++ build to focal & llvm 10

---

tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg

The generated exception clause block was missing a leading '}' to terminate the try block.
This addresses Issue #1741.

Fixed exception clauses in JS template.

---

contributors.txt
runtime/JavaScript/src/antlr4/CharStreams.js

Hi,
As of today, `InputStream` is the default export of its module and not a named one.
The module `CharStreams` was trying to load the named one which does not exist.
Test case 
```javascript
console.log(require('antlr4').CharStreams.fromString('test'))
```
Expected
```
InputStream {
name: '<empty>',
strdata: 'test',
decodeToUnicodeCodePoints: true,
_index: 0,
data: [ 116, 101, 115, 116 ],
_size: 4
}
```
Actual
```
TypeError: InputStream is not a constructor
at Object.fromString (node_modules\antlr4\src\antlr4\CharStreams.js:19:12)
```

:ambulance: fix bad import

---

tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
tool/src/org/antlr/v4/semantics/BasicSemanticChecks.java
tool/src/org/antlr/v4/tool/ErrorType.java

* Invalid code won't be generated even if tokens or rules are empty (all runtimes)
* Check parser.rules instead of parser.tokens in Cpp.stg (fix misprint)
* Fix throwing of "grammar has no rules" error, consider only not fragment rules
Fix #3000

Invalid generated code and no rules error if only fragments are used

---

runtime/Swift/Sources/Antlr4/Lexer.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/LexerActionExecutor.swift
runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

Fix swift warnings

---

runtime/CSharp/Antlr4.csproj

This PR is for https://github.com/antlr/antlr4/issues/3049. It adds a line to Antlr4.csproj to build a .nupkg file by default, which is useful when compiling the C# code using dotnet.

Fix for https://github.com/antlr/antlr4/issues/3049

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Fixes: https://github.com/antlr/antlr4/issues/2611 (Same resolution as in https://github.com/antlr/antlr4/pull/2613) but for LexerFile
(Contributors file signed)

Fix TextIO compatibility with Python 3.6+ in LexerFile

---

runtime/JavaScript/src/antlr4/Utils.js
runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
runtime/JavaScript/src/antlr4/atn/SemanticContext.js

fix javascript semantic predicates

---

doc/lexicon.md

Add missing single quote in lexicon.md

---

runtime/Cpp/CMakeLists.txt
runtime/Cpp/README.md
runtime/Cpp/cmake/Antlr4Package.md
runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake
runtime/Cpp/cmake/README.md
runtime/Cpp/cmake/antlr4-generator.cmake.in

Currently, the C++ runtime compilation is forced to used the C++11 standard, since CMAKE_CXX_STANDARD 11 is set in runtime/Cpp/CMakeLists.txt.
When linking an executable built with a newer C++ standard (for example, C++17) against the runtime build with C++11, the following linker error occurs:
```
FAILED: src/antlr/demo 
: && /usr/bin/clang++-11  -fuse-ld=lld src/antlr/CMakeFiles/demo.dir/src/demo.cpp.o src/antlr/CMakeFiles/demo.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.o src/antlr/CMakeFiles/demo.dir/antlr4cpp_generated_src/TParser/TParser.cpp.o -o src/antlr/demo  src/antlr/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/dist/libantlr4-runtime.a && :
ld.lld: error: undefined symbol: antlr4::ANTLRInputStream::ANTLRInputStream(std::basic_string_view<char, std::char_traits<char> >)
>>> …
```

Cpp target: allow building runtime with newer C++ standards

---

contributors.txt
doc/csharp-target.md

```c#
CharStreams.fromstring(input);
```
should be fixed to
```c#
CharStreams.fromString(input);
```
so as to run functionally.
The code of this API is at [here](https://github.com/antlr/antlr4/blob/4b649103f31e0c0bc3bd0bb964efd0dea6b9f5a0/runtime/CSharp/src/CharStreams.cs#L88).

fix a typo in the csharp-target doc

---

antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java
contributors.txt

Fix #3093 - The antlr4-maven-plugin is not marked as thread safe

---

runtime/Cpp/runtime/src/antlr4-common.h
runtime/Cpp/runtime/src/support/CPPUtils.cpp
runtime/Cpp/runtime/src/support/CPPUtils.h

Before, to use `finally`, the compiler had to:
- set up the lambda;
- construct a `std::function` that could allocate if it wants to;
- call `finaly()`;
- the dtor of the `std::function` would call the lambda;
Neither MSVC nor GCC could inline any of the functions of `std::function`, the `finally` function, nor the lambda, even with LTO.
With this patch both MSVC and GCC can see through the object and inline the lambda directly into the function code, making it essentially free.
MSVC would occasionally still set up the `FinalAction` object even if it doesn't use it, but would inline the lambda anyway.
Should we migrate to a non-movable `FinalAction` wrapper that wouldn't need the `bool` field so MSVC would get the idea to not set up the object?
Anyway, this should still be faster and …

[C++] Performance improvement in finally

---

contributors.txt
runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake

Fix typo in ExternalAntlr4Cpp.cmake

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

Try to find system's `utf8cpp` first, instead of downloading it from github. `utf8cpp` 3 defines a cmake package, so we can use `find_package`. Older `utf8cpp`s don't, so we try also `find_path`. If all that fails, we still fall back to github download.
This is needed as distributions cannot download stuff from their build systems. And people want to use libraries/headers from the distribution anyway.
I had to reorder the file a bit, so that the libraries are defined through the `utf8cpp` detection.

Cpp/runtime: use utfcpp from system if possible

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

Reverts antlr/antlr4#3040
This seems to conflicts more than expected with previous patches for utfcpp.

Revert "Cpp target: No building tests/samples for external utfcpp"

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

As promised to @mike-lischke , here is the rebase of #3040 :
> It is unnecessary that each time the external dependency utfcpp is pulled, its tests are built and run. Also its samples are unnecessarily generated.
> I suggest to use the provided cmake to disable this behavior.
> You can find the documentation of the cmake options here: https://github.com/nemtrif/utfcpp/blob/v3.1.1/CMakeLists.txt#L10-L12
> 
> Let's make this build a little bit more green and not use unnecessary resources.

Patch utfcpp build

---

contributors.txt
runtime/Go/antlr/go.mod

Add `go.mod` to go runtime module

---

runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/go/GoFileFilter.java

Sorry this took so long, life got in the way 😅 
This PR fixes the errors in the go runtime tests by setting up a go module for each test and copying the runtime to a subdirectory. This way, we can use the same source that is already in the pr, instead of `go get`ing the version already in the github repo like in my previous PR.
Hopefully fixes #3175

Fix tests for go runtime

---

contributors.txt
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

This change is a simple workaround which makes grammars which use actions and predicates calling something on `this` work also in Go.
See https://github.com/antlr/grammars-v4/issues/2177 for a bit of background. This change would allow compiling JavaScript grammar with antlr with a bit less manually patching. (There are few more steps to do to get it working.)

Making compatibility with actions and predicates in Go better

---

contributors.txt
tool/src/org/antlr/v4/codegen/target/GoTarget.java

Hi,
I fixed a typo in the code generator for Go (fixes #3204).
Best,
Marc

Fix typo in Go code generator (fixes #3204)

---

contributors.txt
runtime/Python2/src/antlr4/IntervalSet.py
runtime/Python2/src/antlr4/atn/ATNDeserializationOptions.py
runtime/Python3/src/antlr4/IntervalSet.py
runtime/Python3/src/antlr4/atn/ATN.py
runtime/Python3/src/antlr4/atn/ATNDeserializationOptions.py

Previously, in python2's runtime there was a typo where we used `readonly` when the property was actually `readOnly`.
After discussing with Eric on #3226, We decided to change all properties named `readOnly` to `readonly` since that is what the java runtime does.

[Python 2, Python 3] Change all "readOnly" to "readonly"

---

contributors.txt
runtime/Go/antlr/dfa.go
runtime/Go/antlr/dfa_serializer.go
runtime/Go/antlr/dfa_state.go
runtime/Go/antlr/lexer_atn_simulator.go
runtime/Go/antlr/parser_atn_simulator.go

This fixes #2940.
There was some missing and incorrect usage of locks which caused Data Race Warning on Go Target. 
I solved the problem by putting a lock on the correct spots and by making sure read/write are coming through getter and setters.

Fix for #2940: fix data race warning in Go

---

contributors.txt
doc/getting-started.md

remove redundant slash in getting-started.md

---

runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/dfa/DFA.swift
runtime/Swift/Sources/Antlr4/dfa/DFAState.swift
runtime/Swift/Tests/Antlr4Tests/Threading.g4
runtime/Swift/Tests/Antlr4Tests/ThreadingTests.swift

Request for review: @janyou, @ewanmellor, @hanjoes, @rmehta33 
By sharing the mutex in the same way as the DFA array it becomes possible to run in parallel
Fixes #3271

[Swift] Changes to Mutex-es to guard the staticly shared [DFA]

---

runtime/JavaScript/src/antlr4/Lexer.js

Fix stack overflow exception when using Lexer.type in JavaScript

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

I and others (e.g. https://github.com/npm/npm/issues/6285 ) have encountered reliability problems with git: github urls in certain contexts. These problems can be overridden with `git config --global url.https://github.com/.insteadOf git://github.com/` but just starting with the https url would be easier for everyone.

Change utfcpp git url to use https

---

runtime/Cpp/runtime/src/TokenStreamRewriter.cpp
runtime/Cpp/runtime/src/TokenStreamRewriter.h
runtime/Cpp/runtime/src/atn/ATNConfig.h
runtime/Cpp/runtime/src/atn/ATNConfigSet.cpp
runtime/Cpp/runtime/src/atn/ATNSerializer.cpp
runtime/Cpp/runtime/src/atn/ATNSerializer.h
runtime/Cpp/runtime/src/atn/LexerATNSimulator.cpp
runtime/Cpp/runtime/src/atn/LexerActionExecutor.cpp
runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp
runtime/Cpp/runtime/src/atn/PredictionContext.cpp
runtime/Cpp/runtime/src/atn/SemanticContext.cpp
runtime/Cpp/runtime/src/misc/InterpreterDataReader.h
runtime/Cpp/runtime/src/support/CPPUtils.cpp
runtime/Cpp/runtime/src/support/CPPUtils.h
runtime/Cpp/runtime/src/tree/AbstractParseTreeVisitor.h
runtime/Cpp/runtime/src/tree/pattern/ParseTreePatternMatcher.cpp

Pushing upstream a bunch of performance, build, and best practice fixes.
Most of the performance fixes are related to incorrect/misused auto. Lots of places simply use `auto` which causes values to be copied. They have been switched to `const auto&` which avoids copying-by-value. The best practice fix is switching to throw `RuntimeException` instead of a string literal.

[C++] Upstream various performance, build, and best practice fixes

---

runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTestSupport.java
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/Antlr4.Test.csproj
runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java
runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/BaseNodeTest.java

I've added compilation of C# runtime project before the test session. After that, each test use compiled assembly instead of referencing to `.csproj` and extra compilation.
For Node I've removed npm packaging and implemented referencing right on runtime files.
For Go I've added GOROOT redirecting and removed extra copying of runtime files on every test.
There is the table with optimization results:
| Language | [Before](https://ci.appveyor.com/project/parrt/antlr4/builds/41692715) | [After](https://ci.appveyor.com/project/parrt/antlr4/builds/41693296) | Ratio |
|-                 | -          | -        | -    |
| C#             | 21 min | 15 min | 0.7 |
| JavaScript | 22 min | 6 min | 0.3 |
| Go            | 20 min | 8 min | 0.4 |
| **All**       | 88 min | 55 min | 0.63 |
Now runtime …

C#, JavaScript, Go runtime tests performance improvements

---

runtime/Java/src/org/antlr/v4/runtime/ANTLRFileStream.java
runtime/Java/src/org/antlr/v4/runtime/ANTLRInputStream.java
runtime/Java/src/org/antlr/v4/runtime/CommonToken.java
runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java
runtime/Java/src/org/antlr/v4/runtime/misc/NotNull.java
runtime/Java/src/org/antlr/v4/runtime/misc/TestRig.java
runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java
tool/src/org/antlr/v4/codegen/target/GoTarget.java
tool/src/org/antlr/v4/misc/MutableInt.java
tool/src/org/antlr/v4/tool/ErrorManager.java

This pull request addresses issues identified by https://github.com/google/error-prone.

[Java] Fix complaints from ErrorProne static analysis

---

runtime/Cpp/runtime/src/Exceptions.cpp
runtime/Cpp/runtime/src/Exceptions.h
runtime/Cpp/runtime/src/antlr4-common.h
runtime/Cpp/runtime/src/atn/ATN.cpp
runtime/Cpp/runtime/src/atn/ATN.h

Get rid of `NOEXCEPT` macro as we are on C++17 and `noexcept` is available.

[C++] Switch from NOEXCEPT to noexcept

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

Partially undo a previous commit. I misread the original preprocessor condition. It is actually testing for C++ 20, not C++ 17. So it needs to stay otherwise compilers conformant to C++ 17 without any extensions will fail.

[C++] Partially undo commit a8d828016e54adfc403326d8e56d93e7c75c27fc

---

runtime/Cpp/runtime/src/ANTLRInputStream.cpp
runtime/Cpp/runtime/src/ANTLRInputStream.h

Not sure when this was added, but std::string is implicitly convertible to std::string_view. So this can cause compilation errors as the compiler does not know which one to select.

[C++] Fix ambiguous ANTLRInputStream constructor overload

---

.clang-format

This change adds a `.clang-format` file to the root directory to enable consistent styling of C++. It disables all languages except C++ for now (unless we decide to use clang-format for other languages as well). I based it off of LLVM and forced right alignment for pointers and references. It seems to be pretty close, however we can always tweak it going forward as it is very configurable. https://clang.llvm.org/docs/ClangFormatStyleOptions.html

Add .clang-format file to ensure consistent style of C++

---

.circleci/scripts/run-tests-cpp.sh
.github/scripts/run-tests-cpp.sh
.travis/run-tests-cpp.sh
runtime/Cpp/CMakeLists.txt
runtime/Cpp/deploy-macos.sh
runtime/Cpp/runtime/CMakeLists.txt
runtime/Cpp/runtime/src/ANTLRInputStream.cpp
runtime/Cpp/runtime/src/ANTLRInputStream.h
runtime/Cpp/runtime/src/UnbufferedCharStream.cpp
runtime/Cpp/runtime/src/antlr4-common.h
runtime/Cpp/runtime/src/support/StringUtils.cpp
runtime/Cpp/runtime/src/support/StringUtils.h
runtime/Cpp/runtime/src/support/Unicode.h
runtime/Cpp/runtime/src/support/Utf8.cpp
runtime/Cpp/runtime/src/support/Utf8.h
runtime/Cpp/runtime/tests/Utf8Test.cpp

Historically ANTLRv4 C++ runtime has relied on deprecated facilities provided by the standard library to convert between UTF-8, UTF-16 (Windows only) and UTF-32. More recently https://github.com/nemtrif/utfcpp was added as an option. ANTLR has historically kept external dependencies for its runtimes to a minimum, basically nothing except the languages standard library. This change restores that by implementing full UTF-8 and UTF-32 handling based on a port off CEL's C++ implementation which is itself based on Go's `unicode/utf8` package. UTF-16 support (indirectly via `ws2s` and `s2ws`) has been dropped as it was only relevant for Windows. On Windows users should use `MultiByteToWideChar` and `WideCharToMultiByte`.
With this change ANTLRv4 C++ is now dependency free, has full UTF-8 and …

[C++] Implement standalone Unicode encoding and decoding handling

---

runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp

Improve ATN deserialization by avoiding unnecessary copies and right-sizing `std::vector` when the size is known ahead of time.

[C++] Optimize ATN deserialization

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

fixes #2278
@jjeffcaii @ericvergnaud please review

Get rid of reflection in Go.stg

---

runtime/Cpp/runtime/src/dfa/DFA.cpp
runtime/Cpp/runtime/src/dfa/DFA.h
runtime/Cpp/runtime/src/dfa/DFASerializer.cpp
runtime/Cpp/runtime/src/dfa/DFASerializer.h
runtime/Cpp/runtime/src/dfa/DFAState.cpp
runtime/Cpp/runtime/src/dfa/DFAState.h
runtime/Cpp/runtime/src/dfa/LexerDFASerializer.cpp
runtime/Cpp/runtime/src/dfa/LexerDFASerializer.h
runtime/Cpp/runtime/src/misc/Interval.cpp
runtime/Cpp/runtime/src/misc/Interval.h

Fix const correctness, remove virtual where it makes sense (class is instantiated directly by antlr4 and there is no way for users to override), and make things constexpr where it is feasible.

[C++] Clean up antlr4::misc::Interval and antlr4::dfa

---

runtime/Go/antlr/utils.go
runtime/Go/antlr/utils_test.go

The current `BitSet` implementation uses a map. The ideal implementation uses a slice of integers and has significantly less overhead. This pull request switches `BitSet` to be backed by a slice of integers. This is very similar to how things like `std::bitset` in C++ are implemented.

[Go] Improve BitSet implementation

---

runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java

After this its possible to update pom.xml to make the tests parallel, at least for Go. The other test suites may not support that.
```
diff --git a/runtime-testsuite/pom.xml b/runtime-testsuite/pom.xml
index 9c63282cd..c75dc195a 100644
--- a/runtime-testsuite/pom.xml
+++ b/runtime-testsuite/pom.xml
@@ -106,6 +106,8 @@
<include>**/dart/Test*.java</include>
<include>${antlr.tests.swift}</include>
</includes>
+          <parallel>all</parallel>
+          <useUnlimitedThreads>true</useUnlimitedThreads>
</configuration>
</plugin>
<plugin>
```

[Go] Make BaseGoTest::initializeRuntime static

---

runtime/Go/antlr/utils.go
runtime/Go/antlr/utils_test.go

I originally missed the case where `set.data` was small than `b.data`, which would lead to a panic. This resolves that.

[Go] Fix BitSet OR operation

---

runtime/Cpp/runtime/src/ANTLRFileStream.cpp
runtime/Cpp/runtime/src/CommonToken.cpp
runtime/Cpp/runtime/src/DefaultErrorStrategy.cpp
runtime/Cpp/runtime/src/Lexer.cpp
runtime/Cpp/runtime/src/RecognitionException.cpp
runtime/Cpp/runtime/src/Recognizer.cpp
runtime/Cpp/runtime/src/antlr4-runtime.h
runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp
runtime/Cpp/runtime/src/support/StringUtils.cpp
runtime/Cpp/runtime/src/support/StringUtils.h
runtime/Cpp/runtime/src/tree/pattern/ParseTreePatternMatcher.cpp

`replaceAll` is the only function left and its usage is inefficient as its only use case is escaping whitespace. The current usage involves scanning the string 3 times. If any whitespace is actually encountered it updates the string in place, which is terribly slow as std::string is effectively just std::vector with an additional bookkeeping for the null terminator. So updating in place can involve may may memory moves and re-allocations. If there its lots of whitespace to escape, its performance is unacceptable.
Instead an optimal implementation which has a bounded worse case is written inline at its 3 call locations and StringUtils has been removed.

[C++] Improve whitespace escaping

---

tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
tool/src/org/antlr/v4/automata/CharactersDataCheckStatus.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java
tool/src/org/antlr/v4/automata/RangeBorderCharactersData.java

I've tested our case insensitive grammars-v4 repository with enabled new option and have found some errors that are fixed by the current PR:
* Enable `RANGE_PROBABLY_CONTAINS_NOT_IMPLIED_CHARACTERS` only for ASCII characters because there is probably not fully correct behavior with Unicode ranges. Anyway, I still think it's a useful warning, there are even questions on StackOverflow about `[A-z]` range: [Difference between regex [A-z] and [a-zA-Z]](https://stackoverflow.com/q/4923380/1046374), [[A-z0-9]+ regexp matching square brackets [duplicate]](https://stackoverflow.com/q/28449927/1046374)
* Convert range with `caseInsensitive` option if only UPPER range length equals to lower range length
* Improve location for warnings
* Remove some duplicated warnings

Fix case insensitive option with unicode, RANGE_PROBABLY_CONTAINS_NOT_IMPLIED_CHARACTERS fixes

---

runtime/Swift/Sources/Antlr4/Lexer.swift
runtime/Swift/Sources/Antlr4/RecognitionException.swift
runtime/Swift/Sources/Antlr4/Recognizer.swift
runtime/Swift/Sources/Antlr4/RuleContext.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfig.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfigSet.swift
runtime/Swift/Sources/Antlr4/atn/LL1Analyzer.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/dfa/DFAState.swift

changes SUPPRESS_PRECEDENCE_FILTER to be a static (type) variable, not an instance variable.

[Swift] Use proper constants

---

.circleci/scripts/run-tests-cpp.sh
.circleci/scripts/run-tests-dart.sh
.circleci/scripts/run-tests-swift.sh
tool/src/org/antlr/v4/codegen/Target.java
tool/src/org/antlr/v4/codegen/target/CppTarget.java
tool/src/org/antlr/v4/codegen/target/DartTarget.java
tool/src/org/antlr/v4/codegen/target/GoTarget.java
tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java
tool/src/org/antlr/v4/codegen/target/Python3Target.java
tool/src/org/antlr/v4/codegen/target/SwiftTarget.java

@ericvergnaud @KvanTTT How does this look? Tests appear to pass locally.

normalize targets to 80 char strings for ATN serialization segments.

---

runtime/Go/antlr/dfa.go

A shared mutex is kind of heavyweight when we are essentially replicating `volatile` from Java which is ultimately an atomic load/store. This change switches Go to use the equivalent, atomic.StorePointer and atomic.LoadPointer.

Use atomic instead of a shared mutex for DFA.s0

---

doc/lexer-rules.md
doc/options.md
tool-testsuite/test/org/antlr/v4/test/tool/TestATNLexerInterpreter.java
tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
tool/src/org/antlr/v4/automata/LexerATNFactory.java
tool/src/org/antlr/v4/parse/ANTLRLexer.g
tool/src/org/antlr/v4/parse/ANTLRParser.g
tool/src/org/antlr/v4/parse/GrammarTreeVisitor.g
tool/src/org/antlr/v4/semantics/BasicSemanticChecks.java
tool/src/org/antlr/v4/semantics/RuleCollector.java
tool/src/org/antlr/v4/semantics/SemanticPipeline.java
tool/src/org/antlr/v4/semantics/SymbolCollector.java
tool/src/org/antlr/v4/tool/ErrorType.java
tool/src/org/antlr/v4/tool/Grammar.java
tool/src/org/antlr/v4/tool/GrammarTransformPipeline.java
tool/src/org/antlr/v4/tool/Rule.java

It was quite simple to implement, but it should be merged after #3435

caseInsensitive lexer rule option

---

runtime/Cpp/README.md

Corrected/clarified the Linux C++ runtime compilation instructions WRT how to frobnicate the "cmake" command.

Corrected/clarified the Linux C++ runtime compilation instructions

---

runtime/Swift/Sources/Antlr4/ANTLRErrorListener.swift
runtime/Swift/Sources/Antlr4/IntStream.swift
runtime/Swift/Sources/Antlr4/Token.swift
runtime/Swift/Sources/Antlr4/TokenSource.swift
runtime/Swift/Sources/Antlr4/tree/ParseTreeListener.swift
runtime/Swift/Sources/Antlr4/tree/Tree.swift

**Problem**
Using the latest Swift to build Swift runtime will emit warnings about `class` keyword
which is deprecated.
```
warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
```
**Solution**
Use `AnyObject` instead.

Use `AnyObject` instead of `class`.

---

.appveyor/workflow.yml
.circleci/config.yml
.github/workflows/macosx.yml
antlr4-maven-plugin/pom.xml
pom.xml
runtime-testsuite/pom.xml
runtime/Java/pom.xml

use src 11 for tool, but 8 for plugin/runtime

---

contributors.txt
runtime/Cpp/runtime/CMakeLists.txt

This installs DLLs in bin directory instead of lib.

cpp/cmake: Fix library install directories

---

doc/java-target.md
runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
runtime/Java/pom.xml
tool/pom.xml

* tweak doc for 1.8 runtime.  Test rig should gen 1.8 not 1.7
* no need for plugin in runtime, always gen svg from dot for javadoc, gen 1.8 not 1.7 doc for runtime. Gen 11 for tool.

Update javadoc to 8 and 11

---

runtime/Go/antlr/utils.go
runtime/Go/antlr/utils_test.go

Currently code assumes slices have the same length for equivalence. This is incorrect, as its possible for one BitSet to have trailing zeros and another to have the best fit. So we should only be comparing set bits and ignoring trailing zeros.

[Go] Fix (*BitSet).equals

---

tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

These variables are unused and can cause static analyzers to complain, specifically Dart when it is opinionated.

Remove unused variable from generated code

---

runtime/Cpp/runtime/src/UnbufferedCharStream.cpp
runtime/Cpp/runtime/src/UnbufferedCharStream.h

As the name says, fix bugs in UnbufferedCharStream pointed out by #3412. I also cleaned up the class while I was there.

[C++] Fix bugs in UnbufferedCharStream

---

runtime/CSharp/src/Antlr4.csproj

fix warnings in C# CI

---

.github/workflows/windows.yml

Improve CI concurrency

---

.github/scripts-windows/run-tests-csharp.cmd
.github/scripts-windows/run-tests-dart.cmd
.github/scripts-windows/run-tests-go.cmd
.github/scripts-windows/run-tests-java.cmd
.github/scripts-windows/run-tests-javascript.cmd
.github/scripts-windows/run-tests-php.cmd
.github/scripts-windows/run-tests-python2.cmd
.github/scripts-windows/run-tests-python3.cmd
.github/workflows/windows.yml

fix-maven-concurrency

---

.github/scripts-windows/run-tests-csharp.cmd
.github/scripts-windows/run-tests-go.cmd
.github/scripts-windows/run-tests-java.cmd
.github/scripts-windows/run-tests-javascript.cmd
.github/scripts-windows/run-tests-php.cmd
.github/scripts-windows/run-tests-python2.cmd
.github/scripts-windows/run-tests-python3.cmd

increase Windows CI concurrency for all targets except Dart

---

runtime/Cpp/runtime/src/antlr4-common.h
runtime/Cpp/runtime/src/misc/MurmurHash.cpp
runtime/Cpp/runtime/src/support/Guid.cpp
runtime/Cpp/runtime/src/support/Guid.h

Set `WIN32_LEAN_AND_MEAN` and `NOMINMAX` when including a Windows API related header in `support/Guid.cpp`. This resolves #3489. Additionally I updated the macros to be prefixed with `ANTLR4CPP_` which is best practice for public headers.

[C++] Fix Windows min/max macro collision

---

runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTestSupport.java
runtime-testsuite/test/org/antlr/v4/test/runtime/java/TestInterpreterDataReader.java
runtime/Java/src/org/antlr/v4/runtime/VocabularyImpl.java
tool/src/org/antlr/v4/Tool.java

Also includes separating the generation of the .interp file from writing it out so that we can use both independently.
Still working on the Python part.

Fix .interp file parsing test for the Java runtime.

---

runtime/Cpp/runtime/src/atn/LexerActionExecutor.h
runtime/Cpp/runtime/src/atn/PredictionContext.cpp
runtime/Cpp/runtime/src/atn/PredictionContext.h

Fix broken compilation due to missing virtual destructors on `LexerActionExecutor` and `PredictionContext`. I removed the former previously thinking `std::enable_shared_from_this` was virtual itself, but apparently its not. `PredictionContext` was never virtual and it should have been.

[C++] Fix missing virtual destructors

---

runtime/Cpp/runtime/src/Parser.cpp
runtime/Cpp/runtime/src/atn/LexerATNSimulator.cpp
runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp

Various small improvements.
- Improve multithreaded performance by using `insert` instead of `find` then `insert`. This reduces the amount of time spent in critical sections. 
- Fix extremely rare race condition that I introduced as I unlocked then dereferenced an iterator.
- Fix parser profiling setup. Currently calling `setProfile` more than once would crash in debug builds.

[C++] Improve multithreaded performance, fix TSAN error, and fix profiling ATN simulator setup

---

runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/atn/ATNDeserializer.swift
runtime/Swift/Sources/Antlr4/misc/InterpreterDataReader.swift
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
tool/src/org/antlr/v4/codegen/Target.java
tool/src/org/antlr/v4/codegen/model/SerializedATN.java
tool/src/org/antlr/v4/codegen/target/CSharpTarget.java
tool/src/org/antlr/v4/codegen/target/CppTarget.java
tool/src/org/antlr/v4/codegen/target/DartTarget.java
tool/src/org/antlr/v4/codegen/target/GoTarget.java
tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java
tool/src/org/antlr/v4/codegen/target/JavaTarget.java
tool/src/org/antlr/v4/codegen/target/PHPTarget.java
tool/src/org/antlr/v4/codegen/target/Python2Target.java
tool/src/org/antlr/v4/codegen/target/Python3Target.java
tool/src/org/antlr/v4/codegen/target/SwiftTarget.java

Using plain chars for serialized ATN data instead of escaped where it's possible. Fixed the bug with the max size of ATN segment introduced in https://github.com/antlr/antlr4/pull/3438.
I've compared the size of source files for [`largeLexer`](https://github.com/antlr/antlr4/blob/master/runtime-testsuite/test/org/antlr/v4/test/runtime/GeneratedLexerDescriptors.java#L42) test:
| Language   | Before (KB) | After (KB) | Comment                             |
| ---------- | ------ | ----- | ----------------------------------- |
| Java       | 1331   | 902   |                                     |
| C#         | 2713   | 1997  |                                     |
| Dart       | 2582   | 1468  | + Fixed max ATN segment               |
| JavaScript | 2148   | 1702  | …

Optimize ATN serialization data

---

runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp
runtime/Cpp/runtime/src/atn/ATNDeserializer.h
runtime/Cpp/runtime/src/atn/ATNSimulator.cpp
runtime/Cpp/runtime/src/atn/ATNSimulator.h

Simple cleanup of `ATNDeserializer` that removes virtual methods, since they cannot really be overridden anyway, moves private methods to the source file, and removes related deprecated methods from ATNSimulator since nobody should be using those.

[C++] Cleanup ATNDeserializer and remove related deprecated methods from ATNSimulator

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Cpp.test.stg
runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp
runtime/Cpp/runtime/src/tree/xpath/XPathLexer.h
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

Currently ATN is deserialized during program initialization before `main` is invoked. This has a cost that all programs must pay regardless of whether the lexer/parser is even used. This change shifts initialize to be just-in-time using `std::once_flag` and `std::call_once`. This additionally resolves concerns around potential future issues with regards to static initialization order. Static initialization order between separate compliation units is undefined in C++. By switching to `std::once_flag` which has constant initialization, we avoid the problem entirely.

[C++] Lazily deserialize ATN in generated code

---

runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

I realized that generated names are difficult to read without `_` separating the parser/lexer name and the variable name. In example, `XPathLexerstaticData` looks awfully like `XPathLexerStaticData`. While `XPathLexer_staticData` is distinctly different from `XPathLexerStaticData`. While this deviates from the style overall, it is significantly more readable for generated code and makes it clear that `XPathLexer_staticData` is related to `XPathLexer`.

[C++] Switch to camel case for generated static data variable names

---

runtime/JavaScript/src/antlr4/atn/ATNDeserializer.js
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java

@KvanTTT @ericvergnaud @jcking And now JavaScript uses an int array not a string! woot!  Soon we will worry less about large ATN.

JavaScript: Change string to int array for serialized ATN

---

contributors.txt
runtime/Go/antlr/tree.go

Reference: https://github.com/antlr/antlr4/blob/ad29539cd2e94b2599e0281515f6cbb420d29f38/runtime/Java/src/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.java#L18

perf: Add default implementation for Visit in ParseTreeVisitor. 

---

runtime/Go/antlr/atn_deserializer.go

Don't decode utf16 in ATN deserialization for Go; it's just a bunch of uint16

---

runtime/Go/antlr/atn_deserialization_options.go
runtime/Go/antlr/atn_deserializer.go

Updates `ATNDeserializationOptions`, makes some things private, fixes ATN deserialization, and enables verification by default.
Currently ATN deserialization is incorrect, but it is not clear what the incorrect behavior would surface as.

[Go] Cleanup and fix ATN deserialization verification

---

tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
tool/src/org/antlr/v4/codegen/target/PHPTarget.java

Fix PHP codegen to support int ATN serialization.
Complements https://github.com/antlr/antlr-php-runtime/pull/23.

Fix PHP codegen to support int ATN serialization

---

runtime/CSharp/src/Atn/LexerATNSimulator.cs
runtime/Cpp/runtime/src/atn/LexerATNSimulator.cpp
runtime/Cpp/runtime/src/atn/LexerATNSimulator.h
runtime/JavaScript/src/antlr4/atn/LexerATNSimulator.js
runtime/Python2/src/antlr4/atn/LexerATNSimulator.py
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift

The variable appears to be unused and atomic operations are not exactly free.

[C++] Remove unused LexerATNSimulator::match_calls

---

runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java

Java is a bit special in that it is the only language where it is normal for pre-compiled code to be distributed. This makes it difficult to hard cut to a new serialized ATN version. There are a bunch of libraries which break unexpectedly, including some Android libraries. This patch preserves backwards compatibility for ATN serialized version 3, by simply skipping the UUID and assuming all features were supported.

[Java] Preserve serialized ATN version 3 compatibility

---

runtime/Cpp/runtime/src/atn/LexerATNSimulator.cpp
runtime/Cpp/runtime/src/atn/LexerATNSimulator.h
runtime/Cpp/runtime/src/dfa/DFAState.h
runtime/Cpp/runtime/src/support/CPPUtils.h
runtime/Cpp/runtime/src/support/StringUtils.h
runtime/Cpp/runtime/src/support/Unicode.h
runtime/Cpp/runtime/src/support/Utf8.h

As the name suggests, add `ANTLR4CPP_PUBLIC` to various symbols. I additionally cleaned up `SimState` while I was there, as it cannot be virtual since it is used by value as a member. So using a struct is more simple.
Addresses #3577

[C++] Add ANTLR4CPP_PUBLIC attributes to various symbols

---

.editorconfig
contributors.txt

Make it easier to contribute: Add c++ configuration for .editorconfig.
Using the observed style with 2 indentation spaces.
Also adding myself to contributors.txt (both `h.zeller@acm.org` or `hzeller@google.com` would work; choosing one of them)

Update editorconfig for c++

---

tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg

Fix code style and typing to support PHP 8.

Fix code style and typing to support PHP 8

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime/Go/antlr/atn.go
runtime/Go/antlr/atn_state.go
runtime/Go/antlr/dfa.go
runtime/Go/antlr/dfa_state.go
runtime/Go/antlr/lexer_atn_simulator.go
runtime/Go/antlr/parser_atn_simulator.go
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

Ports C++ locking algorithm and lazy ATN deserialization to Go, enabling construction of parsers and lexers to be cheap as the ATN is now deserialized at most once when needed.

[Go] Port locking algorithm from C++ to Go

---

runtime/Cpp/runtime/src/atn/SemanticContext.cpp
runtime/Cpp/runtime/src/atn/SemanticContext.h

This fixes 2 flaws in filterPrecedencePredicates that @parrt and I found in the C++ implementation.
- While filtering precedence predicates Java removes the precedence predicates from the set while C++ does not. This change fixes this by filtering out precedence predicates during iteration and adding the min or max after.
- Equality of and/or is undefined currently, as std::unordered_set makes no guarantees on iteration order. So two identical sets could iterate differently, resulting in two separate and/or semantic contexts being different when they should be equal. This change fixes this by preserving insertion order, making it well defined.

[C++] Fix bugs in SemanticContext

---

runtime/Go/antlr/atn_config_set.go
runtime/Go/antlr/dfa_state.go
runtime/Go/antlr/ll1_analyzer.go
runtime/Go/antlr/parser_atn_simulator.go
runtime/Go/antlr/semantic_context.go
runtime/Go/antlr/utils_set.go

`Array2DHashSet` is an implementation detail that is not directly exposed by any other interfaces or structures. It should be considered an implementation detail and not exported.

[Go] Do not export Array2DHashSet which is an implementation detail

---

runtime/Swift/Sources/Antlr4/atn/ATNConfig.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNConfig.swift
runtime/Swift/Sources/Antlr4/atn/SingletonPredictionContext.swift
runtime/Swift/Sources/Antlr4/tree/pattern/Chunk.swift

NFC, except for fixing reflexivity for pattern/Chunk

[Swift] improvements to equality functions

---

runtime/Swift/Sources/Antlr4/CommonTokenStream.swift
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/atn/ATNConfigSet.swift
runtime/Swift/Sources/Antlr4/atn/ArrayPredictionContext.swift
runtime/Swift/Sources/Antlr4/atn/ParseInfo.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/PredictionContext.swift

[Swift] Use for in loops

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

If a lowercase grammar name is used, the functions will collide. This change ensures they do not by enforcing capitalization when necessary.

[Go] Fix symbol collision in generated lexers and parsers

---

runtime/Cpp/runtime/src/atn/ATNConfigSet.h
runtime/Cpp/runtime/src/atn/ATNSimulator.cpp
runtime/Cpp/runtime/src/atn/ATNSimulator.h
runtime/Cpp/runtime/src/atn/ArrayPredictionContext.cpp
runtime/Cpp/runtime/src/atn/ArrayPredictionContext.h
runtime/Cpp/runtime/src/atn/PredictionContext.cpp
runtime/Cpp/runtime/src/atn/PredictionContext.h
runtime/Cpp/runtime/src/atn/PredictionMode.cpp
runtime/Cpp/runtime/src/atn/PredictionMode.h
runtime/Cpp/runtime/src/atn/SemanticContext.h
runtime/Cpp/runtime/src/atn/SingletonPredictionContext.cpp
runtime/Cpp/runtime/src/atn/SingletonPredictionContext.h
runtime/Cpp/runtime/src/misc/IntervalSet.cpp

Refactor PredictionContext, remove some `dynamic_cast`, and avoid copying `std::shared_ptr` when possible

[C++] Refactor PredictionContext and yet more performance improvements

---

runtime/Swift/Sources/Antlr4/BufferedTokenStream.swift
runtime/Swift/Sources/Antlr4/DiagnosticErrorListener.swift
runtime/Swift/Sources/Antlr4/atn/ATN.swift
runtime/Swift/Sources/Antlr4/atn/SemanticContext.swift
runtime/Swift/Sources/Antlr4/misc/BitSet.swift
runtime/Swift/Sources/Antlr4/misc/IntervalSet.swift
runtime/Swift/Sources/Antlr4/misc/Utils.swift
runtime/Swift/Sources/Antlr4/misc/utils/CommonUtil.swift
runtime/Swift/Sources/Antlr4/tree/Trees.swift

The first commit requires a minimum Swift version of Swift 5

[Swift] use stdlib (single pass)

---

runtime/Swift/Sources/Antlr4/BufferedTokenStream.swift
runtime/Swift/Sources/Antlr4/FailedPredicateException.swift
runtime/Swift/Sources/Antlr4/LexerInterpreter.swift
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/atn/LexerATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/LexerActionExecutor.swift
runtime/Swift/Sources/Antlr4/atn/PredictionContext.swift
runtime/Swift/Sources/Antlr4/atn/SingletonPredictionContext.swift
runtime/Swift/Sources/Antlr4/misc/DoubleKeyMap.swift
runtime/Swift/Sources/Antlr4/misc/MurmurHash.swift
runtime/Swift/Sources/Antlr4/tree/Trees.swift
runtime/Swift/Sources/Antlr4/tree/pattern/ParseTreeMatch.swift
runtime/Swift/Sources/Antlr4/tree/pattern/ParseTreePatternMatcher.swift
runtime/Swift/Sources/Antlr4/tree/pattern/TokenTagToken.swift

[Swift] more improved optional handling

---

runtime/Cpp/cmake/README.md

Included specific examples of using ANTLR4_TAG and ANTLR4_ZIP_REPOSITORY in the sample CMakeLists file.

Updated getting started with Cpp documentation.

---

runtime/Cpp/runtime/src/atn/ATNConfigSet.cpp
runtime/Cpp/runtime/src/atn/ATNConfigSet.h

Currently the underlying storage lives on as only `clear` is used. To actually free the underlying storage we have to perform a swap. The original intent was to free the storage when the config becomes readonly as its going to live on for a long time in the DFA cache.

[C++] Free ATNConfig lookup set in readonly ATNConfigSet

---

runtime/Cpp/runtime/CMakeLists.txt

The new option to cmake ANTLR_BUILD_CPP_TESTS is default
on (so the behavior is as before), but it provides a way to
switch off if not needed.
The C++ tests pull in an external dependency (googletests),
which might conflict if ANTLR is used as a subproject in
another cmake project.
Signed-off-by: Henner Zeller <h.zeller@acm.org>

Allow to switch off building C++ tests, needed if used as sub-project

---

runtime/Swift/Sources/Antlr4/misc/Interval.swift
runtime/Swift/Sources/Antlr4/misc/IntervalSet.swift

Interval was a pointer to 2 Ints
it ought to be just 2 Ints, which is smaller and more semantically correct,
with no need for a cache.
However, this breaks AnyObject conformance and changes type metadata but people shouldn't be relying on those for an Interval.

[Swift] An interval ought to be a value

---

runtime/Cpp/runtime/src/DefaultErrorStrategy.cpp
runtime/Cpp/runtime/src/Parser.cpp
runtime/Cpp/runtime/src/ParserInterpreter.cpp
runtime/Cpp/runtime/src/ParserRuleContext.cpp
runtime/Cpp/runtime/src/atn/ParserATNSimulator.cpp
runtime/Cpp/runtime/src/dfa/DFA.cpp

[C++] Remove more dynamic_cast usage

---

runtime/Swift/Sources/Antlr4/BufferedTokenStream.swift
runtime/Swift/Sources/Antlr4/Parser.swift
runtime/Swift/Sources/Antlr4/ParserRuleContext.swift
runtime/Swift/Sources/Antlr4/TokenStream.swift
runtime/Swift/Sources/Antlr4/UnbufferedTokenStream.swift
runtime/Swift/Sources/Antlr4/atn/ATN.swift
runtime/Swift/Sources/Antlr4/atn/AtomTransition.swift
runtime/Swift/Sources/Antlr4/atn/ParserATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift
runtime/Swift/Sources/Antlr4/atn/RangeTransition.swift
runtime/Swift/Sources/Antlr4/atn/SetTransition.swift
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

This PR modifies public API and has several questions:
should `ParserRuleContext.removeLastChild` require it be not empty?
I think the change to `Parser._parseListeners` requires changes to code templates, but I couldn't get them to apply in local testing.

[Swift] reduce Optionals in APIs

---

runtime/Cpp/runtime/src/ANTLRFileStream.cpp

[C++] Remove reference to antlrcpp:s2ws

---

runtime/Cpp/runtime/src/ANTLRFileStream.cpp

[C++] Remove reference to antlrcpp:s2ws (#3656)

---

runtime/Java/pom.xml

The 4.10.0 runtime of antlr correctly sets the `source` and `target` to 1.8, however, the compiler is still compiling against the Java 11 runtime classpath. This results in the runtime using a different method signature for `java.nio.CharBuffer.flip()`
This manifests as the following error when using antlr in a java8-based project: 
```
Caused by:
java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
```
This PR sets the release (used by the maven compiler plugin) to 8, thus forcing it to use the java 8 runtime when compiling.

Fix build to set the release to Java 8

---

doc/dart-target.md
doc/releasing-antlr.md

Dart `pub` tool got integrated in the `dart` CLI now. Updating the instruction.

Update publishing instruction for Dart

---

runtime/Cpp/CMakeLists.txt
runtime/Cpp/CMakeSettings.json
runtime/Cpp/runtime/CMakeLists.txt
runtime/Cpp/runtime/src/misc/MurmurHash.cpp

Modernize CMakeLists.txt and a few Windows specific fixes
* Upgraded to minimum version 3.15 (was 3.14)
* Use CMAKE_MSVC_RUNTIME_LIBRARY to configure CRT
* Use target_compile_definitions to configure definitions so they can selectively be propagated upward (ANTLR4CPP_EXPORTS & ANTLR4CPP_STATIC needed to be propagated upwards)
* Handle CRT requirement for test correctly (gtest configuration should depend on WITH_STATIC_CRT)
* Don't change the default CMake output directory. With multiple configurations CMake doesn't trigger a build when the configuration is switched resulting in link errors (debug linking against release or vice-versa).
* Rename the static pdb file the same as the library (this was a conflict with both static and shared attempting to write to the same pdb file)
* Fixed x86 …

Modernize CMakeLists.txt and a few Windows specific fixes

---

runtime/Python3/setup.py

Python3 runtime's setup.py introduces the use of an f-string which needlessly breaks compatibility with Python3.5 (#3650)
Remove the use of an f-string to restore ability to use runtime in python3.5

Restore support for py3.5 by removing f-string in setup.py

---

runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake

Two small improvements to the CMake file used to setup the cpp runtime
as an externa project in cmake.
The first commit just silences a warning in newer cmake versions, whereas the latter
ensures that a user does not have to take care of setting up the correct include directories
themselves. Linking to either `antl4_static`  or `antlr4_shared` will now automatically
populate the include directories of the target these are linked to.

Improve ExternalProject cmake file

---

runtime/Go/antlr/testing_lexer_b_test.go
runtime/Go/antlr/tokenstream_rewriter_test.go

Regenerate the codegen and ATN content for test-related `LexerA` and `LexerB`, so that `go test` will execute successfully.
Similar issue to https://github.com/antlr/antlr4/issues/3557

Fix golang tests by regenerating test lexers

---

runtime/Go/antlr/common_token_stream.go
runtime/Go/antlr/common_token_stream_test.go
runtime/Java/src/org/antlr/v4/runtime/BufferedTokenStream.java

Update the Go and Java runtimes to match the C++ runtime for syncing to only the tokens needed
to read the text from the supplied interval. 
The `fill()` methods search for EOF as a signal to conclude the token syncing; however, when there
is an errant input, EOF may be missing and this can result in `fill()` re-reading the entire token stream
for each error encountered in the input. As such `fill()` has been replaced with `sync()` calls which
provide equivalent functionality.
Signed-off-by: Tristan Swadell <tswadell@google.com>

Ensure that only the tokens needed are fetched

---

tool/src/org/antlr/v4/gui/Interpreter.java
tool/src/org/antlr/v4/gui/Intrepreter.java

An interpreted version of TestRig, which only ran Java-based (and compiled) parser/lexers.  This uses java-based interp to process any grammar (ignoring actions of course).
Needed by new tools: https://github.com/antlr/antlr4-tools
```
$ java org.antlr.v4.gui.Interpreter \
/Users/parrt/sample/TParser.g4 \
/Users/parrt/sample/TLexer.g4 \
expr -profile /tmp/T-profile.csv -tokens /tmp/foo.txt
```
```
$ java org.antlr.v4.gui.Interpreter /Users/parrt/sample/JSON.g4 json -profile /tmp/json.csv /tmp/foo.json
Rule,Invocations,Time,Total k,Max k,Ambiguities,DFA cache miss
obj:0,2,0.030417,2,1,0,2
obj:1,1,1.317417,2,2,0,2
arr:2,3,0.034917,3,1,0,2
arr:3,1,0.101917,2,2,0,2
value:4,6,0.341458,6,1,0,3
```
@kaby76 @KvanTTT @hzeller @mike-lischke @ericvergnaud might be interested.  Then I'll hook into …

Add interp tool like TestRig

---

LICENSE.txt
THIRD-PARTY-NOTICES.txt
pom.xml

* Adjust the text of of the BSD license so that it is now recognised as  BSD-3-Clause license  by GitHub auto-detection.  
* Move MIT license from LICENSE.txt to THIRD-PARTY-NOTICES.txt & attribute correctly,  This fixes #1952
* Update copyright year in LICENSE.txt to include current year 2022
* Update license name in project POM to `BSD-3-Clause` (Official SPDX short identifier for the license).  This helps ensure that downstream SCA tooling can correctly identify the license.
* Update URLs in project POM to use https, where https is used.

Update License Files to Help Autodetection

---

doc/getting-started.md

Signed-off-by: nicksxs <nicksxs@hotmail.com>

update getting-started doc

---

runtime/Java/pom.xml

org.antlr.v4.gui is only used for backwards compatibility, but the
manifest generated by upgraded maven-bundle-plugin generates an
Import-Package requirement. This breaks the ability to load
antlr4-runtime in an OSGi enviroment, when nothing provides
org.antlr.v4.gui.
Fix this by specifying resultion as optional.
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

Fix OSGi imports

---

docker/README.md

Fixes: #3688
The jdk image used in the Dockerfile does not support arm, so it may be necessary to specify the platform.
https://hub.docker.com/r/adoptopenjdk/openjdk11/tags
It would be better to fix the README.

Fix Docker README for arm OS user

---

runtime/Cpp/CMakeLists.txt
runtime/Cpp/cmake/ExternalAntlr4Cpp.cmake

When adding ANTLR as an external project, the downstream users will
(generally) not be interested in compiler warnings emitted for ANTLR
itself, as they won't be able to do anything about them anyway (in their
project).
Thus, this commit adds a new cmake option DISABLE_WARNINGS that can be
used to suppress compiler warnings. This flag is then subsequently set
whenever ANTLR is used as an ExternalProject.

Cpp: Disable warnings for external project

---

tool-testsuite/test/org/antlr/v4/test/tool/TestCompositeGrammars.java
tool/src/org/antlr/v4/tool/Grammar.java

Fix circular grammar import stack overflow

---

runtime/Cpp/runtime/src/atn/SemanticContext.h

Don't make class SementicContext::Empty final.
The class does not implement the pure virtual methods so can
not be considered 'final'. Clang 10 and 11 complain about this.
Context: https://github.com/chipsalliance/Surelog/issues/3081

Don't make class SementicContext::Empty final.

---

.github/workflows/hosted.yml

Issue #3783: CI Check Builds
Adding workflow for Github hosted CI check builds. Supports all three
supported platforms with all runtime languages except swift.
Also, includes cpp native builds across all supported platforms i.e.
independent on the test run builds.
Every configuration build generates an artifact (archive of the entire
repository) and is uploaded as a result of the build (regardless of
success or failure).

Issue #3783: CI Check Builds

---

.github/workflows/hosted.yml

Include swift & tool verification in CI workflow
* Adding CI for swift runtime
* Adding CI for tool verification (for java runtime target only)
* Also fixed a few minor issues identified in change #3785 
This change is a follow up to #3785.
Known Issue: There seems to be some sort of timeout issue with setting up Maven using Apache. It is reported here - https://github.com/stCarolas/setup-maven/issues/16
Attn: @KvanTTT @parrt

Include swift & tool verification in CI workflow

---

doc/actions.md
doc/python-target.md

Since I had to work all this out too, and found @kaby76's description in #3508 so helpful, I made an attempt at closing it out.

Fix #3508: Document the $parser attribute and its use in target-agnostic grammars.

---

runtime/Go/antlr/interval_set.go

Signed-off-by: James Taylor <jamestaylor@apache.org>
Unlike the Java version, in the Go-based version of interval_sets, there's no way to access the IntervalSets.intervals field. This field is useful when using Parser.getExpectedTokens(). The alternative is to use IntervalSets#StringVerbose and parse the string returned (which is much more expensive).

Add Go accessor for IntervalSet.intervals

---

tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

Without this suppression, the https://errorprone.info/ lib complains about ANTLR code.
Signed-off-by: Terence Parr <parrt@antlr.org>

Add `@SuppressWarnings("CheckReturnValue")` to prevent error_prone lib errors.

---

runtime/Python2/setup.py

Signed-off-by: Travis Thieman <travis.thieman@gmail.com>
Follow-up from https://github.com/antlr/antlr4/pull/3662. Fixes the F string syntax error in the Python 2 `setup.py` file. This should make the Python 2 runtime installable again from Python 2 pip.

[py2] Fix SyntaxError due to F string

---

.github/workflows/hosted.yml

Add caching support for maven & dependencies. Also, include caching for
cpp builds using actions/ccache.
Builds are more reliable (avoids the archive.apache server which
intermittently reports timeouts) and also significantly improves the
overall builds times (down from 46 mins to 28 mins).
The slowest part of the build now is the Windows+cpp builds because
there is no reliable cache implementation yet. MacOS+cpp (65% cache hit) is
also relatively slow compared to Ubuntu+cpp (99% cache hit).

Caching support

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.go.stg
runtime-testsuite/test/org/antlr/v4/test/runtime/go/GoRunner.java
runtime/Go/antlr/atn_config.go
runtime/Go/antlr/atn_config_set.go
runtime/Go/antlr/dfa.go
runtime/Go/antlr/dfa_state.go
runtime/Go/antlr/go.mod
runtime/Go/antlr/jcollect.go
runtime/Go/antlr/jcollect_test.go
runtime/Go/antlr/lexer_atn_simulator.go
runtime/Go/antlr/parser.go
runtime/Go/antlr/parser_atn_simulator.go
runtime/Go/antlr/prediction_context.go
runtime/Go/antlr/prediction_mode.go
runtime/Go/antlr/utils.go
runtime/Java/src/org/antlr/v4/runtime/atn/ATNConfigSet.java

fix: #3718 Implement generic collections and fiux LA(*) optimizer
o Implements collections using generics to solve has conflicts in previous implementation of
DFAState collections and alt conflict resolution
o Change alt and config to use correct hash and equals as per Java
o Fix LA()*) runtime optimization routine
o A few tidy ups on comments etc
NB: There are now extra hash() and equals() routines that I had to leave there unless I wanted to go through
all the code and rationalize and refactor. Not worth it if we are going to rewrite. The generic collections work for this
purpose but the make up of the currents structs etc, forces a few hacks that won't be needed with better structure.
Sending this PR without tests for the collections as:
o they can't be worse than what is there, that …

fix: Fixes for https://github.com/antlr/antlr4/issues/3718

---

.github/workflows/hosted.yml

Issue #3823: Temporarily disable a few tests on CI
The tests are currently failing. The underlying issues have been fixed
on dev and so the builds will be turned back with the next release.

Issue #3823: Temporarily disable a few tests on CI

---

runtime/Go/antlr/jcollect.go

- Many small collections are created at runtime, the default allocation for
maps, even though small, still requires memory. Specifying a very small
initial allocation prevents unnecesary allocations and has no measurable
effect on performance. A small incremental change.
Signed-off-by: Jim.Idle <jimi@gatherstars.com>

feat: Reduce initial memory allocations for collections

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

fix: Replacement for PR #3101 fixes #2826
Correct code generation template for dynamic scope

fix: #2826  Go template is incorrect for dynamic scopes

---

antlr4-maven-plugin/pom.xml
pom.xml
runtime-testsuite/pom.xml
runtime/Java/pom.xml
tool-testsuite/pom.xml
tool/pom.xml

Move to new version numbers as Go target has had significant changes and needs a new minor version

feat: Bump poms to use 4.11 Snapshot

---

doc/grammars.md
doc/lexer-rules.md
doc/lexicon.md
doc/parser-rules.md
doc/wildcard.md

This seems to be all the affected locations. I left smart-quotes alone in prose like `Here’s`.
Looks like my editor added a trailing newline on files that were missing one. I can back that out, but it's probably for the best. :-)

Replace smart-quote with single-quote in code examples

---

doc/getting-started.md

The URL to the download page in the Windows installation instructions is incorrect and needs to be corrected.
Signed-off-by: GCer-Hidenori <gcer.hidenori+github@gmail.com>

fix URL to download page.

---

runtime-testsuite/test/org/antlr/v4/test/runtime/states/State.java

Cause of compile/link errors were hidden during tests; bad in C++ as can't see anything.

Augment error message during testing to include full cause of problem.

---

runtime/Cpp/cmake/antlr4-runtime.cmake.in
runtime/Cpp/runtime/CMakeLists.txt

As detailed in #3708, it is necessary to link against the (p)threads
library in order to be able to use std::call_once without producing
linker errors.
Since this function is frequently used in ANTLR's cpp version, this
commit ensures that the respective library is always linked against in
order to avoid this error, even if downstream users are not explicitly
linking against an appropriate threads library.
Fixes #3708

Cpp: Link to threads library

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelForClosureContext.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelsOnRuleRefStartOfAlt.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/CSharp.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/JavaScript.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python2.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
runtime-testsuite/test/org/antlr/v4/test/runtime/Processor.java
runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/CppRunner.java
runtime/Dart/lib/src/prediction_context.dart
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

Supercedes https://github.com/antlr/antlr4/pull/2022  Fixes #2016
@jimidle Go target fails this new test:
```
Test: ListLabelsOnRuleRefStartOfAlt; State: Execute; java.lang.InterruptedException: 
panic: interface conversion: antlr.PredictionContext is *antlr.EmptyPredictionContext, not *antlr.ArrayPredictionContext [recovered]
panic: interface conversion: antlr.PredictionContext is *antlr.EmptyPredictionContext, not *antlr.ArrayPredictionContext
goroutine 1 [running]:
test/parser.(*TestParser).expression.func2()
/private/var/folders/w1/_nr4stn13lq0rvjdkwh7q8cc0000gn/T/GoRunner-ForkJoinPool-1-worker-7-1661633249352/parser/test_parser.go:299 +0xfe
panic({0x10ed920, 0xc00007bc80})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/antlr/antlr4/runtime/Go/antlr.merge({0x113ebf0?, …
```

Fix 2016 round 2

---

runtime-testsuite/test/org/antlr/v4/test/runtime/CustomDescriptors.java
runtime/Swift/Sources/Antlr4/misc/Utils.swift
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
tool/src/org/antlr/v4/codegen/model/Choice.java
tool/src/org/antlr/v4/codegen/model/LL1Choice.java
tool/src/org/antlr/v4/codegen/model/TestSetInline.java
tool/src/org/antlr/v4/codegen/model/TokenInfo.java
tool/src/org/antlr/v4/codegen/target/GoTarget.java

@SimonStPeter I've created [a benchmark](https://github.com/KvanTTT/AntlrBenchmarks/blob/master/ConstantFoldingBenchmark/checkParsers.py) with respective grammar and have got the following result:
```
no_const_folding: 2010734 ns
const_folding: 907140 ns
ratio: 0.4511
```
I haven't tested on real grammars, but It's already signficant improvement, more 2x faster and it should be considered. Also, resulting file > 20 % less than the file with not folded constants.
There is no improvement in speed for JavaScript.
fixes #3698, fixes #3699
@parrt I suggest using constant folding for all runtimes because:
* It reduces the size of generated parsers (more than 20% as I've checked for Python and JavaScript)
* It eliminates very long lines that are hard to read by human and text editors. Just …

Constant folding for Python and other runtimes

---

runtime/Go/antlr/go.mod

feat: Add a deprecated message to the existing `v1` (default) module path to direct go module users to the latest `v4` path
Signed-off-by: Jim.Idle <jimi@gatherstars.com>

feat: Add a deprecation message to the existing v1 module

---

.gitignore
doc/releasing-antlr.md

Closes #3805 
I'm using Python 3.9. I tried `python setup.py sdist upload -r pypitest` but got
```
...
Writing antlr4-python3-runtime-4.10.1/setup.cfg
Creating tar archive
removing 'antlr4-python3-runtime-4.10.1' (and everything under it)
running upload
Submitting dist/antlr4-python3-runtime-4.10.1.tar.gz to https://test.pypi.org/legacy/
Upload failed (400): Invalid value for blake2_256_digest. Error: Use a valid, hex-encoded, BLAKE2 message digest.
error: Upload failed (400): Invalid value for blake2_256_digest. Error: Use a valid, hex-encoded, BLAKE2 message digest.
```
The [answer](https://bugs.python.org/issue45590) seems using `twine` instead, and from the [link](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary) there calling `setup.py` should be deprecated. …

[Python 3] use build and twine to publish source and wheel

---

runtime/Go/antlr/antlrdoc.go
runtime/Go/antlr/v4/prediction_context.go

I had not thought about this, but I guess some of the fix PRs were out of order and did not have one fix that was in the legacy version of the runtime, copied in to the v4 branch. This PR fixes that.
It is not worth doing yet another minor release as if anyone needs this exact fix, they can use the dev branch until the next release.
Signed-off-by: Jim.Idle <jimi@gatherstars.com>

fix: Restore missing changes to v4 of go runtime

---

Package.swift
doc/swift-target.md

Problem: https://github.com/antlr/antlr4/commit/c1b448f738dbc193977c5e17885640e6b1c10e13 introduced a regression to the https://github.com/antlr/antlr4/pull/3132, which allowed for ANTLR 4 library usage in Swift's Package Manager.
Solution: return `Package.swift` back to the project's root, so that other Swift projects can depend on ANTLR 4 just as described in the `swift-target.md`.

Bring back the Package.swift in the project's root

---

pom.xml
runtime/Java/pom.xml
tool/pom.xml

Signed-off-by: Hervé Boutemy <hboutemy@apache.org>
equivalent to https://github.com/antlr/antlr3/pull/210 that I did for ANTLR3
given ANTLR4 uses ANTLR3, to get a full reproducible build for ANTLR4, ANTLR3 version will require to be upgraded once https://github.com/antlr/antlr3/pull/209 has been merged and a release done

init Reproducible Builds

---

runtime/Cpp/README.md

Signed-off-by: 1sand0s <1sand0sardpi@gmail.com>
The constructor of `ANTLRInputStream` declared in `ANTLRInputStream.h`, uses `std::string_view` which is available only post `C++17` so the minimum required `CMAKE_CXX_STANDARD` to build the runtime library for `C++` targets would be 17.

Fixing minimum CXX standard required

---

doc/go-target.md
tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
tool/src/org/antlr/v4/codegen/model/decl/ContextGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextRuleGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextRuleListGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextRuleListIndexedGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextTokenGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextTokenListGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/ContextTokenListIndexedGetterDecl.java
tool/src/org/antlr/v4/codegen/model/decl/StructDecl.java

* #3926 
This is an attempt to remove the need to always cast these interfaces to concrete types. I considered two options:
1. Update accessors to return concrete types instead of interfaces
2. Add the missing method signatures to the existing interfaces
This PR implements option (2), as (1) would be a breaking change for existing applications. I believe (2) is backwards compatible.
The strategy here is to add a flag, `signature`, to each of the `ContextGetterDecl` subclasses so that each of their corresponding template definitions can conditionally generate a method signature (for the interface) versus the complete method declaration.
The `getSignatureDecl()` functions on each of the `ContextGetterDecl` subclasses are pretty tedious... open to suggestions for a more elegant option... …

[Go target] Fix for #3926: Add accessors for tree navigation to interfaces in generated parser

---

tool/src/org/antlr/v4/codegen/model/decl/ContextGetterDecl.java

Quick follow up to https://github.com/antlr/antlr4/pull/3927: @KvanTTT pointed out that the getter was unnecessary, and I confirmed this works fine. cc @parrt

Remove unnecessary getter

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelsOnRuleRefStartOfAlt.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Performance/DropLoopEntryBranchInLRRule_4.txt
runtime/Cpp/runtime/src/atn/ArrayPredictionContext.cpp

Fixed while doing https://github.com/antlr/antlr4/pull/3817  Also see  @kaby76's fix that I implemented: https://github.com/antlr/grammars-v4/issues/2909

Fix 3845 nullptr cpp

---

runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift

This PR fixes:
- A hard crash in the `ProfilingATNSimulator` initialiser, from attempting to set values via subscript on an empty array.
- A bug in `ProfilingATNSimulator.adaptivePredict`'s  method that meant `.timeInPrediction` would always report zero; this has now replaced by [the preferred way to measure time in Swift](https://forums.swift.org/t/recommended-way-to-measure-time-in-swift/33326).

Fix two Swift profiling bugs

---

Package.swift

This PR proposes removing the `type: .dynamic` property of the main library exported from the Swift package. 
Forcing the type of the library means that the project will _always_ be generated as a framework bundle, which is fine for application targets, but complicates CLI targets. 
Xcode includes smarts to determine what the appropriate type is to use, and the library does not appear to make use of any framework-specific features like resource bundling, so this should be a low impact change for users of the library.

Don’t specify a default type for the exported Swift package library

---

runtime/Cpp/runtime/antlrcpp.xcodeproj/project.pbxproj

The project had gotten out of sync with updates to the underlying code files. This fix will restore the ability to easily include ANTLR4 Cpp as a dependency via Xcode.
I had made a comment about this issue in the ANTLR4 Cpp Google group several months ago, and am just now circling back to fix it. Original post w/ context is here: https://groups.google.com/g/antlr-discussion/c/JRdZOss1Oq8
FYI The demo project in https://github.com/antlr/antlr4/tree/master/runtime/Cpp/demo still doesn't work, but I'm not sure how to fix that one.
Signed-off-by: Brad Bambara <brad.bambara@gmail.com>

Updating the files in the Xcode project for ANTLR4 Cpp runtime.

---

docker/README.md

No builds or tests were run because this is a README file change. Hopefully that's alright. 
I just noticed that I couldn't copy and paste the instructions and run them, so figured I'd help out a bit.

Fix typo of platfort to platform and weird double space to a single space character

---

antlr4-maven-plugin/pom.xml

Explicitly set version to: 2.0.7 fixes #3902 
Signed-off-by: chris-miner <94078897+chris-miner@users.noreply.github.com>

setting takari-lifecycle-plugin version explicitly to 2.0.7

---

runtime/Cpp/runtime/src/FlatHashMap.h
runtime/Cpp/runtime/src/FlatHashSet.h

**Abstract:**
This PR fixes the compiler errors in `src/FlatHashSet.h` and `src/FlatHashMap.h` introduced in the previous PR https://github.com/antlr/antlr4/pull/3694.
**Details:**
```
template <typename Key,
typename Hash = typename std::unordered_set<Key>::hasher,
typename Equal = typename std::unordered_set<Key>::key_equal,
typename Allocator = typename std::unordered_set<Key>::allocator_type>
using FlatHashSet = std::unordered_set<Key, Hash, Equal, Allocator>;
```
The existing type definition of `FlatHashSet/Map` is problematic if `Key` is not natively hashable (i.e. No specialization of `std::hash<Key>` available, so `std::unordered_set<Key>` cannot be specialized and therefore the member type `hasher` does not exist), resulting in errors when the runtime library is being compiled by …

[C++] Fix the compiler errors reported by GCC 7

---

doc/antlr-project-testing.md

The `**` gets expanded in some shells (zsh), so protect it from that, else the
invocation may fail, e.g.:
```
$ mvn -Dtest=javascript.** test
zsh: no matches found: -Dtest=javascript.**
```
... and a hasty person such as myself might miss the `zsh` in that output line
and think the “no matches” is from Maven meaning that there are no tests
identified by `javascript.**`, but there are.

doc: quote ** in test invocation example

---

runtime/Go/antlr/v4/atn_config_set.go
runtime/Go/antlr/v4/comparators.go
runtime/Go/antlr/v4/dfa.go
runtime/Go/antlr/v4/jcollect.go
runtime/Go/antlr/v4/ll1_analyzer.go
runtime/Go/antlr/v4/parser_atn_simulator.go
runtime/Go/antlr/v4/prediction_context.go
runtime/Go/antlr/v4/prediction_mode.go
runtime/Go/antlr/v4/semantic_context.go

fix: #3875 Extremely poor performance on poorly written grammars
The problem was once again a poorly written hash function, which caused ATN config sets to
hash poorly. The poor grammar caused many thousands of DFA states to hash to the same 
bucket. In your average grammar, this situation would not arise.
For now, I have changed that hash function to use the memory address of the slice that
contains the configs, though i think that this is sub-optimal.  I will revisit this as part of a
general attack at further performance gains.

fix: #3758 Extrememly poor performance on poorly written grammars

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.php.stg

Add ATN tracing support for the PHP target, as requested [here](https://github.com/antlr/antlr4/pull/3957#event-7850225906).
Companion PR:
https://github.com/antlr/antlr-php-runtime/pull/32
@parrt, could you please check if I'm missing something?

Add ATN tracing support for PHP target

---

doc/creating-a-language-target.md
runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.php.stg

This PR addresses an issue I found while running the debugger to ensure everything is fine.
I've also added instructions on how to run the PHP target's tests.

Fix PHP test template and improve docs about debugging

---

README.md
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Performance/DropLoopEntryBranchInLRRule_4.txt
runtime/Cpp/runtime/src/atn/ArrayPredictionContext.cpp

DropLoopEntryBranchInLRRule_4.txt test was failing due to comparing diff size arrays in C++.

Fix cpp equals bug #3959

---

.github/workflows/hosted.yml

Issue #3988: Builds failing on Ubuntu
The workflow is setup to work on Ubuntu-20.04 and the default 'latest' is migrating to Ubuntu-22.04 which isn't supported yet (all the dependent actions needs to support the platform before the workflow can use it).
Switching all platforms to use explicit versions rather than the '-latest' tag so the transition is more voluntary than something that just happens behind the scene.
Also, upgraded all setup-xx actions to latest versions to remove some of the deprecation warnings on dashboard.
Setup concurrency as well (kill any existing build running on the same branch branch and using the same workflow).

Issue #3988: Builds failing on Ubuntu

---

.github/workflows/hosted.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_1.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_2.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_3.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_4.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_5.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/Basic.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/LR.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/LRWithLabels.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/RuleGetters_1.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/RuleGetters_2.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/TokenGetters_1.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/TokenGetters_2.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParseTrees/TokenAndRuleContextString.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelForClosureContext.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelsOnRuleRefStartOfAlt.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ReservedWordsEscaping.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/CSharp.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Cpp.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Java.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/JavaScript.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/PHP.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python2.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Swift.test.stg

Extract unit test updates by @ericvergnaud in https://github.com/antlr/antlr4/pull/4027 then he can rebase after we merge this into dev.  All tests pass locally (didn't check python2 actually but python3 works).
Eric needed these changes so he can have more fine grained control over fields of rule ctx objects.
Signed-off-by: Terence Parr <parrt@antlr.org>

Extract unit test updates by @ericvergnaud needed for TypeScript

---

runtime-testsuite/test/org/antlr/v4/test/runtime/FileUtils.java

Extract FileUtils updates by @ericvergnaud in https://github.com/antlr/antlr4/pull/4027 then he can rebase after we merge this into dev.  All tests pass locally (didn't check python2 actually but python3 works).
Signed-off-by: Terence Parr <parrt@antlr.org>

Extract FileUtils updates by @ericvergnaud

---

tool/src/org/antlr/v4/codegen/model/ListenerFile.java
tool/src/org/antlr/v4/codegen/model/VisitorFile.java

Bug #3878 was missing some scenarios regarding scope of header actions.

Eric file objs update

---

runtime/Python2/src/antlr4/error/ErrorStrategy.py
runtime/Python2/src/antlr4/error/Errors.py
runtime/Python3/src/antlr4/error/Errors.py

- Added a message to LexerNoViableAltException (python2 & 3) : this avoids exception to be raised if the exception message is printed
- Corrected the ErrorStrategy (Python2) : 
-> notifyErrorListeners first argument should be the message, and second the Offending Token 
-> Exception does not have getMessage method

Python LexerNoViableAltException is created with messages (#4095)

---

runtime/Cpp/runtime/src/misc/IntervalSet.cpp

Clang implemented a warning last year to detect bare `move` and `forward` calls, as they have the potential to be error prone: https://github.com/llvm/llvm-project/commit/70b1f6de539867353940d3dcb8b25786d5082d63. This warning should be available in clang-15.

Fully qualify std::move invocations to fix -Wunqualified-std-cast-call

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

Signed-off-by: Eric Vergnaud <eric.vergnaud@wanadoo.fr>

fix missing union type

---

runtime/JavaScript/src/antlr4/CommonToken.d.ts
runtime/JavaScript/src/antlr4/Lexer.d.ts
runtime/JavaScript/src/antlr4/index.d.ts

These are some changes for Issue 4110, which is for the TypeScript target.
* CommonToken is needed. https://github.com/antlr/grammars-v4/blob/f1b4fc39279ce6a9e3878057fba935642f22c364/python/python3/JavaScript/Python3LexerBase.js#L59
* reset() is needed. https://github.com/kaby76/Domemtech.Trash/blob/2431705bdd3a2f3d64f1de5917ec07cd8f195c48/src/trgen/templates/TypeScript/Test.ts#L189
* skip() is needed. https://github.com/antlr/grammars-v4/blob/f1b4fc39279ce6a9e3878057fba935642f22c364/python/python3/JavaScript/Python3LexerBase.js#L109
* I'm including the export of other methods from Lexer as I know they are needed elsewhere.

Fix for Issue 4110

---

doc/actions.md

There is a missing space in `actions.md`. The docs could be improved with this small fix.

Add missing space to actions.md

---

runtime/Cpp/runtime/CMakeLists.txt
runtime/Cpp/runtime/src/internal/Synchronization.h

ANTLR doesn't use threads, and it used not to depend on pthread library either.
It changed recently in 2022: https://github.com/antlr/antlr4/issues/3708 The patch linked against pthread, because the GNU libstdc++ used to depend on it in their implementation of `std::call_once`.
By the way, the libstdc++ stopped it in 2020:
https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=93e79ed391b9c636f087e6eb7e70f14963cd10ad So this is not more needed.
I would like to stop depending on pthread. I am using ANTLR in C++ WebAssembly for the website:
https://arthursonzogni.com/Diagon/
It doesn't compile with emscripten anymore, because by default pthread is not enabled. It could be enabled, but it would force me to deploy cross-origin-isolation:
https://web.dev/cross-origin-isolation-guide/
Solutions:
1. …

cpp runtime: Remove pthread dependency.

---

tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg

Signed-off-by: Mykola Pokhylets <mykola.pokhylets@gmail.com>

Small tweaks to Swift.stg to allow throwing operations in actions

---

.gitignore
runtime/JavaScript/.c8rc.json
runtime/JavaScript/.eslintrc.yml
runtime/JavaScript/package-lock.json
runtime/JavaScript/package.json
runtime/JavaScript/spec/IntervalSetSpec.js
runtime/JavaScript/spec/rewriter/Makefile
runtime/JavaScript/spec/rewriter/TokenStreamRewriterSpec.js
runtime/JavaScript/spec/rewriter/abc.g4
runtime/JavaScript/spec/rewriter/calc.g4
runtime/JavaScript/spec/rewriter/generatedCode/abc.js
runtime/JavaScript/spec/rewriter/generatedCode/calc.js
runtime/JavaScript/src/antlr4/BufferedTokenStream.js
runtime/JavaScript/src/antlr4/TokenStreamRewriter.d.ts
runtime/JavaScript/src/antlr4/TokenStreamRewriter.js
runtime/JavaScript/src/antlr4/index.d.ts
runtime/JavaScript/src/antlr4/index.node.js
runtime/JavaScript/src/antlr4/index.web.js

Add a JavaScript port of the TokenStreamRewriter that includes most, but not all, of the methods from the Java implementation.
So that JavaScript developers can benefit from having it to implement all sorts of neat things (refactorings, translation etc.) 
- `insertAfter`
- `insertBefore`
- `replace`
- `delete`
- `getText`
- `getProgram`
- `getTokenStream`
The following methods were omitted because 
a) I couldn't find any tests for them and 
b) their utility is not immediately obvious to me.  
- `rollback`
- `deleteProgram`
- `getLastRewriteTokenIndex`
If someone needs them then we can obviously add support for them in a subsequent PR.
By
- Porting **most** of the `TokenStreamRewriter` class
- Porting tests and supporting fixtures (there are a couple of toy grammars used by the tests)
- …

Provide Javascript port of TokenStreamRewriter

---

runtime/JavaScript/src/antlr4/Token.d.ts

More typescript exports

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

Hello,
the arrays `literalNames` and `symbolicNames` do not only contain strings, but also null. Therefore we should reflect that in the TypeScript type to prevent build errors in strict mode.
Thank you for your great work on the TypeScript target, loving it :)
Kind regards
Sharknoon

[TypeScript] Fix types in template (missing null-union)

---

runtime/Cpp/runtime/CMakeLists.txt

Posix threads are available only on Unix (and unix like) platforms. Wrap the dependency accordingly so builds don't fail on other platforms.

Limit use of Posix threads to Unix

---

README.md

The badge in the README suggests that ANTLR requires Java 7 or higher, whereas since ANTLR v4.10 Java 11 or higher is required.
NOTE: This is a commit against the `master` branch, but given that the latest versions already have this requirement, I figured it makes more sense to base this against `master` rather than `dev`.

README: Update required Java version

---

runtime/JavaScript/src/antlr4/context/ParserRuleContext.d.ts

Hello,
the two functions `getTypedRuleContext` and `getTypedRuleContexts` only accept a argument named `parser` of type `Parser`, but not of a type that extends `Parser`. This is causing the following problem: 
Therefore I propse to allow child types of `Parser`.
Thank you :)
Kind regards
Sharknoon

[TypeScript] Explicitly allow parameters to be children of type Parser

---

runtime-testsuite/resources/junit-platform.properties
runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeRunner.java
runtime-testsuite/test/org/antlr/v4/test/runtime/go/GoRunner.java

feat: Speed up the go runtime tests
Prior to this change, after writing the go.mod file for each test, we had to run a `go mod tidy` command. This is an extra process sparked for each test, which can be quite the overhead.
This change runs a `go mod tidy` only if we have not yet cached the results (`go.mod` and `go.sum`) for any prior test and therefore saves sparking a process for each test.
@parrt When you get a chance, could you change the Github test runtime environment to use go 1.20.1 ? I would like to keep our development and testing versions of the go compiler up to date, even if I decide not to require go 1.20 at this time. Cheers.

Improve runtime performance of the Go runtime test suite

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/CompositeParsers/ImportedRuleWithAction.txt
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
runtime/Go/antlr/v4/error_strategy.go
runtime/Go/antlr/v4/errors.go
runtime/Go/antlr/v4/parser.go
runtime/Go/antlr/v4/parser_atn_simulator.go
runtime/Go/antlr/v4/recognizer.go
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

feat: Another 50%+ performance improvement
Prior to this change, the runtime and generated code was using panic() and recover()
to perform error checking and reporting. This is extremely expensive and just not the
way to do it. 
This change now uses goto, and explicit checking for error state after selected calls
into the runtime. This has greatly improved parser performance. Using the test code
provided by a recent performance issue report, the parse is now twice as fast as the
issue raised was hoping for. 
This change may require code changes by users if they have added Go code in to their
parsers and have declared variables at random points in actions. They merely have to
declare the variables at the start of the rule. This is a minor price to pay for the massive
performance …

Don't Panic! 50% plus performance improvement

---

.github/workflows/hosted.yml

Issue #4185: Too many artifacts fail to upload
Github action for upload was upgraded to v3 recently and the release is unstable causing too many uploads to fail. Reverting that change to go back to using v2.
Unfortunately, this change also downgrades use of Node.js to 12 which is deprecated, generating too many warnings in build output. Favoring warnings over failed builds.

Issue #4185: Too many artifacts fail to upload

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Removed the redundant `__name__` checks in Python 3 files. In Python 3, `__name__` is implicitly set and will never be None, making this condition always true. Did not modify any of Python 2 files since I am not sure about Python 2, but I think the same logic may also apply.

Remove redundant __name__ check in multiple files

---

runtime/JavaScript/package.json
runtime/JavaScript/spec/imports/NodeCommonJSImportSpec.cjs
runtime/JavaScript/spec/imports/NodeEsmImportSpec.mjs
runtime/JavaScript/spec/support/jasmine.json
runtime/JavaScript/webpack.config.js

No package should enforce upon creator a need to migrate to ESM. As per this pull request, I added webpack configuration that produces cjs and mjs files Correspoding to CommonJS and ESM module. After this pull request if will be up to a project which one to use.
Cheers!

[Javascript] Added support for commonjs in nodejs package

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

Currently Golang codegen passes through `boolean` types without type conversion. This generates invalid Golang, as `boolean` is not Golang keyword.
This PR copies Swift's implementation of a type map: https://github.com/antlr/antlr4/blob/8dcc6526cfb154d688497f31cf1e0904801c6df2/tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg#L40-L48

Add support to Golang codegen for booleans

---

runtime/Go/antlr/v4/file_stream.go
runtime/Go/antlr/v4/input_stream.go

feat: Clean up input streams
- The input streams were inefficient, making more copies of the incoming data than they needed to.
-  Add new Go idiomatic IO stream,  though this cannot be open-ended such as a socket, it is easier for go programmers
in certain situations.

Feat: Clean up go input streams to be a little more efficient

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

feat: Add usable @ actions to the go code generator
As I implement my own parsers in the Go runtime, it became obvious that the existing @members and @header were implemented incorrectly and in fact were not usable.
I cannot change the use of those existing actions as I have no way to know if people have already used them for something. So this PR adds the following new actions:
```antlr
@structmembers {} // allows insertion of items in to the parser or lexer instance struct
@includes {} // allows specifying additional includes in the generated source code
```
There may be other actions that will prove to be useful down the line.

feat: Adds actual usable @ actions to the go templates

---

runtime/Go/antlr/v4/common_token_stream.go
runtime/Go/antlr/v4/token_stream.go
runtime/Go/antlr/v4/tokenstream_rewriter.go

fix: Implement Reset in TokenStream interface and fix both it and SetTokenSource
ping: @parrt

fix: Allow CommonTokenStream to reset properly

---

tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

feat: Make static data available outside the generated parser code
- Allows Go code to access things like RuleNames outside the generated code
instead of non-idiomatic and non-existent Getxxx() funcs

Export generated data structures

---

runtime/Go/antlr/v4/parser_atn_simulator.go

feat: closureCheckingStopState is now an iterative function
- Recursive function retained but will be removed next release
- Improves stack usage on poor grammars
- Provides general speed up for all grammars
First of a few potential changes to use iteration instead of recursion

Change closureCheckingStopState from recursive to iterative

---

tool/pom.xml
tool/resources/org/antlr/v4/tool/templates/unicodedata.st
tool/src/org/antlr/v4/unicode/UnicodeDataTemplateController.java

Generated UnicodeData.java: 4417 KB -> 778 KB
Result antlr.jar artifact: 2566 KB -> 1322 KB
Now UnicodeData.java can be analyzed by IntelliJ, previously it was too big and IntelliJ encountered error when I opened this file.
fix #4226

Optimize generated unicode data

---

README.md
runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.go.stg
runtime-testsuite/test/org/antlr/v4/test/runtime/go/GoRunner.java
runtime/Go/antlr/go.mod
runtime/Go/antlr/v4/LICENSE
runtime/Go/antlr/v4/go.mod
runtime/Go/antlr/v4/go.sum
tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg

The go code for the Go runtime is now located at: antlr4-go/antlr
This PR:
- Updates the main README file to point this out
- Changes the test .stg file to use the new repo name
- Changes the codegen to generate imports from the new repo
The new repo has been initialized with the code tagged as the v4.12.0 release and is tagged there. The README.md for that repo also includes the standard badges for Go modules to indicate code quality, release status and license type. It has been tested and found to be good. 
We should have no more problems with go module imports so long as everyone uses the new repo.
@parrt This is the last PR needed for Go to be released. Tests pass and run.

Feature/newrepo - Transition Go code to new runtime repo

---

.github/workflows/hosted.yml
runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Antlr4.Test.csproj.stg

Surprisingly, the test `LargeLexer` is freezing on dotnet 7 (local machine). But it works fine if I change version of `.csproj` to 7. It looks like a bug in dotnet (there is something wrong with back compatibility) but it can be fixed by version upgrading.

Update dotnet to the latest version in runtime tests (6 -> 7)

---

doc/go-target.md

fix go-target.md。
Remove duplicate 'get'
`go get -u get github.com/antlr4-go/antlr -> go get -u github.com/antlr4-go/antlr`

fix go-target.md, remove duplicate 'get'

---

tool/src/org/antlr/v4/codegen/model/OutputFile.java

When code generating for Java on Windows, a grammar file may be contained in a subdirectory that starts with a 'u'. Because the generated file is comment with the source file that generated it, and windows path escaping is not used,
then the comment  looks like this in Java:
```java
// Generated from .\users\jim.g by ANTLR 4.13.0
```
The \u is seen by the Java lexer as an invalid escape sequence because Java processes the whole translation unit through pre-processing and lexing.
So, here, just for the template generating the comment, we use Unix style delimiters instead of the backslashes.
NB: I have no Windows box, so I will have to let the GitHub triggers ensure that Windows builds.
Fixes #4128 
Closes #4128

fix: #4128 - Prevent generating escape sequences when Windows directories start with  a 

---

runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/uStartingCharDoesNotCauseIllegalUnicodeEscape.txt

Fix producing of source with "illegal unicode escape"

Add test with grammar name that starts with u

---

runtime/JavaScript/.babelrc

Solves a Javascript perfomance problem. Closes #4322.
Kudos to @angrykoala for helping me debug and solve the issue.

Adds default targets for babel configuration

---

Package.swift

SPM cannot always properly recognise dependency type (dynamic or static) so it would be useful to be able to explicitly specify if static or dynamic is needed.
This is the case when eg. dependency is provided not as a source code but rather as a binary and dependency is already fixed into the file.
SPM is not able to detect binary dependencies. There is also no way to specify type of binary's dependencies.
There is already Antlr4Static in Package.swift so dynamic equivalent should be added for completeness.
This PR brings back the [change](https://github.com/antlr/antlr4/pull/3669) that as introduced a year ago but was later overwritten by [dev to master merge](https://github.com/antlr/antlr4/commit/49b69bb31aa34654676a864b229a369680122470#diff-a8ff7c526b830308074a30da78f5627b54ce5a6ed6b6e …

[SWIFT] Add Antlr4Dynamic product

---

tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

Without this change, JDK 21 will give a warning about ANTLR-generated code.
Closes #4341

Java: suppress `this-escape` warning introduced in JDK 21.

---

runtime/Go/antlr/v4/input_stream.go

This causes a fair number of diffs when importing into Google. If a way of setting the source name for string input streams was provided, then we could have the default be the empty string.

Restore "Obtained from string" source name.

---

runtime/CSharp/src/Atn/ParserATNSimulator.cs
runtime/CSharp/src/BaseErrorListener.cs
runtime/CSharp/src/DiagnosticErrorListener.cs
runtime/CSharp/src/IParserErrorListener.cs
runtime/CSharp/src/ProxyParserErrorListener.cs

This is a fix for #4386: fix signatures of [ReportAttemptingFullContext()](https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/CSharp/src/DiagnosticErrorListener.cs#L88C30-L88C57) and [ReportContextSensitivity()](https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/CSharp/src/DiagnosticErrorListener.cs#L97) for the CSharp.
In this PR, I changed the signatures for ReportAttemptingFullContext() and ReportContextSensitivity() for the CSharp runtime to be identical to that for all the other runtimes. The code before this change appears to be written with the idea of exposing the prediction context in some other way. But, it seems the idea never was thought completely out, and what was implemented was basically useless null …

[CSharp] Fix for #4386 -- change signatures for ReportAttemptingFullContext() and ReportContextSensitivity() to be identical to all other targets

---

runtime/Java/pom.xml

see last release check: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/antlr/antlr4/README.md
it was hit by https://issues.apache.org/jira/browse/FELIX-6602 that is fixed in this 5.1.9 release of maven-bundle-plugin

upgrade maven-bundle-plugin: fixes last Reproducible Builds issue

---

runtime/Go/antlr/v4/comparators.go
runtime/Go/antlr/v4/lexer.go
runtime/Go/antlr/v4/parser_atn_simulator.go
runtime/Go/antlr/v4/prediction_context.go

Tiny cleanups to ensure 100% results from https://goreportcard.com/report/github.com/antlr4-go/antlr

fix: Fix very minor code issues spotted by goreportcard.com

---

runtime/Go/antlr/v4/token.go

This change means that BaseToken satisfies the Token interface.
The recent addition of the String() function to the Token interface means that any custom BaseToken derivatives no longer satisfy the Token interface. Rather than forcing them all to implement their own String() function, put the CommonToken String function (plus GetText and SetText) into the BaseToken.

Move GetText(), SetText(), and String() from CommonToken to BaseToken

---

tool/src/org/antlr/v4/codegen/target/SwiftTarget.java

Cleanup duplicate SwiftTarget code

---

runtime/JavaScript/README.md

The current `antlr4` JavaScript package requires Node.JS v16, since https://github.com/antlr/antlr4/commit/2c75e642796718273fd215b03a310d4958319bad (aka ANTLR 4.12.0).
The important line changed is:
https://github.com/antlr/antlr4/blob/ce7f5e73cd4787c5aebdc05c29d4d898d6f2d123/runtime/JavaScript/package.json#L49
**By the way, can an admin modify the release notes for https://github.com/antlr/antlr4/releases/tag/4.12.0 and stick somewhere that the javascript target now requires Node v16?** It's currently missing from the release notes.
By the way, I've also added some badges to the `runtime/JavaScript/README.md` file that automatically load data listed in the `package.json` file, which look like: [![npm version](https://img.shields.io/npm/v/antlr4)](https://www.npmjs.com/package/antlr4) …

[JavaScript] Document Node.JS v16 requirement

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

Currently, when targeting TS, ANTLR will generate a parser file with this code:
This PR adds the override keyword to fix this issue.

Add "override" before EOF in TS

---

runtime/JavaScript/package.json

Currently as of 4.13.1 the entrypoint for `browser` is invalid, and `main` specifies the `esm` build instead of the `commonjs` one.
This results in commonjs based sources attempting to load esm syntax when addressing the sources using `main`.
The error in `browser` causes this error when attempting to bundle the sources:
```
[commonjs--resolver] Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "antlr4". The package may have incorrect main/module/exports specified in its package.json.
```
- `browser` field updated to fix the extension
- `"dist/antlr4.web.js"` -> `"dist/antlr4.web.mjs"`
- `main` field updated to point to the commonjs bundle
- …

[Javascript] Fix broken package entrypoints

---

runtime/Cpp/cmake/README.md

fix: tweak word antrl to antlr

---

runtime/Go/antlr/README.adoc

docs: fix wrong way to import in go

---

runtime/Python3/src/antlr4/atn/ATNDeserializer.py

Currently, loading a parser from an incompatible version results in a message like:
> Could not deserialize ATN with version  (expected 4).
(see e.g. https://github.com/antlr/antlr4/issues/4041 )
Change the exception message generation to use `ord(version)`, so it shows e.g. the string 3 instead of the character with ordinal 3, which is non-printable and the cause for the above cryptic message.

Generate meaningful exception message on checkVersion() failure

---

runtime/JavaScript/src/antlr4/index.node.js
runtime/JavaScript/src/antlr4/index.web.js

Fix missing export of TokenStreamRewriter

---

tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg

This fixes https://github.com/antlr/antlr4/issues/4485

fix: Suppress this-escape warning in generated Parser introduced in JDK 21

---

doc/javascript-target.md

Fixes #4537 
@parrt you might want to also update the antlr.org web site

Remove dead link

---

runtime/JavaScript/spec/BitSetSpec.js
runtime/JavaScript/src/antlr4/atn/LL1Analyzer.js
runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
runtime/JavaScript/src/antlr4/atn/PredictionMode.js
runtime/JavaScript/src/antlr4/error/DiagnosticErrorListener.js
runtime/JavaScript/src/antlr4/misc/BitSet.js

Implements perf improvement by using array view for bit set

Use arrayview for bit set

---

runtime/JavaScript/spec/HashMapSpec.js
runtime/JavaScript/src/antlr4/misc/HashMap.js
runtime/JavaScript/src/antlr4/utils/standardEqualsFunction.js

implement faster HashMap

---

runtime/JavaScript/src/antlr4/Parser.d.ts

This PR adds the four parse listener methods. The `_parseListeners` field could also be set to `ParseTreeListener[]`, but it would _technically_ be a breaking change.
I chose to use `ParseTreeListener` instead of `any` in these methods because parse listeners cannot actually be `any`; their functions are called without checking if they're defined. The current ParseTreeListener interface is the minimum requirement to avoid exceptions.

Add parse listener methods to Parser typescript

---

runtime/JavaScript/src/antlr4/Lexer.d.ts
runtime/JavaScript/src/antlr4/Lexer.js
runtime/JavaScript/src/antlr4/Parser.d.ts
runtime/JavaScript/src/antlr4/Parser.js
runtime/JavaScript/src/antlr4/Recognizer.d.ts
runtime/JavaScript/src/antlr4/Recognizer.js
runtime/JavaScript/src/antlr4/Token.d.ts
runtime/JavaScript/src/antlr4/action/LexerModeAction.js
runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js

**Added TypeScript members:**
- Lexer.setMode()
- Lexer.getMode()
- Lexer.getModeStack()
- Recognizer.getErrorListener()
- Recognizer.getLiteralNames()
- Recognizer.getSymbolicNames()
- Token.INVALID_TYPE
- Token.getTokenSource()
Removed (fixed) TypeScript member:
- Lexer.more(m: number)
Added JavaScript members:
- Lexer.setMode()
- Lexer.getMode()
- Lexer.getModeStack()
- Recognizer.getErrorListener()
Depricated JavaScript members:
- Lexer.mode(...)
- Recognizer.getErrorListenerDispatch()

depricate some methods

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

Required for `"noImplicitOverride": true` typescript setting.
I couldn't figure out how to add a test for this situation in the typescript test file. It only happens if a rule context class has a subclass.

Add override specifier to typescript copyfrom codegen

---

runtime/JavaScript/src/antlr4/Lexer.js

fix missing 'this'

---

runtime/Cpp/runtime/src/TokenStreamRewriter.cpp

Fixing crash bug in TokenStreamRewriter
Order of operations issue - use before deleting not vice-versa.

Fixing crash bug in TokenStreamRewriter

---

runtime/JavaScript/src/antlr4/BufferedTokenStream.js

`BufferedTokenStream::nextTokenOnChannel` was accessing the field `this.channel` instead of the parameter `channel`. The buffered token stream class doesn't have a field named `channel`, so this exhausted the token buffer instead.
The bug had not been caught because it is only called from `CommonTokenStream` with parameter `this.channel`.

[JavaScript] Fix incorrect this.channel access

---

runtime/JavaScript/src/antlr4/Parser.js

`Parser.getSourceName` was expecting a field `sourceName` on `TokenStream`, but that doesn't exist on any `TokenStream` implementation. This commit fixes the bug by calling `getSourceName`, which *is* defined on `BufferedTokenStream`.
This commit also removes some nearby commented-out code that didn't make any sense.

[JS] Fix Parser.getSourceName returning undefined

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

The title says it all
Fixes #4572

[TS] add missing channel constants

---

runtime/JavaScript/src/antlr4/index.node.js
runtime/JavaScript/src/antlr4/index.web.js

When overriding reportError in DefaultErrorStrategy, all exceptions (NoViableAltException, FailedPredicateException) are exported except InputMismatchException.

Export InputMismatchException

---

runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift

* NSEC_PER_SEC is available via CDispatch bindings, which are not currently imported
* Importing them would be heavy handed compared to replacing with the constant (and leaving a comment)
-----
Compiling on Linux currently produces:
```
[239/269] Compiling Antlr4 SetTransition.swift
/workspace/.build/checkouts/antlr4/runtime/Swift/Sources/Antlr4/atn/ProfilingATNSimulator.swift:63:85: error: cannot find 'NSEC_PER_SEC' in scope
decisions[decision].timeInPrediction += Int64((stop - start) * TimeInterval(NSEC_PER_SEC))
```
After fixing this, it compiles (and behaves) as expected.

Fix Linux compilation issue of ProfilingATNSimulator

---

runtime/Go/antlr/go.sum
runtime/Go/antlr/v4/atn.go
runtime/Go/antlr/v4/atn_config.go
runtime/Go/antlr/v4/jcollect.go
runtime/Go/antlr/v4/ll1_analyzer.go
runtime/Go/antlr/v4/mutex.go
runtime/Go/antlr/v4/mutex_nomutex.go
runtime/Go/antlr/v4/prediction_context.go
runtime/Go/antlr/v4/statistics.go
runtime/Go/antlr/v4/utils.go

Adds a build tag such that mutex checking can be turned off for users not using the parser
from multiple threads. This is off by default so that the behavior does not change. 
Adds slight performance improvements.
@parrt This is part of catching things up for Google

Minor improvements and catchups for Go 4.13.1

---

runtime/Cpp/runtime/src/atn/ATNDeserializationOptions.cpp
tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

This PR fixes memory leaks caused by the StaticData objects associated with the generated Parser and Lexer classes. 
Found using the CRT library in VS2022. With the demo project, it produces a leak report similar to this:
```
Detected memory leaks!
Dumping objects ->
{21126} normal block at 0x000001AAB1D11180, 32 bytes long.
Data: <                > 00 95 CF B1 AA 01 00 00 A0 9A CF B1 AA 01 00 00 
{20999} normal block at 0x000001AAB1D141E0, 32 bytes long.
Data: <`       `       > 60 1F D1 B1 AA 01 00 00 60 1F D1 B1 AA 01 00 00 
{20982} normal block at 0x000001AAB1D134C0, 32 bytes long.
Data: <         1      > C0 A8 CD B1 AA 01 00 00 C0 31 D1 B1 AA 01 00 00 
{20981} normal block at 0x000001AAB1D20DF0, 128 bytes long.
Data: <                > 00 19 D1 B1 AA 01 00 00 00 19 D1 B1 AA 01 00 00 …
```

[Cpp] Fix cpp memory leaks

---

runtime/Cpp/runtime/CMakeLists.txt

Use target_include_dirs to attach include directories to targets. This allows setting include directories for the `INSTALL_INTERFACE` which will get exported into `antlr4-targets.cmake`.
`antlr4-targets.cmake` will now have an `INTERFACE_INCLUDE_DIRECTORIES` property set like so:
```
set_target_properties(antlr4_shared PROPERTIES
INTERFACE_COMPILE_DEFINITIONS "ANTLR4CPP_EXPORTS"
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/antlr4-runtime"
)
```
When downstream users pull in antlr4-runtime using `find_package(antlr4-runtime)`, the imported targets `antlr4_static` and `antlr4_shared` will automatically pick up the appropriate include directories instead of needing to manually use `ANTLR4_INCLUDE_DIR`.

[Cpp] Use target_include_dirs for cmake targets

---

runtime/JavaScript/package.json

When using the published `npm` package in my TypeScript project, TypeScript gave the error that it couldn't find the types.
This fix makes sure that the type field in the `package.json` is not in a specific exports target, which fixes the issue. The same types are exposed for both the web and node target, so they were combined in the same field.

[JavaScript-runtime] Support TypeScript bundler module resolution for types

---

docker/Dockerfile

It seems this appuser wasn't being used at all, and the USER line wasn't being set to enable it. In addition, the adduser utility didn't exist in the old or updated version of temurin. This seems simpler and works.

Update to eclipse-temurin:21 and remove appuser

---

runtime/JavaScript/src/antlr4/error/LexerNoViableAltException.d.ts
runtime/JavaScript/src/antlr4/error/index.d.ts

Currently I am using  latest antlr package from npm `"antlr4": "^4.13.2"` and I don't know how to check if an exception is the proposed class without importing js sources.

Add LexerNoViableAltException typescript class

---

tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg

When using some strict TypeScript options, you can't compile the code anymore because of this specific line. Unfortunately I don't know enough about the necessity of the line to help in another way, so that's why I added this simple fix.
There is another error for unused imports in the Lexer file, but I wasn't able to test that one out since that import seemed to have been changes recently.

Explicitly ignore unused var in TypeScript and @typescript-eslint

---

runtime/Python3/src/antlr4/Lexer.py
runtime/Python3/src/antlr4/Parser.py
tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg

Checking just the second element of a version tuple is never good style, and it makes it less clear what actual versions of Python are in question.

Improve Python version handling

---

runtime/JavaScript/src/antlr4/tree/Trees.d.ts
runtime/JavaScript/src/antlr4/tree/index.d.ts

Adding Typescript definition files to export Trees module.
Fixes #4715

Adding Typescript definition files to export Trees module.

---

runtime/JavaScript/src/antlr4/error/DiagnosticErrorListener.d.ts
runtime/JavaScript/src/antlr4/error/ErrorListener.d.ts
runtime/JavaScript/src/antlr4/misc/BitSet.d.ts

Fixes: https://github.com/antlr/antlr4/issues/4730
Updates TypeScript declaration file for `ErrorListener`. Additionally updates `DiagnosticErrorListener` that implements `ErrorListener` and adds a declaration file for `BitSet` class (`BitSet.d.ts`).

fix(JS: ErrorListener types)

---

runtime/CSharp/src/Atn/ATN.cs
runtime/CSharp/src/Dfa/DFA.cs
runtime/CSharp/src/LexerInterpreter.cs
runtime/CSharp/src/Recognizer.cs
runtime/CSharp/src/Sharpen/BitSet.cs
runtime/CSharp/src/Sharpen/Collections.cs
runtime/CSharp/src/Vocabulary.cs

I noticed when enabling some static code analysis rules (by setting the property `<EnableNETAnalyzers>true</EnableNETAnalyzers>` in the csproj file), that [CA1825: Avoid zero-length array allocations](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1825) was raised.
Because the C# solution still targets net4.5 (is that still needed? I would argue that net4.8 or netstandard2.0 should be sufficient, it is 2025 after all) the use of [`Array.Empty<T>`](https://learn.microsoft.com/dotnet/api/system.array.empty) can not be used. However, fortunately, `Collections.EmptyList<T>`  already provided a solution. I just applied them where applicable.

[C# target] Use Collections.EmptyList to prevent zero length allocations

---

.github/workflows/hosted.yml
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/TypeScript.test.stg

Mandatory bump of actions/upload-artifact, see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Bump GitHub action

---

.github/workflows/hosted.yml
runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/TypeScript.test.stg

macos-12 is deprecated on GH, see https://github.com/actions/runner-images/issues/10721
This PR upgrades our CI to use macos-15

Bump GitHub platform

---

runtime/Cpp/runtime/src/atn/ProfilingATNSimulator.cpp

I am a member of Microsoft vcpkg, due to there are new changes merged by microsoft/STL#5105, which revealed a conformance issue in `antlr4`. It must add include `<chrono>` to fix this error.
Compiler error with this STL change:
```
D:\b\antlr4\src\4.13.2-0987b822d0.clean\runtime\Cpp\runtime\src\atn\ProfilingATNSimulator.cpp(38): error C2653: 'high_resolution_clock': is not a class or namespace name
```

Include `<chrono>` for high_resolution_clock

---

runtime/Cpp/runtime/src/antlr4-runtime.h

Described here https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-begin_exportsend_exports
These pragmas are not only understood by the IWYU tools, but as well clang-tidy ( https://clangd.llvm.org/design/include-cleaner#iwyu-pragmas ), so that projects using clang-tidy will not get false-positives about missing includes.

Add IWYU pragmas to indicate that the headers export symbols.

---

runtime/Cpp/cmake/README.md

Fix typo from _ExternalAntlr4Cpp.cpp_ to _ExternalAntlr4Cpp.cmake_ in runtime/Cpp/cmake/README.md file.

Fix typo in cpp readme

---

runtime/Cpp/runtime/src/RuleContext.h

The operator== in RuleContext only mildly looked like the virtual operator== in the base class: it does take a different parameter and was not const.
This results in warnings by the compiler complaining about a shadowed method:
```
/usr/include/antlr4-runtime/tree/ParseTree.h:50:18: warning: ‘virtual bool antlr4::tree::ParseTree::operator==(const antlr4::tree::ParseTree&) const’ was hidden [-Woverloaded-virtual=]
50 |     virtual bool operator == (const ParseTree &other) const;
|                  ^~~~~~~~
/usr/include/antlr4-runtime/RuleContext.h:135:10: note:   by ‘bool antlr4::RuleContext::operator==(const antlr4::RuleContext&)’
135 |     bool operator == (const RuleContext &other) { return this == &other; } // Simple address comparison.
```
This does not look intentional. Fix by using …

RuleContext: use correct override.

---

runtime/Cpp/runtime/CMakeLists.txt

CMake version 4.0.0 doesn't support the currently used `googletest` CMake project version. As such, updating the project to the latest version makes sense.
(This closes https://github.com/antlr/antlr4/issues/4807)

Fix a CMake v4.0.0 build error (related to `googletest`)

---

tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg

Consider the following simple grammar:
```antlr
Expression : Expression '*' Expression
| Expression '+' Expression
```
ANTLR will generate the following member function:
```c++
bool SampleParser::expressionSempred(ExpressionContext *_localctx, size_t predicateIndex)
{
switch (predicateIndex) 
{
case 0: return precpred(_ctx, 5);
case 1: return precpred(_ctx, 4);
default:
break;
}
return true;
}
```
The first parameter is never used in the function body, resulting in an unused parameter warning. This PR fixes the warning by adding the attribute `[[maybe_unused]]` which is available as of C++17.
Thank you.

Cpp: Fix the unused parameter warning in the sempred function.

---

runtime/Cpp/CMakeLists.txt
runtime/Cpp/runtime/CMakeLists.txt

This allows overriding them if needed when the system uses different paths than usual (e.g. Haiku, which uses "develop/headers" for includes instead of "include").
Signed-off-by: Joachim Mairböck <j.mairboeck@gmail.com>

[Cpp] CMake: use variables for specifying install paths consistently
