antlr/antlr4

- bild.py
> add osgi stuff in manifest of runtime jar

- runtime/Java/pom.xml
- runtime/Java/src/org/antlr/v4/runtime/misc/NotNull.java
- runtime/Java/src/org/antlr/v4/runtime/misc/NullUsageProcessor.java
- runtime/Java/src/org/antlr/v4/runtime/misc/Nullable.java
- tool/pom.xml
- added note for maven developers
- removed maven plugins
- updated maven dependencies for dev only
- added antlr4 annotations to project
> maven cleanup

- contributors.txt
I fixed keyword issues with antlr4-javascript.
https://github.com/antlr/antlr4-javascript/pull/18
@ericvergnaud suggested that I should add myself to the contributors
https://github.com/antlr/antlr4-javascript/issues/17
> Added as contributor due to a fix in antlr4-javascript

- runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java
- runtime/Java/src/org/antlr/v4/runtime/dfa/DFA.java
This should fix #804
**Note:** This code has not been compiled or tested as the build and test configuration has been removed from the `master` branch.
> Fix potential misuse of the DFA start state when initializing a decision

- contributors.txt
I signed the contributor agreement.
> Robert Jacobson signed the contributor agreement.

- runtime/Java/src/org/antlr/v4/runtime/misc/IntegerList.java
Added error checks.
Removed a confusing variable 'current' from addAll(Collection<Integer> list).
In 'int get(int index)', it might be more robust to invert fromIndex and toIndex.
> Added error checks.

- runtime/Java/src/org/antlr/v4/runtime/Parser.java
- tool/playground/Main.java
- tool/playground/T.g4
- tool/tool.iml
> Fix parse listeners

- runtime/Java/src/org/antlr/v4/runtime/ParserInterpreter.java
- runtime/Java/src/org/antlr/v4/runtime/atn/AmbiguityInfo.java
- runtime/Java/src/org/antlr/v4/runtime/atn/LookaheadEventInfo.java
- runtime/Java/src/org/antlr/v4/runtime/atn/ProfilingATNSimulator.java
(crap.  I messed up and included the previous PR in this one; no big deal as I'm merging the other ahead of this.)
> Add error nodes

- bild.py
- tool/tool.iml
> got all but 2 tests passing for py2!

- runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/ParserErrors/TokenMismatch2
corresponding https://github.com/antlr/antlr4/commit/2e06ed8360b8df2cbdca1da73b3bd7de589a910f
> add new unit test TokenMismatch2

- runtime/Java/src/org/antlr/v4/runtime/Parser.java
- runtime/Java/src/org/antlr/v4/runtime/ParserInterpreter.java
- runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java
- runtime/Java/src/org/antlr/v4/runtime/atn/ProfilingATNSimulator.java
- runtime/Java/src/org/antlr/v4/runtime/tree/Trees.java
- tool/src/org/antlr/v4/tool/Grammar.java
- tool/src/org/antlr/v4/tool/GrammarInterpreterRuleContext.java
- tool/src/org/antlr/v4/tool/GrammarParserInterpreter.java
- tool/test/org/antlr/v4/test/tool/TestAmbigParseTrees.java
some cleanup and improvement to other interpreter.
> add new interpreter that knows how to track alternatives in rule nodes

- antlr4-maven-plugin/pom.xml
Thanks to @sharwell for catching this.
> Use variable for project version

- tool/src/org/antlr/v4/codegen/target/JavaScriptTarget.java
Octal is not supported in strict mode.
> Fix antlr4-javascript #36.

- .gitignore
- runtime/JavaScript/src/antlr4/Parser.js
- runtime/JavaScript/src/antlr4/atn/ATN.js
- runtime/JavaScript/src/antlr4/atn/ATNConfig.js
- runtime/JavaScript/src/antlr4/atn/ATNConfigSet.js
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
- runtime/Python2/src/antlr4/atn/ATNConfig.py
- runtime/Python3/src/antlr4/atn/ATNConfig.py
> Lexer bug in javascript runtime

- runtime/JavaScript/src/antlr4/Parser.js
- runtime/JavaScript/src/antlr4/atn/ATN.js
- runtime/JavaScript/src/antlr4/atn/ATNConfigSet.js
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
In the context of code completion, need this to enable call to getExpectedTokens with the invokingState corresponding to the token being replaced
> More context in javascript runtime

- .gitignore
- doc/faq/actions-preds.md
- doc/faq/error-handling.md
- doc/faq/general.md
- doc/faq/getting-started.md
- doc/faq/index.md
- doc/faq/installation.md
- doc/faq/lexical.md
- doc/faq/parse-trees.md
- doc/faq/translation.md
slowly but surely I will move documentation over to this repository.
> Move faq to repo

- doc/ace-javascript-target.md
I noticed this as I was reading through and thought, "Why not?"
> Minor cleanup to docs/ace-javascript-target.md

- contributors.txt
- runtime/JavaScript/src/antlr4/atn/PredictionMode.js
- runtime/JavaScript/src/antlr4/dfa/DFAState.js
This is a simple patch to fix some missing 'require' statements in the JS runtime.
> JS: Fix missing 'require' statements

- contributors.txt
- doc/actions.md
- doc/grammars.md
- doc/left-recursion.md
- doc/lexer-rules.md
- doc/options.md
- doc/predicates.md
- doc/tree-matching.md
Adding me to the contributors list seems silly for this.
> documentation typos

- runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java
- runtime/JavaScript/README.md
- runtime/JavaScript/src/antlr4/README.md
- runtime/Python2/src/antlr4/PredictionContext.py
- runtime/Python2/src/antlr4/atn/ATNConfig.py
- runtime/Python2/src/antlr4/atn/ATNConfigSet.py
- runtime/Python2/src/antlr4/atn/LexerATNSimulator.py
- runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python2/src/antlr4/atn/PredictionMode.py
- runtime/Python3/src/antlr4/PredictionContext.py
- runtime/Python3/src/antlr4/atn/ATNConfig.py
- runtime/Python3/src/antlr4/atn/ATNConfigSet.py
- runtime/Python3/src/antlr4/atn/LexerATNSimulator.py
- runtime/Python3/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python3/src/antlr4/atn/PredictionMode.py
- tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
> Python performance issue

- doc/adding-tests.md
> Enhancing the doc

- .gitignore
- contributors.txt
- runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java
Addresses issue #1260, allowing check-in of new language target files.
Also added .gitignore entries for Node.js & typescript dependency cache directories, and added my name to the Project Contributors Certification of Origin and Rights.
> Fix .gitignore for codegen/target language directory

- tool/src/org/antlr/v4/codegen/CodeGenPipeline.java
- tool/src/org/antlr/v4/codegen/CodeGenerator.java
- tool/src/org/antlr/v4/codegen/OutputModelController.java
- tool/src/org/antlr/v4/codegen/OutputModelWalker.java
- tool/src/org/antlr/v4/codegen/Target.java
- tool/src/org/antlr/v4/codegen/model/Recognizer.java
- tool/src/org/antlr/v4/codegen/model/decl/StructDecl.java
Adds header file functionality needed by C++ into single commit and moves filename computation to `Target` objects. Doesn't affect existing targets. Adds a bit to model for Go target.
> Model updates for new targets

- runtime/Go/antlr/interval_set.go
> Fix bug in IntervalSet

- doc/building-antlr.md
- runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/node/BaseNodeTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
> small improvements to locating mono, node

- runtime/Python3/src/antlr4/TokenStreamRewriter.py
(not tested, but I'm sure some users will provide feedback)
> port from python 2 version

- tool/src/org/antlr/v4/parse/LeftRecursiveRuleWalker.g
> Fix failure to identify prefix rules that also recurse

- README.md
> modify info on Swift target

- doc/getting-started.md
Thank you for proposing a contribution to the ANTLR project. In order to accept changes from the outside world, all contributors most "sign" the  [contributors.txt](https://github.com/antlr/antlr4/blob/master/contributors.txt) contributors certificate of origin. It's an unfortunate reality of today's fuzzy and bizarre world of open-source ownership.
Make sure you are already in the contributors.txt file or add a commit to this pull request with the appropriate change. Thanks!
> Change jar file from 4.5 to 4.5.3

- .travis.yml
- .travis/run-tests-java.sh
> add tool tests but only when testing java target

- runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/PerformanceDescriptors.java
- runtime/JavaScript/src/antlr4/atn/ATNDeserializer.js
- runtime/JavaScript/src/antlr4/atn/ATNState.js
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
- runtime/JavaScript/src/antlr4/dfa/DFA.js
- runtime/Python2/src/antlr4/ParserInterpreter.py
- runtime/Python2/src/antlr4/atn/ATNDeserializer.py
- runtime/Python2/src/antlr4/atn/ATNState.py
- runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python2/src/antlr4/dfa/DFA.py
- runtime/Python3/src/antlr4/ParserInterpreter.py
- runtime/Python3/src/antlr4/atn/ATNDeserializer.py
- runtime/Python3/src/antlr4/atn/ATNSimulator.py
- runtime/Python3/src/antlr4/atn/ATNState.py
- runtime/Python3/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python3/src/antlr4/dfa/DFA.py
Thank you for proposing a contribution to the ANTLR project. In order to accept changes from the outside world, all contributors most "sign" the  [contributors.txt](https://github.com/antlr/antlr4/blob/master/contributors.txt) contributors certificate of origin. It's an unfortunate reality of today's fuzzy and bizarre world of open-source ownership.
Make sure you are already in the contributors.txt file or add a commit to this pull request with the appropriate change. Thanks!
> Fix poor left recursive rule performance in python + javascript

- tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
- tool/src/org/antlr/v4/automata/LexerATNFactory.java
- tool/src/org/antlr/v4/semantics/SymbolChecks.java
- tool/src/org/antlr/v4/tool/ErrorType.java
> Duplicated and incompatible commands

- README.md
> Correct link for AppVeyor build

- tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
- tool/src/org/antlr/v4/semantics/SymbolChecks.java
- tool/src/org/antlr/v4/tool/LabelType.java
> Check labels for tokens with different types 

- runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/TestExpectedTokens.java
Hmm.... I can't reproduce https://github.com/antlr/antlr4/issues/1480 but I improved testing of that. This test passes even with repo rolled back to before https://github.com/antlr/antlr4/pull/1477 LL(1) analyzer fix.
> Fix 1480 (getExpectedTokens missing token from FOLLOW)

- runtime/Java/src/org/antlr/v4/runtime/CommonToken.java
- tool/src/org/antlr/v4/gui/TestRig.java
@antlr/antlr-targets might care about this.
> Fix #1073. Better token output.

- runtime/Java/src/org/antlr/v4/runtime/Recognizer.java
@antlr/antlr-targets might care
> Fixes #1042

- runtime/JavaScript/src/antlr4/Parser.js
> Implement the fix in #1471 for JavaScript target.

- runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParseTreesDescriptors.java
- runtime/Python2/src/antlr4/ParserRuleContext.py
- runtime/Python3/src/antlr4/ParserRuleContext.py
The patch adapts the fix in PR #1472 for Python targets.
> Implement the fix of #1298 for Python targets.

- runtime/Python2/src/antlr4/error/ErrorStrategy.py
> fix unicode issue in Python 2

- doc/targets.md
> Added Go in features table, and keep target order in sync with above.

- runtime/Swift/Antlr4/org/antlr/v4/runtime/Recognizer.swift
> Fixes #1042 Swift target

- runtime/Swift/Antlr4/org/antlr/v4/runtime/BufferedTokenStream.swift
- runtime/Swift/Antlr4/org/antlr/v4/runtime/atn/ParserATNSimulator.swift
Swift target Fixes #1238, Fixes #994
> Swift target Fixes #1238, Fixes #994 

- runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParseTreesDescriptors.java
- runtime/Swift/Antlr4/org/antlr/v4/runtime/ParserRuleContext.swift
> Fixes #1298 for Swift target

- runtime/Swift/Antlr4/org/antlr/v4/runtime/CommonToken.swift
> Fixes #1073 for Swift target

- runtime/Cpp/runtime/src/CommonToken.cpp
- runtime/Cpp/runtime/src/CommonToken.h
- runtime/Cpp/runtime/src/TokenFactory.h
- runtime/Cpp/runtime/src/antlr4-common.h
- runtime/Cpp/runtime/src/misc/Interval.h
Mostly that toString() enhancement, but also some other minor changes.
> Issue 1483

- doc/ace-javascript-target.md
- doc/javascript-target.md
- runtime/JavaScript/src/antlr4/package.json
- runtime/JavaScript/src/npm.txt
> Update npm related docs

- runtime/Python2/src/antlr4/Parser.py
- runtime/Python2/src/antlr4/PredictionContext.py
- runtime/Python3/src/antlr4/PredictionContext.py
> fixes #1530 and #1531

- runtime/JavaScript/src/antlr4/tree/Tree.js
> fix typo in javascript visitor

- runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java
- runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java
> Document the value shifting used in the serialized ATN

- antlr4-maven-plugin/src/main/java/org/antlr/mojo/antlr4/Antlr4Mojo.java
- runtime-testsuite/pom.xml
> Support using the Maven plugin to generate test sources

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/BufferedTokenStream.cs
- runtime/JavaScript/src/antlr4/BufferedTokenStream.js
- runtime/Python2/src/antlr4/BufferedTokenStream.py
- runtime/Python3/src/antlr4/BufferedTokenStream.py
> fix #1584 for C#, JavaScript and Python targets

- runtime/Go/antlr/atn_config.go
- runtime/Go/antlr/atn_simulator.go
- runtime/Go/antlr/lexer_atn_simulator.go
- runtime/Go/antlr/parser_atn_simulator.go
- runtime/Go/antlr/prediction_context.go
- runtime/Go/antlr/utils.go
Using the standard gofmt tool.
> Format Go runtime files

- contributors.txt
I got permission from FB's legal team to add myself to contributors.txt.
> Add bhamiltoncx to contributors.txt

- tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
- tool/src/org/antlr/v4/semantics/SymbolChecks.java
> The final fix (hopefully) for alternative labels check in left recursive rules

- contributors.txt
- runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParseTreesDescriptors.java
- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/ParserRuleContext.cs
Port of the java fix for #1298 to C#.
> Fix #1298 for CSharp

- tool/src/org/antlr/v4/codegen/target/GoTarget.java
fixes #1617.
Some spaces replaced with tabs.
> Added "action" to badWords set for Go runtime.

- .travis.yml
- .travis/before-install-linux-python3.sh
trying this out. python3.5 first.
> node, deadsnakes setup simplification

- runtime/Cpp/runtime/src/antlr4-common.h
> Some compilers need the functional include.

- runtime/Cpp/runtime/src/tree/pattern/ParseTreePatternMatcher.cpp
- runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp
> Fix for issue #1608

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs
- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Misc/Pair.cs
> Fix C# Pair.cs, Right arrow escaping in XML Comments

- runtime/Java/src/org/antlr/v4/runtime/RuleContext.java
- runtime/Java/src/org/antlr/v4/runtime/tree/ParseTree.java
- runtime/Java/src/org/antlr/v4/runtime/tree/TerminalNode.java
Addendum to previous commits #1665 and #1674 per conversation at #1673.
> shift setParent up one level

- tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
- tool/src/org/antlr/v4/automata/ATNOptimizer.java
- tool/src/org/antlr/v4/codegen/Target.java
- tool/src/org/antlr/v4/misc/CharSupport.java
- tool/src/org/antlr/v4/misc/EscapeSequenceParsing.java
- tool/src/org/antlr/v4/parse/ANTLRLexer.g
Improved warning output in ATNOptimizer.
Fixed #1714.
> Fixed incorrect "used multiple times" warning.

- runtime/Cpp/demo/TLexer.g4
A small change to make the C++ demo project work with the new Unicode support.
> Using new Unicode syntax for C++ demo project.

- runtime/Java/src/org/antlr/v4/runtime/misc/IntSet.java
- runtime/Java/src/org/antlr/v4/runtime/misc/IntervalSet.java
Updated comments to ensure people test isNil() or size() before requesting min, max, any single element.
> Fixes #1703. 

- .travis/before-install-linux-dotnet.sh
- .travis/run-tests-dotnet.sh
- runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Tree/Xpath/XPathLexer.cs
- runtime/CSharp/runtime/CSharp/project.json
Should work now: https://travis-ci.org/xied75/antlr4/builds/207577147
> fix #1725; get dotnet target test run

- tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
- tool/src/org/antlr/v4/automata/LexerATNFactory.java
- tool/src/org/antlr/v4/tool/ErrorType.java
But on my opinion such syntax a bit confused despite of it's common...
> Reverted unterminated ranges: [+-], [-+], [-].

- runtime/Cpp/runtime/src/atn/PredictionContext.cpp
> Fixed regression introduced by wrong optimization. Fixes #1708.

- tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
Fixes: https://github.com/antlr/antlr4/issues/1743
> Initialize decisionToDFA in init in Go.stg

- runtime-testsuite/test/org/antlr/v4/test/runtime/java/api/perf/TimeLexerSpeed.java
This is a redo of https://github.com/antlr/antlr4/pull/1787 on top of the new size information.
> Fix TimeLexerSpeed when run from jar

- runtime/Swift/Antlr4.xcodeproj/project.pbxproj
- runtime/Swift/Antlr4.xcodeproj/project.xcworkspace/xcshareddata/Antlr4.xcscmblueprint
- runtime/Swift/Antlr4.xcodeproj/xcshareddata/xcschemes/Antlr4 IOS.xcscheme
- runtime/Swift/Antlr4.xcodeproj/xcshareddata/xcschemes/Antlr4 OSX.xcscheme
- runtime/Swift/Sources/Antlr4/BaseErrorListener.swift
- runtime/Swift/Sources/Antlr4/TokenStreamRewriter.swift
- runtime/Swift/Sources/Antlr4/tree/AbstractParseTreeVisitor.swift
- runtime/Swift/Tests/Antlr4Tests/LexerA.g4
- runtime/Swift/Tests/Antlr4Tests/LexerB.g4
- runtime/Swift/Tests/Antlr4Tests/SwiftTest.g4
- runtime/Swift/Tests/Antlr4Tests/TokenStreamRewriterTests.swift
- runtime/Swift/Tests/Antlr4Tests/TokenStreamTests.swift
- runtime/Swift/Tests/Antlr4Tests/VisitorBasic.g4
- runtime/Swift/Tests/Antlr4Tests/VisitorCalc.g4
- runtime/Swift/Tests/Antlr4Tests/VisitorTests.swift
- runtime/Swift/test.py
Adding TokenStreamRewriter tests including fix for #550.
Added visitor tests.
> Adding more API tests to Swift runtime.

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/UnbufferedCharStream.cs
This ports https://github.com/antlr/antlr4/pull/1796 to the C# runtime.
The JS runtime doesn't have an equivalent of `UnbufferedCharStream`, so we should be good to go with all the runtimes with this change.
> C#: Change UnbufferedCharStream to use 32-bit Unicode code points and 32-bit buffer

- doc/lexicon.md
- doc/parsing-binary-files.md
- doc/unicode.md
- runtime/Java/src/org/antlr/v4/runtime/ANTLRFileStream.java
- runtime/Java/src/org/antlr/v4/runtime/ANTLRInputStream.java
- runtime/Java/src/org/antlr/v4/runtime/CharStreams.java
- runtime/Java/src/org/antlr/v4/runtime/UnbufferedCharStream.java
WIP update doc, deprecate old interface
> Deprecate old streams

- runtime/Swift/Antlr4.xcodeproj/project.pbxproj
Fixing Xcode setting for Swift API tests. Somehow the setting was overwritten by one of the commits.
> Fixing Xcode project setting.

- doc/getting-started.md
Either that or say what is is useful to do with...
> Update getting-started.md (trivial)

- runtime/Java/src/org/antlr/v4/runtime/IntStream.java
An extra word is in the comments.
Signed-off-by: Yishuang Lu luyscmu@gmail.com
> Typo in the comments of IntStream.java

- runtime/CSharp/README.md
> Update .Net NuGet package name to 4.7 with .NET Core target

- doc/javascript-target.md
> Update the example in JavaScript readme doc to 4.7

- doc/swift-target.md
@parrt This is to put in performance note for the Swift target.
> Updated swift-target.md.

- runtime/Python3/src/antlr4/__init__.py
This pull request resolves Issue #2012.
> Import RuleContext into the antlr4 module namespace. See Issue #2012.

- doc/getting-started.md
Introduced newlines to have better view of steps.
> Minor formatting

- runtime/Java/pom.xml
- tool/pom.xml
This silences warnings from Maven.
> Add some version numbers to pom.xml.

- tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
- tool/src/org/antlr/v4/tool/ErrorType.java
> All error codes distinct

- runtime-testsuite/test/org/antlr/v4/runtime/TestCodePointCharStream.java
- runtime/Java/src/org/antlr/v4/runtime/CodePointCharStream.java
> Fixed empty CodePointCharStream throwing exception on getText.

- contributors.txt
- doc/getting-started.md
I didn't change any of the code. Only update version numbers in the documentation for getting-started.md
> Change all mentions of 4.5.3 in getting-started to 4.7

- appveyor.yml
> Update AppVeyor version number to 4.7.1-SNAPSHOT.

- runtime/Go/antlr/interval_set.go
- runtime/Go/antlr/interval_set_test.go
Added additional interval math functionality
> [Go] Interval

- doc/getting-started.md
Introduction to install on Unix based systems version mismatch.
> getting-started.md

- appveyor.yml
These cache the Maven and nuget package directories.
> Add cache entries to appveyor.yml.

- runtime/Swift/Sources/Antlr4/atn/ATNDeserializer.swift
Remove lots of unnecessary type annotations, replace unnecessarily
complicated static initializers, and use "if let" and "guard let" to remove
lots of casting.
Bring together a couple of hundred lines of copy-paste code between
the deserialize and deserializeFromJson paths.
Fix some obvious bugs in the deserialize path.  This code is entirely unused;
we use deserializeFromJson in the autogenerated parsers.  I'm inclined to
remove deserialize since it was so broken, but I'm leaving it for now, in
case someone needs compatibility with ATNs from different language targets
and wants to fix it.
> Tidy ATNDeserializer.

- runtime/Go/antlr/common_token_stream.go
- runtime/Go/antlr/common_token_stream_test.go
These routines are public in the Java implementation.
> Export GetHiddenTokens routines

- .travis.yml
> Use csharp as main test target

- .travis.yml
> move python 2 back to main test stage since it’s a standalone target

- .travis.yml
- runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java
> Update to python 3.6

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs
- runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python3/src/antlr4/atn/ParserATNSimulator.py
> Fix #1955 python

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
- runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python3/src/antlr4/atn/ParserATNSimulator.py
> Fix #1955 javascript

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/Atn/ParserATNSimulator.cs
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
- runtime/Python2/src/antlr4/atn/ParserATNSimulator.py
- runtime/Python3/src/antlr4/atn/ParserATNSimulator.py
> Fix #1955 csharp

- doc/getting-started.md
> Updated antlr version for windows

- doc/getting-started.md
Otherwise it throws "Can't load Hello as lexer or parser" error
> Updating current directory in classpath

- contributors.txt
- runtime/Python3/src/antlr4/ParserRuleContext.py
> Fix Index Error in Python3 GetChild

- .travis/run-tests-python2.sh
- .travis/run-tests-python3.sh
- runtime/Python2/tests/run.py
- runtime/Python3/test/run.py
@ericvergnaud  I notice that the python tests are not used in travis. Here I enable the python tests.
> update test script

- contributors.txt
- doc/javascript-target.md
> Added visitor example.

- runtime/CSharp/runtime/CSharp/Antlr4.Runtime/TokenStreamRewriter.cs
- runtime/Cpp/runtime/src/TokenStreamRewriter.cpp
- runtime/Cpp/runtime/src/tree/xpath/XPath.cpp
- runtime/Python2/src/antlr4/TokenStreamRewriter.py
- runtime/Python3/src/antlr4/TokenStreamRewriter.py
Fix proposition for https://github.com/antlr/antlr4/issues/2547
> Fix overlaping condition

- contributors.txt
https://github.com/antlr/antlr4/pull/2571
Adding myself to the contributors.txt file
> Test cases

- tool-testsuite/test/org/antlr/v4/misc/UtilsTest.java
I've analysed your codebase and noticed that `org.antlr.v4.misc.Utils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
> Add unit tests for org.antlr.v4.misc.Utils

- doc/cpp-target.md
- runtime/Cpp/demo/Mac/antlrcpp-demo.xcodeproj/project.pbxproj
- runtime/Cpp/runtime/antlrcpp.xcodeproj/project.pbxproj
- runtime/Cpp/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4.xcscheme
- runtime/Cpp/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4_ios.xcscheme
- runtime/Cpp/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4_static.xcscheme
Mostly updated project settings after XCode upgrade.
> Some non-code changes in C++ runtime

- tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
This PR improves code generation of the PHP target.
> Remove redundant assignment, optimize autoloading and tweak code style

- contributors.txt
- tool/src/org/antlr/v4/parse/ANTLRLexer.g
- tool/src/org/antlr/v4/parse/ANTLRParser.g
> replace gramamr with grammar

- contributors.txt
- runtime/JavaScript/src/antlr4/error/index.js
- runtime/JavaScript/src/antlr4/index.js
Ran into same issues as in #1759 while using with angular.
> fix for issues in #1759

- .travis.yml
- .travis/before-install-linux-dart.sh
- appveyor.yml
> Pin dart version to 2.8.4 to get unit tests passing

- .travis.yml
- .travis/before-install-linux-dart.sh
- doc/dart-target.md
> Fix travis ci for Dart pin version

- runtime/JavaScript/src/antlr4/PredictionContext.js
- runtime/JavaScript/src/antlr4/Utils.js
- tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
Fix #2745 (nb would be great to have a test that reproduces the issue)
> Fix template issue

- doc/cpp-target.md
> cpp-target.md link broken fix

- runtime/Python3/src/antlr4/PredictionContext.py
> Fix undefined value

- doc/lexicon.md
> add a missing space

- runtime/Java/src/org/antlr/v4/runtime/tree/Tree.java
> fix a typo

- doc/faq/parse-trees.md
> Fix typo - our -> are

- antlr4-maven-plugin/pom.xml
> maven-plugin-plugin 3.6.0

- runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
> Fix invalid import

- tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
fixes #2193 (item 2) and other similar issues
> Fix incorrect python token string templates

- runtime/JavaScript/src/antlr4/PredictionContext.js
> rollback partially incorrect fix for #2902

- tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
> Potential fix to #2980

- tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
> ensure 1 statement per line to help debug

- runtime/JavaScript/package.json
> upgrade ini

- runtime-testsuite/processors/src/org/antlr/v4/test/runtime/CommentHasStringValueProcessor.java
@parrt can you check if this works for you?
> Potential fix to #3038

- .gitignore
- runtime/CSharp/Atn/LL1Analyzer.cs
- runtime/CSharp/DefaultErrorStrategy.cs
- runtime/Cpp/runtime/src/atn/LL1Analyzer.cpp
- runtime/Go/antlr/ll1_analyzer.go
- runtime/JavaScript/src/antlr4/LL1Analyzer.js
- runtime/JavaScript/src/antlr4/error/ErrorStrategy.js
- runtime/Python2/src/antlr4/LL1Analyzer.py
- runtime/Python2/src/antlr4/error/ErrorStrategy.py
- runtime/Python3/src/antlr4/LL1Analyzer.py
- runtime/Python3/src/antlr4/error/ErrorStrategy.py
- runtime/Swift/Sources/Antlr4/atn/LL1Analyzer.swift
> Update ll1 analyzer

- doc/releasing-antlr.md
> Include prerequisite documentation to publish Dart target

- runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTestSupport.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/MockIntTokenStream.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTestSupport.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTestUtils.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/cpp/BaseCppTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/csharp/BaseCSharpTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/dart/BaseDartTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/go/BaseGoTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/java/BaseJavaTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/javascript/BaseNodeTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/php/BasePHPTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/python/BasePythonTest.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/python2/BasePython2Test.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/python3/BasePython3Test.java
- runtime-testsuite/test/org/antlr/v4/test/runtime/swift/BaseSwiftTest.java
- tool-testsuite/test/org/antlr/v4/test/tool/BaseJavaToolTest.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestATNInterpreter.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestATNLexerInterpreter.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestATNParserPrediction.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestCompositeGrammars.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestDollarParser.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestParserExec.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestParserProfiler.java
- tool-testsuite/test/org/antlr/v4/test/tool/TestPerformance.java
> Sanitize test code base

- .circleci/config.yml
- .circleci/scripts/install-linux-php.sh
- .circleci/scripts/run-tests-php.sh
> reinstate PHP ci on circle-ci

- .appveyor/workflow.yml
- .circleci/scripts/install-linux-javascript.sh
- .circleci/scripts/run-tests-javascript.sh
- runtime/JavaScript/package.json
- runtime/JavaScript/src/antlr4/IntervalSet.js
- runtime/JavaScript/src/test/TestIntervalSet.test.js
> Fix javascript intervals

- contributors.txt
- doc/javascript-target.md
> fix javascript import in example code

- runtime/JavaScript/src/antlr4/Parser.js
> always trigger enter/exit rules (same as Java/C#)

- contributors.txt
- runtime/JavaScript/src/antlr4/InputStream.js
If you know feature array size then it faster to init array with `new Array(size)` instead of `array.push`. Here comparison https://jsbench.me/67ko818eiq/1
> Javascript runtime: InputStream performance optimization

- contributors.txt
- docker/.dockerignore
- docker/Dockerfile
- docker/README.md
This PR adds initial support for Docker. Its based on original PR #2810 by @krzkaczor (who has been added to the contributors list)
> Add Docker image for transparent calling of ANTLR4 from a command line.

- doc/javascript-target.md
Noticed the issue while using the documentation.
> Indent JavaScript example code

- runtime/JavaScript/src/antlr4/IntervalSet.js
- runtime/JavaScript/src/antlr4/atn/ParserATNSimulator.js
> Fix bug 3270

- runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java
> add heartbeat to csharp/recursion

- contributors.txt
- runtime/CSharp/src/Antlr4.csproj
> Added .NET Framework 4.6.2 target csharp runtime

- runtime/JavaScript/package-lock.json
- runtime/JavaScript/package.json
> Fix dependabot alert

- runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java
> target is dotnet, not csharp

- contributors.txt
- doc/cpp-target.md
> Add explanation about lifetime of parse tree to cpp-target.md#memory-management

- tool/src/org/antlr/v4/codegen/ActionTranslator.java
Fix remaining complaints related to non-exhaustive switch statements.
> [Java] Fix remaining complaints from ErrorProne static analysis

- runtime/Cpp/runtime/src/atn/LexerATNSimulator.cpp
> Fix reported memory leak

- .circleci/config.yml
- .circleci/scripts/run-tests-cpp.sh
- .circleci/scripts/run-tests-dart.sh
- .circleci/scripts/run-tests-dotnet.sh
- .circleci/scripts/run-tests-go.sh
- .circleci/scripts/run-tests-javascript.sh
- .circleci/scripts/run-tests-php.sh
- .circleci/scripts/run-tests-python2.sh
- .circleci/scripts/run-tests-python3.sh
- .circleci/scripts/run-tests-swift.sh
- antlr4-maven-plugin/pom.xml
- doc/antlr-project-testing.md
- doc/building-antlr.md
- pom.xml
- runtime-testsuite/pom.xml
- runtime/Java/pom.xml
- tool-testsuite/pom.xml
- tool/pom.xml
trying to do some updates to the version numbers to get cleaner maven compiles / installs.
> Update maven plugin versions

- runtime/Cpp/demo/Mac/antlrcpp-demo.xcodeproj/project.pbxproj
- runtime/Cpp/runtime/antlrcpp.xcodeproj/project.pbxproj
Some small fixes to make the C++ runtime demo build in latest Xcode.
> Fixed C++ runtime demo

- .github/workflows/windows.yml
- runtime/Java/pom.xml
> GitHub windows runner

- README.md
> display Github status for windows

- .github/scripts-windows/run-tests-python2.cmd
- .github/scripts-windows/run-tests-python3.cmd
- .github/workflows/windows.yml
> Python GitHub action

- .github/scripts-windows/run-tests-csharp.cmd
- .github/workflows/windows.yml
> GitHub action csharp

- .github/scripts-windows/run-tests-dart.cmd
- .github/workflows/windows.yml
> GitHub action dart

- .github/scripts-windows/run-tests-go.cmd
- .github/workflows/windows.yml
> GitHub action go

- .github/scripts-windows/run-tests-php.cmd
- .github/workflows/windows.yml
> GitHub action php

- runtime/Cpp/cmake/README.md
> [C++] Update cmake README.md to C++17

- antlr4-maven-plugin/pom.xml
> Follow maven guidelines for maven-plugin

- runtime/Go/antlr/error_strategy.go
- runtime/Go/antlr/parser.go
> make InErrorRecoveryMode public for go

- runtime/Cpp/runtime/src/antlr4-common.h
@parrt Simple cleanup of unused headers.
> [C++] Remove duplicate includes and remove unused includes

- tool/src/org/antlr/v4/codegen/Target.java
- tool/src/org/antlr/v4/codegen/target/CSharpTarget.java
- tool/src/org/antlr/v4/codegen/target/DartTarget.java
- tool/src/org/antlr/v4/codegen/target/PHPTarget.java
- tool/src/org/antlr/v4/codegen/target/SwiftTarget.java
Generates bigger ATN again but don't want to break lots of builds with utf-8 assumption (it did internally in at least one company).
> Ascii only ATN serialization

- runtime/JavaScript/package.json
> fix dependabot issues

- tool-testsuite/test/org/antlr/v4/test/tool/TestSymbolIssues.java
- tool/src/org/antlr/v4/automata/ParserATNFactory.java
The fixed version of https://github.com/antlr/antlr4/pull/3564
> Fix NPE for undefined label, fix antlr#2788

- runtime/Cpp/runtime/src/RuntimeMetaData.cpp
- runtime/Cpp/runtime/src/Version.h
- runtime/Cpp/runtime/src/antlr4-common.h
- runtime/Cpp/runtime/src/antlr4-runtime.h
> [C++] Introduce version macros

- runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java
fixes: #3720
Signed-off-by: Will <dazeydev.3@gmail.com>
> Issue 3720: Java 2 Security issue

- Package.swift
Add static library distribution in SPM
> Update Swift Package to support static library

- runtime-testsuite/test/org/antlr/v4/test/runtime/states/State.java
> Augment error message during testing to include full cause of problem (round 2)

- tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
- tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
Tweak to constant propagation/folding in https://github.com/antlr/antlr4/pull/3701
> Tweak folding to wrap && operations in parentheses

- doc/listeners.md
Signed-off-by: Eric Mutta <eric.mutta@gmail.com>
> Fix typos in listeners.md

- .github/workflows/hosted.yml
> Gcc version fix

- .github/workflows/hosted.yml
Signed-off-by: Terence Parr <parrt@antlr.org>
> php composer install

- runtime/JavaScript/src/antlr4/Parser.js
> Fix issue #3710

- doc/releasing-antlr.md
> Update release docs

- README.md
moved antlr description before versioning strategy
> present antlr before versioning

- runtime/JavaScript/src/antlr4/TokenStream.d.ts
> [TypeScript] Fix incorrect typings

- runtime/CSharp/src/Atn/LexerATNSimulator.cs
Allow user to subclass and consume differently. Useful for CR handling as suggested in https://github.com/antlr/antlr4/pull/2519
> Update LexerATNSimulator.cs with virtual Consume

- docker/Dockerfile
- docker/README.md
Added support for s390x
Also updated base image for multi-arch support.
> Update base image to add multi-arch support

- runtime/Python3/src/antlr4/atn/ATNDeserializer.py
> Minor typo

- runtime/JavaScript/package.json
fixes https://github.com/antlr/antlr4/issues/4285
> Fixed file paths used in `package.json#exports.types`

- tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg
> Implement consistent file extensions for Typescript imports

- runtime/JavaScript/src/antlr4/Token.d.ts
issue #4110:
https://github.com/antlr/antlr4/issues/4110#issuecomment-1898214382
> added Token.DEFAULT_CHANNEL and Token.HIDDEN_CHANNEL

- .github/workflows/hosted.yml
Install composer before using it.
> Fix Github Actions

- .github/workflows/hosted.yml
Maybe this will fix the macos/php CI run?
> Switch CI to macos-12 and PHP 8.3

- doc/cpp-target.md
Fixes https://github.com/antlr/antlr4/issues/4511
> Update C++ documentation to state that C++17 is required

- README.md
> chore: fix error link

- runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/TypeScript.test.stg
Fix no longer valid test templates
> Fix failing tests
